pulsar/internal/commands_test.go

The Go map doesn't guarantee any ordering (it changes across different instances of the map object, even for the same keys), so the test cannot make assumptions.

Fixed flaky TestConvertStringMap

---

Dockerfile
run-ci.sh

Since we move utils code to `./pkg` and `./util`, updating the script that looks for test files in subdirs.

Run tests on all the subdirectories

---

pulsar/internal/default_router.go

Fix runtime error: integer divide by zero
The `maxBatchingDelay.Nanoseconds()`  may be zero, so we need check zero.

Fix runtime error: integer divide by zero

---

Dockerfile
pkg/compression/zlib.go

Seems Integration tests failed for reason:
```
E: Package `openjdk-8-jre-headless` has no installation candidate
```
We can't download  `openjdk-8-jre-headless` lib for integration tests, so we choose to replace a way to install java8 environment.

Fix the openjdk-8-jre-headless can't download

---

pkg/compression/zlib.go

Fixes #34 
In `reader.Read()`, only a portion of the data will be read at a time. Here we should read all the data until it encounters `io.EOF` and then returns.
This problem has not been reproduced in the previous Test case, because we ignored the processing of error, so whether it succeeds or not, he returns correctly.

[issue:34] Fix zlib compress Decompress logic

---

.gitignore

Ignore some files that are automatically generated in the project, as follows:
```
.idea/
*.DS_Store
*.swp
*.out
```

Ignore some files that are automatically generated in the project

---

pulsar/consumer_test.go
pulsar/internal/commands.go
pulsar/internal/commands_test.go

Fixes #40 #39 #33 
"Payload" command frame format (It has the same 3 fields as a "simple" command, plus the following):
|"Simple" fields var length|magicNumber (0x0e01) 2 bytes|checksum (CRC32-C) 4 bytes| metadataSize (uint32) 4 bytes| metadata (protobuf encoded) var length| payload (bytes) totalSize - (SUM others)|
|----|----|----|----|----|----|
||OPTIONAL If present, indicates following 4 bytes are checksum|OPTIONAL Checksum of the following bytes| size of the metadata| |Any sequence of bytes, possibly compressed and or encrypted (see metadata)|
When using batch messages, the payload will be containing a list of entries, each of them with its individual metadata, defined by the `SingleMessageMetadata` object.
```
singleMetaSize(4 …
```

[issue:40]Fix producer send protocol error

---

pulsar/impl_client_test.go
pulsar/impl_producer.go
pulsar/producer.go
pulsar/producer_test.go
pulsar/test_helper.go

Fixes #45 
In the original code logic, if the user customized the `MessageRouter` policy, the `messageRouter` of producer is not initialized. The pull request will fix it.

[Issue:45] Fix the logic of message router

---

run-ci.sh

Fixes #49
By default, timeout exit after 10 minutes
```
go test --help
-timeout d
If a test binary runs longer than duration d, panic.
If d is 0, the timeout is disabled.
The default is 10 minutes (10m).
```

[Issue:49]Fix test killed with quit: ran too long

---

pulsar/unackedMsgTracker.go

Change-Id: I9d5d544808a6f739d79776a4f154d7caceaa133c
remove extra timeout param on UnackedMessageTracker#handlerCmd

refactor: remove extra timeout param

---

license_test.go
pulsar/impl_consumer.go
pulsar/impl_partition_producer.go
pulsar/internal/connection.go
pulsar/unacked_msg_tracker.go
pulsar/unacked_msg_tracker_test.go

Fixes #72
This patch adds locking to fix all the data race warnings when discovered when running.
`go test ./... -race`

[ISSUE #72] Fix data race conditions.

---

pulsar/impl_partition_consumer.go
pulsar/impl_partition_producer.go
pulsar/internal/connection.go
pulsar/internal/rpc_client.go

We're not currently handling the `ServerError` responses in the `RpcClient`. That leaves the caller hanging when any request fails on broker side.

Handle RPC errors in reconnections

---

pulsar/impl_partition_consumer.go
pulsar/internal/connection.go
pulsar/internal/connection_reader.go

Fixed locking around the `mapMutex` in consumer. The current behavior is mixing read-write and read-only locks even when modifying the map. 
The `pendingReqs` was really meant to be accessed by a single go-routine. Changed the logic to pass the received commands on a channel, to be processed in the connection's own go-routine.
cc/ @cckellogg

Fixed locking between connection_reader and connection

---

Dockerfile

We shouldn't be using Oracle JDK and especially automatically accepting the condition when building the image.
If Java 8 is not available on the go-1.12 image, we can switch to the default java 11 package.

Switch to OpenJDK for CI

---

pulsar/impl_message.go
pulsar/impl_message_test.go
pulsar/message.go

Added a tracker so the client can ack batched messages. This is just the framework and needs additional patches to make it work.

Added a message id tracker for acking messages that are batched.

---

pulsar/impl_partition_producer.go
pulsar/internal/blocking_queue.go
pulsar/internal/blocking_queue_test.go
pulsar/internal/semaphore.go
pulsar/producer_test.go

Move blocking queue and semaphore to the internal package so they are not exported with the client. These are only for internal purposes.

Move util files to internal so they are not exported.

---

examples/consumer-listener/consumer-listener.go
examples/consumer/consumer.go
perf/perf-consumer.go
pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/impl_producer.go
pulsar/negative_acks_tracker.go
pulsar/negative_acks_tracker_test.go
pulsar/producer_test.go

Added negative acks tracker and integration in the consumer. 
Fixed the API to not return errors for Ack and Nack since these operations will never fail given that we don't wait for confirmation.
cc/ @cckellogg

Added negative acks tracker and integration

---

pulsar/consumer_partition.go
pulsar/internal/commands.go
pulsar/internal/commands_test.go
pulsar/internal/connection.go
pulsar/internal/lookup_service_test.go
pulsar/internal/rpc_client.go

Simplified the rpc client handling of request that don't need to track the response.

Fixed RpcClient.RequestOnCnxNoWait() to not require a request id

---

pulsar/client.go
pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_partition_test.go
pulsar/consumer_test.go
pulsar/impl_client.go
pulsar/impl_client_test.go
pulsar/impl_partition_producer.go
pulsar/impl_producer.go
pulsar/internal/closable.go
pulsar/producer.go
pulsar/producer_test.go
pulsar/reader.go

Fixes #17. As per discussion, simplify the API by allowing `defer client.Close()` methods. Internally, we need to make sure we release all the resources even when we have failures.

Remove error return on Close() methods

---

pulsar/consumer_partition.go
pulsar/consumer_partition_test.go
pulsar/consumer_test.go
pulsar/internal/batch_builder.go
pulsar/internal/commands.go
pulsar/internal/connection.go

Implemented the batch decompression on the consumer side

Implemented decompression on consumer side

---

pulsar/client_impl.go
pulsar/client_impl_test.go
pulsar/impl_partition_producer.go
pulsar/impl_producer.go
pulsar/internal/commands.go
pulsar/producer_test.go
pulsar/test_helper.go

This patch is needed to implement the regex consumer. Doing this in a separate patch to make reviews easier.

Add client function to list topics in a namespace.

---

pulsar/impl_producer.go

Fix error set bug in impl_producer.go
```go
if pe.err != nil {
err = pe.err
}
```
- If a feature is not documented yet in this PR, please create a followup issue for adding the …

[Producer] Set error only if not nil

---

pulsar/producer_impl.go
pulsar/producer_partition.go
pulsar/producer_test.go

This fixes a seg fault when a producer with the same name is created for a topic. 
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd755d6]
goroutine 48 [running]:
github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).Close(0x0)
github.com/apache/pulsar-client-go/pulsar/impl_partition_producer.go:443 +0x26
github.com/apache/pulsar-client-go/pulsar.newProducer(0xc0000c68c0, 0xc000342780, 0x58, 0x58, 0xc000596360)
github.com/apache/pulsar-client-go/pulsar/impl_producer.go:103 +0x31c
github.com/apache/pulsar-client-go/pulsar.(*client).CreateProducer(0xc0000c68c0, 0xc0000344c0, 0x13, 0x1030d22, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
github.com/apache/pulsar-client-go/pulsar/client_impl.go:94 +0x7a
```

Fix seg fault when producer with same name is created.

---

pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/helper.go
pulsar/helper_test.go
pulsar/producer_partition.go
pulsar/producer_test.go
pulsar/test_helper.go

Add the metadata to the produce and subscribe commands (the other clients support this) so the properties from the configs will show up in the topic stats response from the brokers.

Add metadata to produce and subscribe commands.

---

pulsar/client_impl.go
pulsar/internal/client_handlers.go
pulsar/internal/client_handlers_test.go

fix race condition caused by writing to map in multiple goroutines
Created new internal type: ClientHandlers which encapsulates a sync.Mutex to make read/writes to clients.handlers concurrent safe.
This change added tests and can be verified as follows:  just run: `go test -timeout 30s github.com/apache/pulsar-client-go/pulsar/internal -run "^(TestClientHandlers)$"`

[Issue 118][client_impl.go] fix race condition when accessing client.handlers

---

pulsar/negative_acks_tracker_test.go

Make the nack tracker test for robust. I've seen them occasionally fail.
https://builds.apache.org/job/pulsar_precommit_client_go/195/console

Make nack tracker tests more robust.

---

pulsar/consumer_test.go
pulsar/negative_acks_tracker_test.go
pulsar/producer_partition.go
pulsar/producer_test.go

Fixes #123
Fixes #76 
Fixes #114 
If the current message being published does not fit in the current batch that message is never sent. This patch will add the message to the batch after flushing the current batch.

[Issue #123] Ensure message is sent if no room in current batch.

---

perf/perf-producer.go
pulsar/client.go
pulsar/consumer.go
pulsar/consumer_test.go
pulsar/producer.go
pulsar/producer_test.go

There are some config options that are currently ignored in the Go client and make more sense in C++ client lib. Removing them for now, until it's clear that we need them.

Removed unused config options

---

perf/pulsar-perf-go.go

This change ensures that the go routine listening for the interrupt exists properly. It work before because we exited the program whenever we received a signal from this channel. This change just ensures proper clean up so we don't ever leak a go routine.

Exit goroutine when signal is caught.

---

perf/perf-producer.go
pulsar/producer.go

`SendTimeout` is not currently being used, rather we are relying on the `ctx` object to timeout the send requests

Removed SendTimeout from producer options

---

pulsar/client.go
pulsar/client_impl.go
pulsar/internal/connection.go
pulsar/internal/connection_pool.go

When creating connections, we need to honor the connection timeout specified in the `ClientOptions`.

Use the specified connection timeout when creating connections

---

pulsar/consumer_impl.go
pulsar/consumer_test.go

If the consumer has been closed a call to receive should not block and return an error.

[Issue #140] Consumer should not block on received if closed.

---

examples/producer/producer.go
pulsar/consumer_regex_test.go
pulsar/consumer_test.go
pulsar/producer.go
pulsar/producer_impl.go
pulsar/producer_partition.go
pulsar/producer_test.go

As it was already done on the C++ based client as well, we should return the MessageID even on the sync send operation, before we freeze the API on release.

Make producer.Send() to also return MessageID

---

pulsar/consumer_partition.go
pulsar/internal/connection.go
pulsar/internal/connection_pool.go
pulsar/internal/lookup_service.go
pulsar/internal/lookup_service_test.go
pulsar/internal/rpc_client.go
pulsar/producer_partition.go

Fixes: #145 
if producer connect to broker through pulsar proxy, producer will get `Short read when reading frame size` error because pulsar proxy not pass commands to broker.

[Issue #145] fix producer cannot connect to broker through pulsar proxy

---

.golangci.yml

We should error on the side of readability in
code base so we don't need the maligned lint flag.

Remove maligned check from linter.

---

pulsar/consumer_partition.go
pulsar/internal/connection.go
pulsar/internal/connection_pool.go
pulsar/internal/lookup_service.go
pulsar/internal/lookup_service_test.go
pulsar/internal/rpc_client.go
pulsar/producer_partition.go

The PR #146 has completely broken the connection pool logic. Closed/failed connection are not being evicted from the pool anymore, resulting in permanent failures with no recovery.
The change in #146 added an unnecessary flag throughout the code. We just need to check whether the physical address is the same as the logical address. The only part missing was to the pass the hostname to the proxy when needed.

Fixed the connection pool logic

---

pulsar/internal/connection.go

We're processing the "connection closed" event twice when the broker sends a "producer closed" or "consumer closed" command. 
Basically after the producer reconnects, it will reconnect again on the same connection because it got the notification 2 times. One when the graceful close command and another when the connection is closed (eg: broker is shutting down).
This is not harmful, though it's logically wrong.

Avoid double cnx close notification on graceful server side close

---

pulsar/internal/connection_reader.go

Fixes #147
There is bug in the `connection_reader` routine. If a frame is spanning multiple IP packets, it might get the case where we have read a partial frame into the current buffer and then we have to read the remainder of the frame from the socket. 
Instead of reading the remainder, we were trying to read the full frame size, which in turn will lead to the connection reader getting stuck. The connection eventually will fail the ping probe and will get closed though new connections incur in the same issue.

Fixed reading from connection

---

pulsar/internal/connection_pool.go

When we try to create a new connection, if `!wasCached` is true, the `newConnection`  related memory should be freed.

Fixed memory leak of connection

---

pulsar/internal/rpc_client.go

Change the RPCResultChannel to a buffer channel to avoid blocking connection.Run() when request timeout occuers
https://github.com/apache/pulsar-client-go/issues/144
https://github.com/apache/pulsar-client-go/issues/151
Signed-off-by: dsmlily <dsmlily_2008@126.com>

res channel causes connection.Run() to block When request timeout occuers

---

pulsar/internal/lookup_service.go

Fixes #173
Fix `logrus` crash, the error as follows:
```
panic: reflect: call of reflect.Value.Type on zero Value
```

[Issue:173] Fix logrus crash

---

pulsar/consumer_test.go
pulsar/internal/batch_builder.go
pulsar/producer_partition.go

Currently, when we specify the `Key` for the message, the broker can not receive the partition key. 
- set partition key in BatchBuilder

Fix partition key not set in batch builder

---

pulsar/consumer_impl.go
pulsar/internal/client_handlers.go
pulsar/internal/client_handlers_test.go
pulsar/producer_impl.go

Fixes: #153 
Makes producer & consumer removed from client handler when producer / consumer closed.

[Issue #153] Fix handler memory leak

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_partition.go
pulsar/consumer_regex.go
pulsar/consumer_test.go
pulsar/internal/connection.go

Master Issue: [#148](https://github.com/apache/pulsar-client-go/issues/148)
*Add seek by messageID*
*Add seek by messageID*
*Refactor some UT code*
*(example:)*
- *Added integration tests for seek by messageID*
- The public API: (*yes* / no)
- If a feature is not documented yet in this …

[Issue-148][pulsar-client-go] add seek by messageID

---

pulsar/client_impl.go

Fixes #181 
When the topic is non-partitioned topic, the  `res.Response.PartitionMetadataResponse` value is nil, so we can't get `Error` or `GetPartitions` of `PartitionMetadataResponse`, Otherwise it will cause:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x84f47a]
```
- Fix nil pointer dereference of PartitionMetadataResponse

Fix nil pointer dereference of PartitionMetadataResponse

---

pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/message.go
pulsar/producer_partition.go
pulsar/producer_test.go

When producing a message, we are currently accepting event time as a pointer:
```go
type ProducerMessage struct {
/// .... 
// EventTime set the event time for a given message
EventTime *time.Time
}
```
though on a receiving message, we're exposing as a value: 
```go
type Message interface {
/// ...
// PublishTime get the publish time of this message. The publish time is the timestamp that a client
// publish the message.
PublishTime() time.Time
// EventTime get the event time associated with this message. It is typically set by the applications via
// `ProducerMessage.EventTime`.
// If there isn't any event time associated with this event, it will be nil.
EventTime() time.Time
```
We should unify these 2 and also with the same approach used for `PublishTime`.

Expose EventTime consistently as a non-pointer

---

pulsar/internal/rpc_client.go

Fix issue #190 
https://github.com/apache/pulsar-client-go/issues/190
Make sure the client connection retry is bound to OperationTimeout, instead of the current implementation is the next retry backoff time is no more than OperationTimeout, thus we can reduce the number retries.
The total time spent on retry won't be over OperationTimeout.
The first retry will be one second later instead of the current immediate retry with only very small increment at 100ms in the second retry. The new implementation basically increase the gaps to 1, 2, 4, 8 ... seconds
Manual test verification
- Dependencies (does it add or upgrade a dependency): ( no )
- The public API: ( no )
- The schema: ( no )
- The default values of configurations: ( no )
- The wire protocol: ( no )
- Does this pull request …

[Issue 190] RequestTimeout bound client connection backoff

---

pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/impl_message.go
pulsar/message.go

Master Issue: #201 
- Expose `GetDeliveryCount()` method from `Message` interface
- Add test case to verfiy

[Issue: 201] Expose GetDeliveryCount method from Message interface

---

pulsar/consumer_test.go
pulsar/internal/default_router.go
pulsar/internal/default_router_test.go
pulsar/producer_impl.go
pulsar/producer_partition.go
pulsar/producer_test.go
pulsar/test_helper.go

Currently, the Go producer will only produce to a single partition if BatchingMaxPublishDelay is not specified.  BatchingMaxPublishDelay will be zero and the logic in the DefaultRouter will always select partition 0.

Fix Go Producer produce to only one partition

---

pulsar/producer_partition.go
pulsar/producer_test.go

The logic to check if a message can be batched is currently broken because `deliverAt.UnixNano()` is not actually returning a 0 when the `deliverAt` is uninitialized. Rather it represent a timestamp in the far past which is changed into a negative timestamp (< Jan 1970).

Fixed batching flag logic

---

pulsar/client_impl.go
pulsar/internal/lookup_service.go
pulsar/internal/lookup_service_test.go

I tried a tls connection but it failed.
Log:
```
$ go run producerForTls.go
pulsar.NewClient start.pulsar.NewClient end.INFO[0000] Connecting to broker                          remote_addr="pulsar+ssl://<hostname>:6651"
INFO[0000] TCP connection established                    local_addr="<ip>:<port>" remote_addr="pulsar+ssl://<hostname>:6651"
INFO[0000] Connection is ready                           local_addr="<ip>:<port>" remote_addr="pulsar+ssl://<hostname>:6651"
INFO[0000] Connecting to broker                          remote_addr="pulsar://<hostname>:6650"
WARN[0000] Failed to connect to broker.                  error=EOF remote_addr="pulsar://<hostname>:6650"
INFO[0000] Connection closed                             remote_addr="pulsar://<hostname>:6650"
INFO[0002] Connecting to broker …
```

Fixed tls connection issue

---

pulsar/consumer_impl.go
pulsar/consumer_regex.go
pulsar/consumer_test.go
pulsar/producer_impl.go
pulsar/producer_test.go
pulsar/test_helper.go

Client should automatically discover new partitions as they're added.

Auto update the client to handle changes in number of partitions

---

pulsar/producer_partition.go

In `Producer.Send()` we're unnecessarily forcing a flush operation. This piece of code was a remnant from an early prototype and should have been removed when the proper handling of batching was introduced.
In this case, since we're calling `internalSendAsync()` with `flushImmediately=true` the message will be immediately sent.

Removed unnecessary flush in sync Send() operation

---

pulsar/producer_partition.go

There is a race condition that make `Producer.Flush()` to get stuck. 
The flush operation works by attaching itself as a callback on the last item in the pending messages queue. Once the (current) last message in the queue is published, then flush is completed. 
The problem is that we check the last item in queue and then we grab a mutex and add the flush request. If the the pending item is completed before we grab the mutex, then the flush callback will never be called.

Fixed race condition in producer Flush() operation

---

pulsar/internal/commands.go
pulsar/internal/connection.go

This PR will fix a problem preventing consumer receiving empty payload with properties in non-batch mode; and empty payload without key and properties in batch mode. Error messages are prompted currently as such:
```
ERRO[0004] Discarding corrupted message                  msgID="ledgerId:92658 entryId:1458 partition:-1 " name=hwmiw subscription=consumer topic="<pulsar topic>" validationError=BatchDeSerializeError
ERRO[0004] handle message Id: ledgerId:92658 entryId:1458 partition:-1   consumerID=1 local_addr="192.168.1.111:33444" remote_addr="<pulsar URL>"
```
In addition, error will be printed out from MessageReceived instead of masking the real error reported.
The buffer capacity is validated instead of solely replying on ReadableBytes to determine EOF is reached.
Tested against batch …

allow empty payload for nonbatch message

---

go.mod
go.sum
pulsar/internal/compression/zstd.go

Fixes #244
The current implementation of `zstdProvider.Decompress` doesn't close the zstd decoder and will lead to memory leak, mentioned in the issue.
Use the `decoder.DecodeAll` to implement zstdProvider.Decompress and reuse the decoder.
And also upgrade klauspost/compress to v1.10.5.

[Issue 244][zstdProvider] Fix zstd memory leak

---

pulsar/internal/connection_reader.go

Master Issue: #200 
add internal connectionReader readAtLeast error information
these error information may help to solve #200 
function ```readAtLeast``` return error type 
- Dependencies (does it add or upgrade a dependency): (yes / ***no***)
- The public API: (yes / ***no***)
- The schema: (yes / ***no*** / don't know)
- The default values of configurations: (yes / ***no***)
- The wire protocol: (yes / ***no***)
- Does this pull request introduce a new feature? (yes / ***no***)

[Issue #200] feature: add internal connectionReader readAtLeast error information

---

pulsar/consumer_partition.go
pulsar/impl_message.go
pulsar/message.go

Master Issue: #243 
- Expose isReplicated and replicatedFrom for Pulsar message
- Add `replicatedFrom` filed on message struct

Expose replicated from filed on message struct

---

pulsar/producer_partition.go

Fixes #213 
Panic due to a race condition.
- access to `state` of `partitionProducer` is using atomic operations now to be thread-safe 
- `partitionConsumer` will probably need a similar fix as well
- `go test -race -count 100 -v -run 'TestDLQ$' .` does not panic anymore
This change is already covered by existing tests, such as `TestDLQ`.

[Issue 213] Fix data race when accessing partition producer state

---

pulsar/producer.go

Fixes #208 
- Fix send async comments

Fix send async comments

---

perf/perf-producer.go

Due to the use of goroutine, `stop <-chan struct {}` cannot be seen.
- Fix perf-produce cannot be closed

Fix perf-produce cannot be closed

---

perf/perf-producer.go

Signed-off-by: jonyhy96 <hy352144278@gmail.com>
Fix the wrong target in perf-producer
- Change the target of quantile in perf-producer from 0.90 to 0.50

Fix perf-producer target

---

pulsar/producer_partition.go

Fixes #<Issue 259>
after fail to add batchbuilder, should callback and release publishSemaphore.and fix the batch and single send logic

[Issue 259][pulsar-client-go] fix fail to add batchbuilder

---

pulsar/internal/batch_builder.go

This is a simple fix to tune down an excessive number of debug messages from "BatchBuilder flush: messages: " when producing messages with log level is set to debug. The log file would fill with "BatchBuilder flush: messages: 0" especially when `DisableBatching : true` and producing a low message rate.

skip debug print out when batch disabled with no messages

---

integration-tests/standalone.conf
pulsar/internal/batch_builder.go
pulsar/internal/commands.go
pulsar/internal/connection.go
pulsar/producer_partition.go
pulsar/producer_test.go

Fixes #240 
Issue #240: Add client-side check for max message size
1. When creating a connection, try to get maxMessageSize from handshake
response command. If it's not set, then use the default maxMessageSize
value defined in the client side.
2. When sending a message, check whether the size of payload exceeds
maxMessageSize. If so, return error immediately without adding this
meesage into sending queue.
3. To implement these, I made some tiny modifications in Connection
interface and added a field in its implementation struct.

[Issue 240] Add check for max message size

---

.github/workflows/go.yml
.github/workflows/project.yml
Dockerfile
docker-ci.sh

Currently, the Pulsar Go Client is only tested against Go version 1.12. The
motivation for this change is to help bring confidence that the Go client is
compatible with multiple versions of Go, all being tested with each PR.
I've modified the two GitHub Action workflows that are a part of this repo with
a [matrix](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) such that we test against multiple versions of Go.
I've also modified the current `docker-ci.sh` script and `Dockerfile` to allow for injecting a different go version other than the default `1.12`.

Build and test with multiple versions of Go

---

go.mod
go.sum
pulsar/internal/compression/zstd_cgo.go

While the pure Go ZStd library is very convenient, its performance is still ~50% slower than the native C ZStd library, per their own benchmarks: https://github.com/klauspost/compress/tree/master/zstd#performance
For this, if the application has already CGO enabled, we can use the native library.

When CGO is enabled, use C version of ZStd

---

pulsar/producer_impl.go

Fixes #271 
This fixes a race when a producer is closed and the number of partitions changed i.e. the topic is deleted just after the producer is closed.
It consists of stopping the ticker that controls the partition discovery in the background.
This is a trivial rework.

[Issue 271][Producer]Stop partition discovery on Close

---

pulsar/client.go
pulsar/client_impl.go
pulsar/internal/connection_pool.go

Similar to what we do in Java client, in certain conditions it might be useful to have more than one TCP connection to each broker. This increase the parallelism in client (more Go routines), brokers (connections get assigned to different IO threads) and also can improve the throughput at TCP level when the client is talking to a small number of brokers.

Allow to have multiple connections per broker

---

pulsar/internal/connection.go

This channel is used to pass data from producers to the connection go routine. It can become contended or blocking if we have multiple partition produces writing on a single connection. In general it's good to keep this above the number of partition producers assigned to a single connection.

Increase writeRequestsCh channel buffer size

---

go.mod
go.sum
pulsar/internal/compression/compression_bench_test.go
pulsar/internal/compression/test_data_sample.txt
pulsar/internal/compression/zstd_cgo.go
pulsar/internal/compression/zstd_go.go

Added microbenchmark to report compression and decompression speeds.
Current results:
```
$ go test --bench=. ./pulsar/internal/compression
goos: darwin
goarch: amd64
pkg: github.com/apache/pulsar-client-go/pulsar/internal/compression
BenchmarkCompression/zlib-16 	     177	   6735144 ns/op	  14.94 MB/s
BenchmarkCompression/lz4-16  	    1261	    912741 ns/op	 110.22 MB/s
BenchmarkCompression/zstd-pure-go-fastest-16         	     910	   1246418 ns/op	  80.72 MB/s
BenchmarkCompression/zstd-pure-go-default-16         	     615	   1855754 ns/op	  54.21 MB/s
BenchmarkCompression/zstd-pure-go-best-16            	     364	   2748821 ns/op	  36.60 MB/s
BenchmarkCompression/zstd-cgo-level-fastest-16       	    1908	    633766 ns/op	 158.74 MB/s
BenchmarkCompression/zstd-cgo-level-default-16 …
```

Microbenchmark for compression

---

pulsar/internal/batch_builder.go
pulsar/producer.go
pulsar/producer_partition.go
pulsar/producer_test.go

Previously, the producer maximum batch size was hard-coded to 128 KB.
Now, the produdcer maximum batch size is exposed via ProducerOptions
and defaults to 128 KB
Different applications producing to Pulsar require different batching policies.
Previously, users had control over the maximum batching delay and the maximum number of messages in a batch, but could not control the maximum number of bytes in a batch.  This change enables the latter. 
Expose a new `ProducerOption.BatchingMaxSize` (default: 128KB) that allows the user to configure the maximum batch size.  This option has been plumbed through `partition_producer` module to the `internal/batch_builder` module where it is used.
This change is already covered by existing tests, such as `producer_test.TestFlushInPartitionedProducer` and …

Expose BatchingMaxSize from ProducerOptions

---

pulsar/consumer_partition.go

Fixes #282 
In Shared Subscription, is is unable to unsubscribe the consumer(return an error). So 
it wasn't to mark the connection state to CLOSED.
Mark the connection state back to Ready when unsubscribe fails

[Issue #282] Fix unable to close consumer after unsubscribe in Shared Subscription

---

pulsar/producer_partition.go

When multiple go-routines are sharing the same producer instance, there will be contention and blocking on the channel that is used to dispatch to the partition handler.

Use maxPendingMessages for sizing producer eventsChan

---

pulsar/producer_impl.go

Multiple go-routines sharing a single producers are experiencing contention on the partitioned producer mutex that we acquire while using the router.
The mutex is there to protect the updates on the list of partitions, but we can optimize that away.

Avoid contention on producer mutex on critical path

---

go.mod
go.sum
pulsar/internal/compression/zstd_cgo.go

Fixes #274 
The Zstd wrapper we're using (`valyala/gozstd`) is shipping with pre-built binaries as a well. That is nice but it makes using CGo in Alpine very complicated (since `go build` tries to reuse the pre-built binaries but fails at it).
Switched to use `DataDog/zstd` which doesn't have pre-built binaries and use `ctx` API from zstd (merged in https://github.com/DataDog/zstd/pull/83) to improve internal memory usage.
```
BenchmarkCompression/zstd-cgo-level-fastest-16       	    2272	    513861 ns/op	 195.78 MB/s
BenchmarkCompression/zstd-cgo-level-default-16       	    1477	    772904 ns/op	 130.17 MB/s
BenchmarkCompression/zstd-cgo-level-best-16          	     254	   4670399 ns/op	  21.54 MB/s
BenchmarkDecompression/zstd-cgo-level-fastest-16     	    8382	    154040 ns/op	 653.11 …
```

Switched to DataDog zstd wrapper, reusing the compression ctx

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_test.go

Fixes https://github.com/apache/pulsar-client-go/issues/288

fix panic when creating consumer with ReceiverQueueSize set to -1

---

pulsar/client_impl_test.go
pulsar/consumer_partition.go
pulsar/internal/batch_builder.go
pulsar/internal/buffer.go
pulsar/internal/commands.go
pulsar/internal/compression/compression.go
pulsar/internal/compression/compression_bench_test.go
pulsar/internal/compression/compression_test.go
pulsar/internal/compression/lz4.go
pulsar/internal/compression/noop.go
pulsar/internal/compression/zlib.go
pulsar/internal/compression/zstd_cgo.go
pulsar/internal/compression/zstd_go.go
pulsar/internal/connection.go
pulsar/producer_partition.go

* Used pooled buffers when serializing a batch of messages
* Perform in-place compression into the batch buffer

Used pooled buffering for compression and batch serialization

---

pulsar/internal/semaphore.go
pulsar/internal/semaphore_test.go
pulsar/producer_partition.go

When there are multiple go-routines sharing a single producer instance, there can be significant contention on the channel that is used as a semaphore. 
That is because the channel is internally implemented with a mutex.
Instead, use a counter to optimize for the normal case scenario (when we're not blocked by the semaphore), leaving the channel as a way to synchronize when the semaphore has exhausted all the permits.

Added semaphore implementation with lower contention

---

pulsar/internal/batch_builder.go
pulsar/internal/connection.go
pulsar/producer_partition.go

The buffer pooling introduced in #292 has a serious bug in that the buffer gets released back to the pool after it's written on the connection. The problem is that, if there's a failure, a message can be written again after the reconnection, in which case we're sending garbage data. 
We need to tie the buffer lifecycle of the send request instead and, in that optic, it doesn't make to have the pool on the connection, rather it should be at the partition producer level.

Fixed pooled buffer lifecycle

---

pulsar/internal/blocking_queue.go
pulsar/internal/blocking_queue_test.go
pulsar/producer_partition.go

The blocking queue iterator method is not really thread safe in the presence of other read/write operations on the queue. While it makes a snapshot of what's readable at one point, if there are `Poll()` operations, it might be ending up reading new items before the new ones.
For that, it's better to make a copy of the items in the queue, also considering that iterating over this queue is only done on reconnections and it's not performance sensitive.

Removed blocking queue iterator

---

pulsar/reader_impl.go
pulsar/reader_test.go

Fixes #304 
User of the client's client's [CreateReader](https://github.com/apache/pulsar-client-go/blob/master/pulsar/client.go#L109) API can use a custom type satisfying the [MessageID](https://github.com/apache/pulsar-client-go/blob/master/pulsar/message.go#L108) interface, when using it as a value for `StartMessageID` in [ReaderOptions](https://github.com/apache/pulsar-client-go/blob/master/pulsar/reader.go#L48) argument for the mentioned API.
The current reader creation does an untested type assertion here, when preparing the `consumerOptions` needed for creating a `partitionConsumer`.
https://github.com/apache/pulsar-client-go/blob/master/pulsar/reader_impl.go#L64 
This assertion of `MessageID` as `*messageID` will fail unless an instance of `MessageID` is created from one of these …

[Issue 304][Reader] fixed panic in CreateReader API using custom MessageID for ReaderOptions

---

pulsar/internal/compression/zlib.go

As seen in tests for #310, there's a panic caused by having the wrong max buffer size estimate from the ZLib provider, because we're not considering the headers size for incompressible data.

Fix CompressMaxSize() for ZLib provider

---

pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/impl_message.go
pulsar/impl_message_test.go
pulsar/producer_partition.go

An int occupies one word of memory; on 64-bit machines, this is 8 bytes.
As a result, the messageID struct is 56-bytes:
* ledgerID - 8 bytes
* entryID - 8 bytes
* batchIdx - 8 bytes
* partitionIdx - 8 bytes
* tracker - 8 bytes
* consumer - 16 bytes (1 word for type, 1 word for data address)
This commit changes the type of batchIdx and partitionIdx fields to int32,
which saves one word of memory and maintains alignment of struct fields.
Reducing the size of the MessageID structs is important as they are
currently allocated on the heap for every message produced or consumed.
The motivation is to reduce the amount of heap allocated memory for each message produced and consumed.
This commit changes the type batchIdx and partitionIdx fields …

Reduce the size of the MessageID structs by one word on 64-bit arch

---

perf/perf-producer.go
pulsar/internal/batch_builder.go
pulsar/producer_partition.go

When a producer is publishing on many partitions, there can be significant memory overhead in maintaining a per-partition pool. Instead, there's not significant perf impact in using a single shared buffer pool.

Share buffer pool across all partitions

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_regex.go
pulsar/consumer_test.go

Supports the `Name()` interface on the consumer side, allowing users to customize their own consumer name. If the user does not specify, a default consumer name will be randomly generated
- add `consumerName` field in consumer struct
- add `consumerName` field in multiConsumer struct
- add `consumerName` field in regexConsumer struct

Add Name method to Consumer interface

---

pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_partition.go
pulsar/consumer_partition_test.go
pulsar/consumer_regex.go
pulsar/impl_message.go
pulsar/impl_message_test.go
pulsar/negative_acks_tracker.go
pulsar/negative_acks_tracker_test.go
pulsar/producer_test.go
pulsar/reader_impl.go

Passing a function parameter by pointer (or writing a pointer into a
channel) will cause the Go escape analysis to allocate the parameter on
the heap.
This change passes messageID struct instances by value instead of by
pointer; this keeps messageID structs on the stack.
Each message produced or consumed by the library is associated with
a MessageID; keeping instances of the MessageID structure on the stack
reduces heap allocation and associated GC cost.
Reduce the amount of per-Message heap allocation performed by the library
This change modifies the Consumer and Producer code paths to pass messageID struct instances by value instead of by
pointer; this keeps the messageID structures on the stack and off of the heap.
This change is …

Do not allocate MessageIDs on the heap

---

pulsar/internal/connection.go

Fixes #306 
Print a clean log when the connection failed.

[Issue 306] Change connection failed warn log to error and print error message

---

go.mod
go.sum

This fixes an issue with the latest master's `go.mod`
```
go get github.com/apache/pulsar-client-go/pulsar@master
go: found github.com/apache/pulsar-client-go/pulsar in github.com/apache/pulsar-client-go v0.1.2-0.20200715083626-b9f8c5cedefb
go: github.com/apache/pulsar-client-go master => v0.1.2-0.20200715083626-b9f8c5cedefb
go get: github.com/apache/pulsar-client-go@v0.1.2-0.20200715083626-b9f8c5cedefb requires
github.com/apache/pulsar-client-go/oauth2@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
Remove the "invalid version" and readded it

Fixes go.mod issue with invalid version

---

pulsar/producer_impl.go

Per Producer there is a goroutine leaked. The goroutine is used for the partition auto-discovery and will never exit.
This changes the goroutine to be properly exiting after a `Close()` on the producer.
pprof output no longer shows running goroutines from the producer.
*Worth considering:* Testing for goroutine leaks using https://github.com/uber-go/goleak

[producer] Fix producer goroutine leak

---

pulsar/consumer_partition.go
pulsar/internal/connection.go
pulsar/producer_partition.go

When the client creates a producer and a consumer with the same id, then the consumer processing handleCloseConsumer() will cause the producer with the same id to be unable to handle handleSendReceipt() and handleCloseProducer() in the future. The most direct impact is the Send() method Will always block.

Fix producer block

---

pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_partition.go
pulsar/consumer_partition_test.go
pulsar/consumer_regex.go
pulsar/impl_message.go
pulsar/impl_message_bench_test.go
pulsar/impl_message_test.go
pulsar/producer_test.go
pulsar/reader_impl.go

This change splits the `MessageID` implementation in two:
1. `messageID` - A 24 byte structure that contains message identification
information only; to be used during message production
2. `trackingMessageID` - A 72 byte structucture that shares the same
message identification information as `messageID`
and adds `ackTracker`, `acker`, and `receivedTime`
fields; to be used during message consumption
Micro benchmarks show that passing arguments by value that are less-than
four words of memory are optimized by the Go runtime.  Results from the
`pulsar/impl_message_bench_test.go` module are below.
```
name            time/op
ProducerCall    1.46ns ± 5%
ProducerCall-4  1.47ns ± 5%
ConsumerCall    7.62ns ± 1%
ConsumerCall-4  7.53ns ± 5%
```
The messageID structure in pulsar-client-go has the …

Different MessageID implementations for message Production and Consumption

---

pulsar/internal/connection.go

There's a condition in which a producer can remain deadlocked in the event of a connection failure. 
The sequence goes like: 
1. Producer (or multiple producers) have several outstanding request to write on a connection
2. The channel (used to pass buffers to write) has the buffer full and thus it's blocking
3. When the connection is closed the channel is not drained
4. The connection tries to notify the producers that it's time to reconnect
5. The producer go-routine is not able to process that notification, since it's blocked on the connection channel

Avoid producer deadlock on connection closing

---

oauth2/client_credentials_provider.go
pulsar/client_impl_test.go
pulsar/internal/auth/oauth2_test.go

---
*Motivation*
Fix the keyfile unmarshal error:
```
open test_credential.json: unsupported format
```
We should support any type of credential to authentication with pulsar.

Fix the keyfile unmarshal error

---

oauth2/client_credentials_provider.go
pulsar/internal/auth/oauth2_test.go

---
*Motivation*
Make the oauth2 read the private key can handle with  'file://' schema and 'data://' schema.

Support specified the oauth2 private key with prefix 'file://' and 'data://'

---

pulsar/client.go
pulsar/client_impl_test.go
pulsar/internal/auth/tls.go

This PR partially fixed ISSUE #345 by adding a method to create the auth provider from a tls cert supplier.
So users don't have to provide the path to the key/cert.

[Issue 345] Add a new method to create auth provider from tls cert supplier

---

pulsar/internal/connection.go

Fixes #239
As @wolfstudy pointed out here https://github.com/apache/pulsar-client-go/issues/239#issuecomment-625238240
There is a race on callbacks of `pendingReqs` when closing the connection while the run loop is still running, which will lead to calling a callback up to 2 times:
https://github.com/apache/pulsar-client-go/blob/e7f1673350f208b5063823282d14906d70d66904/pulsar/internal/connection.go#L669-L671
Introducing a `runLoopStoppedCh` to make sure that the run loop has already stopped when cleaning callbacks of `pendingReqs` in the `Close()`

Clean callbacks of connection after run loop stopped (#239)

---

pulsar/internal/connection.go
pulsar/reader.go
pulsar/reader_impl.go
pulsar/reader_test.go

Fixes #218 
Follow https://github.com/apache/pulsar-client-go/pull/222 and add the seek logic for reader 
- Add `seek by msgID` interface
- Add `seek by time` interface
- Add test case

Add seek logic for reader

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_regex.go
pulsar/consumer_regex_test.go
pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/impl_message.go
pulsar/internal/connection.go
pulsar/internal/topic_name.go
pulsar/producer_impl.go
pulsar/retry_router.go

Fixes #353 
Follow [pulsar#6449](https://github.com/apache/pulsar/pull/6449) to support retry letter topic in go client
- Add `retryRouter` for sending reconsume messages to retry letter topic
- Add `ReconsumeLater(msg Message, delay time.Duration)` to Consumer interface
- Add configureable retry letter topic name in `DLQPolicy`
```go
type DLQPolicy struct {
// ...
// Name of the topic where the retry messages will be sent.
RetryLetterTopic string
}
```
enable it explicitly while creating consumer, default unenable
```go
type ConsumerOptions struct {
// ...
// Auto retry send messages to default filled DLQPolicy topics
RetryEnable bool
}
```
- Add 2 `TestRLQ*`  test cases
[pulsar doc: retry-letter-topic](http://pulsar.apache.org/docs/en/concepts-messaging/#retry-letter-topic)

Support retry letter topic 

---

pulsar/internal/connection.go

There is a problem when writing large commands on the connections (other than commands with payloads which are already handled correctly). 
If the connection buffer doesn't have enough space, we're getting a panic for buffer overflow. 
This can for example happen when triggering a lot of `Nack()` requests.
```
INFO[19:10:38.794] Stats - Consume rate:  770.4 msg/s -    6.0 Mbps
INFO[19:10:42.128] Connection closed                             local_addr="192.168.1.3:61179" remote_addr="pulsar://192.168.1.3:6651"
panic: runtime error: slice bounds out of range [:31678] with capacity 4088
goroutine 68 [running]:
github.com/apache/pulsar-client-go/pulsar/internal.(*connection).writeCommand(0xc00022e360, 0xc00055b6c0)
/Users/mmerli/go/src/github.com/apache/pulsar-client-go/pulsar/internal/connec …
```

Fixed buffer resize when writing request on connection

---

pulsar/dlq_router.go

When acking the original message, after sending to the DLQ, there is a potential deadlock if the producer is sharing the same connection as the consumer.  The problem is we're trying to write on the connection event channel from the same go-routine that's handling the connection.
```
1 @ 0x4038f00 0x400774d 0x4007515 0x4606e8d 0x4613487 0x4603456 0x461cf4c 0x4619ab8 0x45f8bde 0x45f805e 0x45f737d 0x45fed61 0x4068bb1
#	0x4606e8c	github.com/apache/pulsar-client-go/pulsar.(*partitionConsumer).AckID+0x25c			/Users/mmerli/go/src/github.com/apache/pulsar-client-go/pulsar/consumer_partition.go:279
#	0x4613486	github.com/apache/pulsar-client-go/pulsar.trackingMessageID.Ack+0x106				/Users/mmerli/go/src/github.com/apache/pulsar-client-go/pulsar/impl_message.go:55
#	0x4603455 …
```

Fixed deadlock in DLQ ack processing

---

pulsar/internal/batch_builder.go
pulsar/producer_partition.go
pulsar/producer_test.go

Fixes #367 
Send delay message individually even batching is enabled.
1. flush batching messages immediately when a new delay message is received
2. reset deliverAtTime metadata of `BatchBuilder`
Ref #367 
- If yes, how is the feature documented? (docs)

[Issue 367][producer] Send delay message individually even batching is enabled

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/key_shared_policy.go
pulsar/key_shared_policy_test.go

Fixes #342
Add support for KeySharedPolicy with AutoSplit or Sticky mode for consumer, which is a useful for some user cases like scalable request-reply pattern.
add key shared policy options for consumer, and a helpful constructor for validating hash range list
*(or)*
*(or)*
*(example:)*
- Dependencies (does it add or upgrade a …

[Issue 342][consumer] add key shared policy support

---

pulsar/consumer_impl.go
pulsar/reader_impl.go

[Issue 350] fix panic on receiverQueueSize set to -1

---

go.mod
pulsar/consumer_partition.go
pulsar/consumer_regex_test.go
pulsar/internal/commands.go
pulsar/internal/connection.go
pulsar/internal/lookup_service_test.go
pulsar/internal/rpc_client.go
pulsar/producer_partition.go

Fixes #366
In current code of `pulsar/internal/connection.go` we have 2 channels, closeCh and incomingRequestsCh. when the connection closes, the current mis-use of these 2 channels may have a deadlock. 
PR #366 has detailed steps to reproduce and the root cause [analysis](https://github.com/apache/pulsar-client-go/pull/366#issuecomment-696759873) .
This PR tries to fix the deadlock.
- make the close logic independent, not in the same loop of normal events handling.
- when the connection closed, handle the existing requests in the channel and return an error to avoid deadlock.
passed the tests in #366 
current ut passed

Fix deadlock when connection closed

---

pulsar/internal/connection.go

There is a deadlock that can happen in Go client when the client has a write failure and tries to process that.
The issue is that Go mutexes are not re-entrant and we trigger a connection.Close() while already holding the connection mutex.
```
goroutine 1077 [semacquire, 83 minutes]:
sync.runtime_SemacquireMutex(0xc00c31fb04, 0xc110a12000, 0x1)
/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00c31fb00)
/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
/usr/local/go/src/sync/mutex.go:81
github.com/apache/pulsar-client-go/pulsar/internal.(*connection).Close(0xc00c31fb00)
/go/pkg/mod/cd.splunkdev.com/streamlio/pulsar-client-go@v0.1.1-streamlio-5/pulsar/internal/connection.go:718 +0x547
github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).Received …
```

Fix producer deadlock after write failure

---

pulsar/internal/commands.go
pulsar/internal/connection_reader.go

- issue 1
If broker updated `maxMessageSize`, client's `maxMessageSize` will be the same after handshaking.
However, client still use the default `maxMessageSize` while reading command from connection.
Lead to consumer can't receive message which payload exceed 5MB.
- issue 2
According to [PIP-36](https://github.com/apache/pulsar/wiki/PIP-36%3A-Max-Message-Size), default *Size should be:
```
maxMessageSize = 5MB
framePaddingSize = 10KB
maxFrameSize = maxMessageSize + framePaddingSize
```
But they two are confused currently：
```
maxFrameSize = 5MB
framePaddingSize = 10KB
maxMessageSize = maxFrameSize - framePaddingSize
```
- Use the aligned `maxMessageSize` instead of the default value.
- Correct `maxMessageSize` default value.

Fix maxMessageSize not effective even if aligned with broker

---

go.mod
go.sum
pulsar/internal/compression/zstd_cgo.go

Fixes #379 
Using `DataDog` instead of `datadog` is not canonical way
Changed dependency nam
- Dependencies (does it add or upgrade a dependency): (yes)
- If yes, how is the feature documented? (not applicable)
- If a feature is not applicable for documentation, explain why? Just library name change

[Issue #379][pulsar-client-go] Replaced github.com/DataDog/zstd with github.com/datadog/zstd

---

pulsar/consumer_impl.go
pulsar/consumer_test.go
pulsar/helper.go

Retry policy not effective with non-FQDN topic.
- reproduction
```go
client, _ := pulsar.NewClient(pulsar.ClientOptions{URL: "pulsar://localhost:6650"})
consumer, _ := client.Subscribe(pulsar.ConsumerOptions{
Topic:            "topic-01",
SubscriptionName: "my-sub",
RetryEnable:      true,
DLQ:              &pulsar.DLQPolicy{MaxDeliveries: 2},
})
msg, _ := consumer.Receive(context.Background())
consumer.ReconsumeLater(msg, 5*time.Second)
```
- logs
```
RN[0000] consumer of topic [persistent://public/default/topic-01] not exist unexpectedly  topic="[topic-01 persistent://public/default/my-sub-RETRY]"
```
For MultiTopicConsumer `consumers` map filed:
- key: user provided topic, maybe non-FQDN.
- value: consumer instance.
`ReconsumeLater` using msg's FQDN topic as key to find `consumer` in …

Fix retry policy not effective with non-FQDN topics

---

.github/workflows/bot.yml

Currently, when run the bot ci, the error as follows:
```
Run zymap/bot@v1.0.0
with:
repo_owner: apache
repo_name: pulsar-client-go
rerun_cmd: rerun failure checks
comment: rerun failure checks
env:
GITHUB_TOKEN: ***
Error: HttpError: No commit found for SHA: xiaolong/test-bot
```
Fix bot action ci yaml file

Fix bot action ci yaml file

---

pulsar/producer_partition.go

The current publish latency metric measures the time when send is called until the message is acked. The metric can be skewed if batching is enabled. 
For example, if we call send the client will hold that message until x number of messages are collected or an interval has passed. This new metric measures the time when we send the data to the connection until we get an ack from the broker. This cuts out any batch skewing and provides a more accurate latency of what the client sees at the connection level.

Add metric for internal publish latency

---

integration-tests/standalone.conf
pulsar/producer.go
pulsar/producer_impl.go
pulsar/producer_partition.go
pulsar/producer_test.go

Support `SendTimeout` and `DisableBlockIfQueueFull ` for producer.
- Add 2 configurations into `ProducerOptions`
- Check and fail timeout messages before flushing batch.
- Check `DisableBlockIfQueueFull` before acquiring publish semaphore while sending messages.
- Add `TestSendTimeout` to verify sendTimeout effective whille backlog exceeded on topic.
client-go and client-java have different ways to disable `sendTimeout`
- client-java: set `sendTimeout` to 0 explicitly, to override default 30s configuration.
- client-go: set `sendTimeout` to -1, to bypass unset detection.
[configure-producer](https://pulsar.apache.org/docs/en/client-libraries-java/#configure-producer)

Support sendTimeout

---

go.mod
go.sum
oauth2/go.mod
oauth2/go.sum

Fixes #380 
github.com/99designs/keyring v1.1.5 -> v1.1.6
- Dependencies (does it add or upgrade a dependency): (yes)
- The schema: ( no)
- The default values of configurations: ( no)

[Issue 380] Update go-keyring to v1.1.6 to remove warnings on MacOS Catalina+

---

pulsar/producer_partition.go

Add an label to the `pulsar_client_producer_errors` metric to distinguish the error type.

Add error label to publish errors metric

---

pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/internal/connection.go
pulsar/internal/lookup_service.go
pulsar/internal/metrics.go
pulsar/internal/rpc_client.go
pulsar/metrics.go
pulsar/producer_impl.go
pulsar/producer_partition.go

Add const client label to metrics so when metrics are added to other clients we can filter the metrics by client language.

Add const client label to metrics

---

pulsar/default_router.go
pulsar/default_router_bench_test.go
pulsar/default_router_test.go

Previously, we read the system clock twice for each event unless we
switched partitions early due to reaching `maxBatchingMessages` or
`maxBatchingSize`.
Now, we read the clock once every `maxBatchingMessages / 100` messages.
This improves performance (especially for larger batch sizes) as the
router function is called for every message produced.
A bench test of the default router was added; results are below:
```
name             old time/op    new time/op    delta
DefaultRouter       106ns ± 0%      16ns ± 1%  -84.94%  (p=0.016 n=4+5)
DefaultRouter-4     106ns ± 0%      16ns ± 0%     ~     (p=0.079 n=4+5)
```
The default_router reads the system clock twice for every message routed in the production code path.  When testing at scale …

Read the clock fewer times during message routing

---

pulsar/consumer_impl.go

The goroutine for auto discovery partitions has never been closed even when consumer is Close()
https://github.com/apache/pulsar-client-go/blob/v0.3.0/pulsar/consumer_impl.go#L236
Currently consumer Close() will stop() the ticker, however, Stop() does not close the ticker's channel. The behaviour is described at https://golang.org/pkg/time/#Ticker.Stop
This bug can leave a large number of dangling goroutines, that results in high CPU consumption.
The fix is to introduce a signal channel to send a signal to terminate the partition auto discovery goroutine upon consumer Close().
- The …

close dangling autoDiscovery goroutine in consumer

---

pulsar/client.go
pulsar/client_impl.go

The default TCP connection timeout of 30 seconds is too high. The connection timeout should be low enough such that we can recover a producer session with brokers before the operation or the publish timeouts expired (default is 30sec for both).
5 seconds is a better default value for this scope.

Reduce the default TCP connection timeout from 30 to 5 seconds

---

pulsar/internal/rpc_client.go

There is a problem with the re-connection logic introduced in #157. 
The change added a logic to keep retrying to establish a TCP connection with broker up to the "operation timeout" (default 30seconds). 
There are few issues with it: 
1. (minor) It's not checking that the error is indeed a TCP error (eg: it would retry on auth failures too)
2. (major) After a TCP connection failure, reconnecting to the same broker is always the wrong approach, because the most likely outcome is that the next attempt will also fail and, worse, the IP might just be unresponsive and we will then have to wait for the full connection timeout time. 
The correct solution after a connection failure is to re-do the topic lookup, since the topic will be moving to a different broker and we need to reconnect to the …

Fixed logic to attempt reconnections to same broker

---

pulsar/consumer_partition.go

https://github.com/apache/pulsar-client-go/issues/389#issuecomment-741560624
When a consumer whose receive queue is not empty reconnects to a broker, unacked messages don't be redelivered to a client application and these are removed from backlog.
This is because StartMessageID is updated and the consumer implicitly acks redelivered unacked messages.
https://github.com/apache/pulsar-client-go/blob/v0.3.0/pulsar/consumer_partition.go#L972-L976
https://github.com/apache/pulsar-client-go/blob/v0.3.0/pulsar/consumer_partition.go#L507-L510
* If startMessageID is undefined, it will not be updated in order to prevent  unacked messages from being discarded by following logic.
.https://github.com/apache/pulsar-client-go/blob/v0.3.0/pulsar/consumer_partition.go#L507-L510

Fix discard unacked messages

---

pulsar/internal/metrics.go
pulsar/internal/rpc_client.go

After some tooling change, the variable name `RpcRequestCount` is now triggering an error in the checkstyle job. Changing to `RPCRequestCount`

Renamed Metrics.RpcRequestCount to RPCRequestCount to conform to style check

---

pulsar/consumer_partition.go
pulsar/negative_acks_tracker.go
pulsar/negative_acks_tracker_test.go

The negative ack tracker, nackTracker, created by consumer_partition has leaks in many places. These goroutines left running even after the consumers are Close().
1. Close the nackTracker in each failure path on partition consumer creation.
2. Only send close sig once to nackTracker goroutine.
3. Close the nackTracker in consumer notready state too. (this may not need at the current implementation since we use sync.Once to close the tracker thread. It prevents leaks in the future).
- If yes, how is the feature documented? 
- …

fix leaked nack tracker goroutine

---

go.mod
go.sum
pulsar/consumer_impl.go
pulsar/consumer_test.go
pulsar/default_router.go
pulsar/dlq_router.go
pulsar/impl_message.go
pulsar/message.go
pulsar/producer_partition.go

Fixes #401
According to apache/pulsar#4079, orderingKey was introduced to let user set message order manually, currently pulsar-client-go do not have related apis exposed to user. We should add orderingKey related apis to pulsar-client-go.
- add OrderingKey to ProducerMessage
- add OrderingKey() to Message interface
- sync OrderingKey to SingleMessageMetadata
- tests

[Issue #401] Add orderingKey apis

---

pulsar/consumer_multitopic.go
pulsar/consumer_test.go

Retry policy not effective with partitioned topic.
- reproduction
topic-01 have 2 partitions:
```go
client, _ := pulsar.NewClient(pulsar.ClientOptions{URL: "pulsar://localhost:6650"})
consumer, _ := client.Subscribe(pulsar.ConsumerOptions{
Topic:            "topic-01",
SubscriptionName: "my-sub",
RetryEnable:      true,
DLQ:              &pulsar.DLQPolicy{MaxDeliveries: 2},
})
msg, _ := consumer.Receive(context.Background())
consumer.ReconsumeLater(msg, 5*time.Second)
```
- logs
```
WARN[0000] consumer of topic [persistent://public/default/topic-01-partition-0] not exist unexpectedly  topic=" [persistent://public/default/topic-01 persistent://platform/psr/my-sub-RETRY]"
```
For MultiTopicConsumer `consumers` map filed:
- key: FQDN topics, without partition number suffix.
- value: consumer …

Fix retry policy not effective with partitioned topic

---

pulsar/consumer_impl.go

If user provided retry topic is same with consumer topic
- Currently underlayer will create 2 same topic consumers to implement retry, but it's unnecessary, client-java only create 1 consumer to do this, see [ConsumerBuilderImpl.java#L139](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java#L139)
- When user invoke `consumer.Close()`, only the 2th consumer will be closed directly, consumer 1st is still active, there are potential memory leak. 
```go
func main() {
client, _ := pulsar.NewClient(pulsar.ClientOptions{URL: "pulsar://localhost:6650"})
defer client.Close()
topic := "topic-01"
consumer, _ := client.Subscribe(pulsar.ConsumerOptions{
Topic:            topic,
SubscriptionName: "my-sub",
Type: …
```

Deduplicate user provided topics before using them

---

perf/perf-consumer.go
perf/perf-producer.go
perf/pulsar-perf-go.go

Add token/JWT and trusted certificate support in Pulsar perf go client. So that it can be used in production environment.
Implement pulsar-perf-go command line arguments for token-file and trusted-cert-file. These two arguments are optional. There is no change to the default non-TLS and no auth configuration.
This is a change to Pulsar perf go client. It should pass build and existing test cases.
- If a feature is not applicable for …

support jwt and trusted cert for pulsar perf client

---

pulsar/impl_message.go
pulsar/reader_impl.go
pulsar/reader_test.go

Master Issue: #438  https://github.com/apache/pulsar-client-go/issues/438
Fix issue #438 
Reader.HasNext() should return true on empty topic, leading to hangs.
It checks the last message on the broker with a valid Entry Id (non-negative).
Add a new test case for read.erHasNext() when the topic is empty. The test case is part of CI now.

[issue 438] reader.HasNext() returns true on empty topic

---

pulsar/log/wrapper_logrus.go

logrusWrapper formatter shrank  `[]interface{}` args into an `interface{}`, cause logrus formatter missing arguments.
Format case
```
ls.log.Debugf("Successfully looked up topic{%s} on broker. %s / %s - Use proxy: %t",
topic, lr.GetBrokerServiceUrl(), lr.GetBrokerServiceUrlTls(), lr.GetProxyThroughServiceUrl())
```
Logging looks like:
```
DEBU[0000] Successfully looked up topic{[persistent://public/default/topic-1 pulsar://localhost:6651  %!s(bool=false)]} on broker. %!s(MISSING) / %!s(MISSING) - Use proxy: %!t(MISSING)  serviceURL="pulsar://localhost:6650"
```
Expand `[]interface{}` before invoke logrus logger, pass them to logrus intact.

Fix logrusWrapper shrink interfaces slice into an interface

---

pulsar/internal/connection.go
pulsar/internal/lookup_service.go

Clusters deployed over k8s, during broker pod restarting / terminating, it's service DNS `.cluster.local` will be removed, cause proxy can't resolve the restarting owner broker DNS name.
For now, client only logging `ServiceNotReady` error but without details which help troubleshoot.
Logging LookupResponse failure detail message, like this:

Logging what really caused lookup failure

---

pulsar/consumer_partition.go
pulsar/consumer_test.go

Message queues should be cleared after seek requests (`Seek` and `SeekByTime`). If this is not performed messages that stay in message queues will be consumed before the sough message.
Cleaning `queueCh` and `messageCh` after successful seek request in partition_consumer.go.
This change is already covered by existing tests, such as `TestConsumerSeekByTime` and `TestConsumerSeek`.
- Extended `TestConsumerSeekByTime` and `TestConsumerSeek` test for consuming correctly sought message even if some messages stay in message queues.
- Does this pull request introduce a …

Clearing message queues after seek requests

---

oauth2/client_credentials_flow_test.go

[KeyFileTypeServiceAccount](https://github.com/apache/pulsar-client-go/blob/v0.3.0/oauth2/client_credentials_flow_test.go#L45) is not defiend in the latest version of oauth2/client_credentials_provider.go file,so there will be a compile error in oauth2/client_credentials_flow_test.go
change KeyFileTypeServiceAccount to "resource" in test file.
- The public API:  no
- The schema:  no 
- Does this pull request introduce a new feature?  no

fix: KeyFileTypeServiceAccount not found compile error

---

pulsar/producer_partition.go

Fixes #458
For current producer, send timeout checking triggered by interval batch flush
If connection closed, the producer eventloop will blocked to reconnect to broker, lead to batch flush and send timeout checking take no effective, java-client timer did effective in this situation
Asynchronized send timeout by running in independent goroutine until producer closed, and without a pending queue lock
Without pending queue lock, the send timeout checking  gets more complicated, I don't know if it's worth it for performance.

asynchronized send timeout checking without pending queue lock

---

pulsar/consumer_partition.go

For the present consumer, `Close()` and `Unsubscribe()` handled by the same eventloop goroutine.
The eventloop exited after `Close()`, then unsubscribe event wouldn't be selected and handled anymore, lead to block.
example:
```go
func main() {
client, err := pulsar.NewClient(pulsar.ClientOptions{URL: "pulsar://localhost:6650"})
if err != nil {
log.Fatal(err)
}
defer client.Close()
consumer, err := client.Subscribe(pulsar.ConsumerOptions{
Topic:            "topic-1",
SubscriptionName: "my-sub",
})
if err != nil {
log.Fatal(err)
}
defer consumer.Unsubscribe() // unintentional
defer consumer.Close()
}
```
`Unsubscribe()` blocked:
Check consumer state before send unsubscribe event, if consumer is closing or has closed, just logging it

Fix unsubscribe blocked when consumer is closing or has closed

---

oauth2/store/keyring.go

**Motivation**
When compiling the code across different platform, sometimes
will encounter the nil pointer when getting the label from the
`authIterm`.
error logs:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13105e1]
goroutine 1 [running]:
github.com/apache/pulsar-client-go/oauth2/store.(*KeyringStore).WhoAmI(0xc0001ae660, 0x7ffeefbff459, 0x1b, 0x0, 0x0, 0x0, 0x0)
/Users/zhangyong/github.com/apache/pulsar-client-go/oauth2/store/keyring.go:127 +0x221
github.com/streamnative/pulsarctl/pkg/oauth2.doActivate(0xc0003446e0, 0x7ffeefbff3ae, 0x3a, 0x7ffeefbff459, 0x1b, 0x7ffeefbff421, 0x2c, 0xc000357cf8, 0x157a745)
/Users/zhangyong/github.com/streamnative/pulsarctl/pkg/oauth2/active.go:93 +0x21a …
```

Fix unexpected nil pointer when reading item from keyring

---

go.mod
go.sum
pulsar/internal/compression/zstd_cgo.go

Fixes #440
Data Dog has added go.mod file to their lib, and now library is official named github.com/**DataDog**/zstd
So we must use it to be able to install client correctly
go mod change
- If yes, how is the feature documented? (not applicable)

[Issue 440] Reverted datadog to DataDog

---

go.sum
oauth2/auth.go
oauth2/go.mod
oauth2/go.sum

jwt-go before 4.0.0-preview1 allows attackers to bypass intended access restrictions in situations with []string{} for m["aud"] (which is allowed by the specification). Because the type assertion fails, "" is the value of aud. This is a security problem if the JWT token is presented to a service that lacks its own audience check.

Update jwt-go version to v4

---

pulsar/producer_partition.go

Fixes #475
Fix wrong batch flush method bug.
Check if batchBuilder is multi batches before flush.
- Dependencies (does it add or upgrade a dependency):  no
- The public API:  no
- The schema:  no
- The default values of configurations:  no
- If yes, how is the feature documented? GoDocs

fix: batch flush method

---

pulsar/internal/connection.go
pulsar/internal/connection_reader.go
pulsar/producer_partition.go

This PR is to improve error log for `frame size too big` on the consumer. We have seen a number of frame size too big error and I would like to trace what the exact maxMessageSize is set to that is not default. Debug log was not able to be enabled on the production system.
Log improvement mostly
- If yes, how is the feature documented? no

Improve error log for frame size too big and maxMessageSize

---

pulsar/batcher_builder.go
pulsar/client_impl.go
pulsar/client_impl_test.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_regex.go
pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/error.go
pulsar/producer_impl.go
pulsar/producer_partition.go
pulsar/producer_test.go
pulsar/reader_impl.go
pulsar/retry_router.go
pulsar/schema.go

Fixes #444
For better error assertion in client side.
Fix newError and use newError to build return error in most case.
- Dependencies (does it add or upgrade a dependency):  no
- The public API:  no
- The schema:  no
- The default values of configurations:  no
- If yes, how is the feature documented? GoDocs

[Issue 444][fix] Use newError to build return error

---

pulsar/client_impl.go

[Issue 493] close cnxPool when closing a Client

---

pulsar/consumer_impl.go
pulsar/producer_impl.go

Master issue: #462
In some cases consumer `Close` method might be called in nearly the same moment with background partiotion discovery routine tick. When `Close` acquires mutex first, it will release all underlying consumers, but that not guarantees backgound routine's not wait for the same mutex in `internalTopicSubscribeToPartitions`, so when `Close` completes, mutex gets acquired by not-finished-yet goroutine leading to new partition consumers gets created without any chance to close them.
The same logic is valid for producer partition discovery goroutine which is closed the same manner.
This PR modifies background discrovery goroutine the way it will be closed before acquiring mutex in `Close` method.
Described above.
This change is a trivial rework / code cleanup without any test …

Fix race condition/goroutine leak in partition discovery goroutine

---

.github/workflows/bot.yml

Fixes #479
ci bot for pulsar-client-go is not working due to below error:
`zymap/bot@v1.0.1 is not allowed to be used in apache/pulsar-client-go. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace or match the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, apache/*, burrunan/gradle-cache-action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, dawidd6/action-download-artifact@*, gradle/wrapper-validation-action@*, julia-actions/julia-runtest@*, julia-actions/setup-julia@*, msys2/setup-msys2@*, peaceiris/actions-gh-pages@*, peaceiris/actions-hugo@*, peter-evans/create-pull-request@*, potiuk/cancel-workflow-runs@*, …

[fix #479] use pulsar-test-infra/pulsarbot as github action bot

---

pulsar/consumer_test.go
pulsar/producer.go
pulsar/producer_impl.go

`partitionsAutoDiscoveryInterval` is currently hardcoded to 1 minute: https://github.com/apache/pulsar-client-go/blob/6ab17dcca28db389ab91a4a2ea6e5ae990d613da/pulsar/producer_impl.go#L60
I could think of two reasons for making it a configurable value:
* A faster or slower partitions discovery is desired. A faster one is more likely when users would like a partition increment to be effective more quickly.
* Allow a test to be able to set it to a much smaller time duration so that the test could exercise the logic within a reasonable short time
Added `PartitionsAutoDiscoveryInterval` into `ProducerOptions` with a default value of 1 minute.
- Dependencies (does it add …

Make PartitionsAutoDiscoveryInterval configurable

---

pulsar/consumer_partition.go
pulsar/impl_message.go
pulsar/message.go

Currently, using reader.latest fails because we discard
all messages less than the startPositionID, this causes an issue with
the reader as we filter all messages as all messages are less than
latest message id

[bug] Fix reader latest position

---

pulsar/impl_message.go
pulsar/impl_message_test.go
pulsar/message.go
pulsar/reader_test.go

In some cases, consumers need to obtain the ledgerId, entryId, batchId, partitionidx of the messageId.
This expose LedgerId EntryId BatchId PartitionIdx func for MessageId interface.

add LedgerId,EntryId,BatchIdx,PartitionIdx func for MessageId interface

---

pulsar/internal/rpc_client.go

Fixes #491 
see #491
add timeout guarantee to RequestOnCnx
- **The public API: (yes)**

[Issue 491][rpc_client]fix: timeout guarantee for RequestOnCnx

---

pulsar/internal/lookup_service.go

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc7bd24]
goroutine 129 [running]:
github.com/apache/pulsar-client-go/pulsar/internal.(*lookupService).GetPartitionedTopicMetadata(0xc00017ac80, 0xc00040c1e0, 0x2c, 0x0, 0x0, 0x5)
/go/pkg/mod/github.com/apache/pulsar-client-go@v0.4.1-0.20210504220432-203f2f60325b/pulsar/internal/lookup_service.go:193 +0x244
github.com/apache/pulsar-client-go/pulsar.(*client).TopicPartitions(0xc00010f860, 0xc00040c1e0, 0x2c, 0xc0005e6f80, 0x2, 0x2, 0xc0005e6f7c, 0x2)
/go/pkg/mod/github.com/apache/pulsar-client-go@v0.4.1-0.20210504220432-203f2f60325b/pulsar/client_impl.go:184 +0xa2
github.com/apache/pulsar-client-go/pulsar.(*consumer).internalTopicSubscribeToPartitions(0xc …
```

fix nil pointer error with `GetPartitionedTopicMetadata` 

---

pulsar/internal/connection.go

Avoid holding the connection lock when producer and consumer request callbacks are called.

Release locks before calling producer consumer response callbacks.

---

pulsar/producer_partition.go

Fixes #550
When resending `pendingItems`, reset the `pendingItem`'s `sentAt` and put the `pendingItem` to the back of `pendingItems` queue.

#550 fix race condition when resend pendingItems 

---

pulsar/consumer_partition.go

The partitionConsumer maintains a few internal go-routines, two of which
access the underlying internal.Connection.  The main runEvenstLoop()
go-routine reads the connection field while a separate go-routine is used
to detect connnection loss, initiate reconnection, and sets the connection.
Previously, access to the conn field was not synchronized.
Now, the conn field is read and written atomically; avoiding race
conditions.
While attempting to submit a separate PR (https://github.com/apache/pulsar-client-go/pull/534) I found that the `pulsar/reader_test` consistently failed with the following data race.  This change in this PR is an attempt to fix it. 
```
2021-06-07T22:33:43.1825587Z ==================
2021-06-07T22:33:43.1825992Z …
```

Fix data race while accessing connection in partitionConsumer

---

pulsar/client.go

Go's comment spec requires that the comment must start with the name it describes. Fix some comments to reduce IDE warnings
* Make the comments start with the name of the element it describes

Updating comments to conform to golang comment specification

---

pulsar/internal/semaphore.go
pulsar/internal/semaphore_test.go
pulsar/producer_partition.go
pulsar/producer_test.go

Previously, the Producer ignored the context passed to Send() and
SendAsync().
Now, the Producer respects the context in the case where the
ProducerOptions.MaxPendingMessages limit is breached.  In this case, the
producer will block until a permit for sending the message is available or
until the context expires, whichever comes first.
Failures to send messages due to context expiration are communicated to
callers via the existing TimeoutError error code.
When the Producer is applying backpressure to the caller it will block attempting to acquire a send permit.
Before this change change, the producer would block indefinitely as a send permit must be acquired before the send timeout can be checked by the internal `runEventsLoop` …

Producer respects Context passed to Send() and SendAsync() when appying backpressure

---

pulsar/internal/connection.go

In `internalSendRequest`, We will add the request to be sent to the `pendingReqs` map, even when the current connection status is `connectionClosed`, we will append the request, which will cause the current request's callback to be called twice
First:
```
func (c *connection) internalSendRequest(req *request) {
c.pendingLock.Lock()
if req.id != nil {
c.pendingReqs[*req.id] = req
}
c.pendingLock.Unlock()
if c.getState() == connectionClosed {
c.log.Warnf("internalSendRequest failed for connectionClosed")
// In Here, call req.callback *************
if req.callback != nil {
req.callback(req.cmd, ErrConnectionClosed)
}
} else {
c.writeCommand(req.cmd)
}
}
```
Twice:
```
func (c *connection) run() {
// All reads come from the reader goroutine …
```

Fix channel data race

---

pulsar/internal/backoff.go
pulsar/internal/backoff_test.go

Fixes #556 
When reconnecting to a broker, an exponential backoff strategy is used. However, there is no randomness involved which means in case of a general outage impacting several clients, they will try to reconnect at the same time.
The modification consists of adding a jitter that adds 20% of delay after the delay is doubled on each retry.
This change added unit tests to verify the expected behavior.
- The default values of configurations: no)
- …

[Issue 556]Add jitter to exponential backoff (#556)

---

pulsar/internal/connection.go
pulsar/internal/connection_reader.go
pulsar/internal/rpc_client.go

Simplify the connection close logic into one function. I thinks this makes the code easier to reason about and maintain.

Simplify connection close logic

---

pulsar/internal/connection.go
pulsar/internal/connection_pool.go

- Use mutex instead of sync map in connection pool
- Create tickers in run function for the connection instead
of when the connection is created

Fix possible race condition in connection pool

---

pulsar/client_impl.go

In Java SDK, the default connection timeout is **10** sec
```
private int connectionTimeoutMs = 10000;
```
The problem here is that when the load of the broker is high, there is no way to complete the processing and creation of the connection within 5s, which will cause the client to constantly create new connections and try to establish a connection with the broker, and the broker Continuously disconnecting from the client, forming a vicious circle
Replace 5 sec of connection timeout with `10` sec

Fix default connection timeout

---

pulsar/internal/commands.go
pulsar/internal/connection.go
pulsar/internal/pulsartracing/producer_interceptor.go
pulsar/internal/pulsartracing/producer_interceptor_test.go

Fixes #564 
Add command of SendError logic for connection

Add send error logic for connection

---

pulsar/error.go
pulsar/producer_partition.go
pulsar/producer_test.go

Fix issue: #495 
Add producer state check before send msg.

[issue 495] fix: producer.Send() blocks forever for closed producer

---

pulsar/producer_partition.go
pulsar/producer_test.go

Master Issue: https://github.com/apache/pulsar/issues/5606
Handle create producer timeout on pulsar-client-go. To prevent duplicate producer when broker is not available.
- add `epoch` to `partitionProducer`
- add `userProvidedProducerName` to `partitionProducer`
- add tests

add epoch to handle create producer timeout

---

pulsar/consumer_impl.go
pulsar/producer_impl.go

```
panic: runtime error: index out of range [1] with length 1
goroutine 166288 [running]:
github.com/apache/pulsar-client-go/pulsar.(*producer).internalCreatePartitionsProducers(0xc0070aa6e0, 0x0, 0x0)
/Users/lzhuang/scfproj/scf_trigger_v2/vendor/github.com/apache/pulsar-client-go/pulsar/producer_impl.go:194 +0x785
github.com/apache/pulsar-client-go/pulsar.(*producer).runBackgroundPartitionDiscovery.func1(0xc004167cd0, 0xc00559f5c0, 0xc006af6dc0, 0xc0070aa6e0)
/Users/lzhuang/scfproj/scf_trigger_v2/vendor/github.com/apache/pulsar-client-go/pulsar/producer_impl.go:152 +0xce
created by github.com/apache/pulsar-client-go/pulsar.(*producer).runBackgroundPartitionDiscovery
/Users/lzhuang/scfproj/scf_trigger_v2/vendor/github.com/apache/pulsar- …
```

Fix producer panic by oldProducers

---

pulsar/consumer_regex_test.go
pulsar/test_helper.go

in `consumer_regex_test.go`, sometimes consumers take more than 2 seconds (waiting time) subscribing, and assertions fail.
instead of waiting and asserting just once, repeat it a specified number of times so that consumers have enough time to subscribe.

Retry assertion several times in consumer regex test

---

pulsar/client_impl_test.go

fix `TestNamespaceTopicsNamespaceDoesNotExit` error after pulsar release 2.8.1
ref: https://github.com/apache/pulsar/pull/11172

fix TestNamespaceTopicsNamespaceDoesNotExit

---

pulsar/consumer_partition.go
pulsar/producer_partition.go

Fixes #623
As #623 said, when the topic is deleted forced, we don't should trying to reconnect, instead of giving up reconnection.
- Fix prodcuer reconnetion logic
- Fix consumer reconnection logic

Fix reconnection logic when topic is deleted

---

.github/workflows/go.yml
.github/workflows/project.yml
Dockerfile

CI is currently broken because the `go mod download` is failing in the docker images for Go 1.11 and 1.12.
```
go: gopkg.in/check.v1@v1.0.0-20190902080502-41f04d3bba15: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /pkg/mod/cache/vcs/7e5fa1eab4705eb80c9746632736cea906708d060702d529df6241d1c8c2c9f9: exit status 128:
fatal: unable to access 'https://gopkg.in/check.v1/': server certificate verification failed. CAfile: none CRLfile: none
go: gopkg.in/check.v1@v1.0.0-20180628173108-788fd7840127: unknown revision 788fd7840127
```
The issue is related with Let's Encrypt root CA getting changed. Apparently the `go` tool is not even using the updated certs from the image.
Removing 1.11 and 1.12 from CI and adding newer versions 1.15, 1.16 and 1.17.

Go 1.11 & 1.12 Docker images are not working anymore

---

oauth2/auth.go
oauth2/authorization_tokenretriever.go
oauth2/client_credentials_flow.go
oauth2/client_credentials_flow_test.go
oauth2/device_code_flow.go
oauth2/device_code_provider.go
oauth2/go.mod
oauth2/go.sum
pulsar/internal/auth/oauth2.go

This PR improves support for Azure AD and other OAuth 2.0 authorization servers.  
1. Support the passing of scope parameters to various OAuth 2.0 API calls.
2. Use well-known claims for user name when possible.  The helper function looks for `name` and `sub` claims to provide a  user name hint to the application.  It is for informational purposes only.
3. Support responses with `Content-Type` headers that contain extra parameters.  Use the golang mime parser for this.
This change is partly covered by tests; more tests will be contributed in a follow-up.
no

Improve support for Azure AD OAuth 2.0

---

pulsar/producer_partition.go

Fixes #650
Modify handle CommandSendReceipt  command way same with java client ,
and when  response's sequenceID is less than max sequenceID in pendingQueue will not close cnx.
Master Issue: #650

fix issue 650,different handle sequence value

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_partition.go
pulsar/consumer_regex.go
pulsar/impl_message.go
pulsar/negative_acks_tracker.go
pulsar/negative_acks_tracker_test.go
pulsar/negative_backoff_policy.go
pulsar/negative_backoff_policy_test.go

Master Issue: #658
Support nack backoff policy
- Add `EnableDefaultNackBackoffPolicy` and `NackBackoffPolicy` options in ConsumerOptions.
- Modify the original implementation of the `Nack(Message)` interface
- Add test case
- Add defaultNackBackoffPolicy

Support nack backoff policy for SDK

---

pulsar/internal/connection.go

Fixes #662
As described in #662, there appears to be a potential race condition in connection.go function _waitUntilReady()_: the `cond.Broadcast()` can occur before the `cond.Wait()`.
[EDIT:] To be explicit, this is the issue:
[goroutine A] calls c.getState() and sees that it is not set to connectionReady
[goroutine B] changes the state to connectionReady
[goroutine B] sends a cond.Broadcast(), which goes nowhere because no goroutine is waiting.
[goroutine A] calls cond.Wait(), which never completes
Function _waitUntilReady()_ was previously holding the global `c.Lock()` on the connection. From my reading of the code, this mutex is intended to protect the `cnx` variable. I think that the use of `c.Lock()` in _waitUntilReady()_ was probably just a typo.
Instead, I think the author …

[Issue 662] Fix race in connection.go waitUntilReady()

---

pulsar/internal/compression/zstd.go
pulsar/internal/compression/zstd_cgo.go
pulsar/internal/http_client_go_1.11.go
pulsar/internal/http_client_go_1.12.go

According to the [Bug-resistant build constraints proposal](https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md), //+build will be replaced by //go:build. A transition period from //+build to //go:build syntax will last from Go version 1.16 through version 1.18.

Add new bug-resistant build constraints

---

pulsar/internal/auth/provider.go

Added parsing error check in NewProvider; minor cleanups.

Handle the parameters parsing error in NewProvider

---

docs/release-process.md

As I mentioned in [this email](http://mail-archives.apache.org/mod_mbox/pulsar-dev/202111.mbox/%3C4416E302-58BF-4ED4-98B4-8FC91B89B9BC%40yahoo-corp.jp%3E), it is better to use dev KEYS instead of release KEYS in a vote email because release KEYS only include keys of PMC.
Ref. https://github.com/apache/pulsar/wiki/Create-GPG-keys-to-sign-release-artifacts
I also modify URL of source file so that we can easily find asc and shasum.

Update email template of release docs

---

pulsar/internal/batch_builder.go

Currently, when we disable batch in Producer, in `handleSend()` of `serverCnx.java`, the `msgMetadata.hasNumMessagesInBatch()` is **true** and `msgMetadata.getNumMessagesInBatch()` is **1**.
At this point, if we get the Properties object we set on the producer side on the broker side, the display is empty.
Go SDK set Properties:
```
// disable batch
producer, err := client.CreateProducer(pulsar.ProducerOptions{
Topic: "topic-1",
DisableBatching: true,
})
// set properties for every message
producer.Send(ctx, &pulsar.ProducerMessage{
Payload: []byte(fmt.Sprintf("hello-%d", i)),
Properties: map[string]string{
"key-1": "value-1",
},
});
```
Broker get message properties from entry metadata is null:
```
ByteBuf metadataAndPayload = …
```

Add properties filed for batch container

---

pulsar/internal/batch_builder.go
pulsar/internal/key_based_batch_builder.go
pulsar/producer_test.go

Fixes issue https://github.com/apache/pulsar-client-go/issues/513.
This issue was previously partially addressed by @zzzming in PR https://github.com/apache/pulsar-client-go/pull/528.
Following PR https://github.com/apache/pulsar-client-go/pull/528, the logic for the `hasSpace()` function, which is used to determine whether a batch container has enough space for a new message, reads:
```
func (bc *keyBasedBatchContainer) hasSpace(payload []byte) bool {
msgSize := uint32(len(payload))
return bc.numMessages+1 < bc.maxMessages || (bc.buffer.ReadableBytes()+msgSize) < uint32(bc.maxBatchSize)
}
```
Currently, then, the batch container will be considered to have space (be non-full) until **both** the max-messages and the max-size limits are hit.
I think that is incorrect. Nearby in the code, …

[Issue 513] Correct apparent logic error in batchContainer's hasSpace() method

---

go.mod
go.sum

This updates zstd to 1.5.0 which supports some major performance
improvements.  For details see:
https://github.com/facebook/zstd/releases/tag/v1.5.0
Results from `pulsar/internal/compression/compression_bench_test.go` show the speedup.
```
name                                          old time/op    new time/op     delta
CompressionParallel/zstd-cgo-level-fastest      1.30ms ±13%     0.95ms ± 0%  -27.09%  (p=0.000 n=9+8)
CompressionParallel/zstd-cgo-level-fastest-2     672µs ± 2%      517µs ± 4%  -23.12%  (p=0.000 n=10+10)
CompressionParallel/zstd-cgo-level-fastest-4     421µs ± 6%      323µs ± 3%  -23.10%  (p=0.000 n=10+10)
CompressionParallel/zstd-cgo-level-fastest-8     241µs ± 1%      187µs ± 1%  -22.25%  (p=0.000 n=8+8)
CompressionParallel/zstd-cgo-level-default      1.34ms ±15% …
```

Upgrade DataDog/zstd to v1.5.0

---

Dockerfile
docker-ci.sh

Set the default go version to 1.13 in the CI related files as per the minimum version requirements.

Set default go version to 1.13 in CI related files

---

pulsar/consumer_partition.go
pulsar/consumer_partition_test.go

The compression providers map in the partition consumer is a textbook case
for using go's lock-free sync.Map: the set of map entries is stable and
access is read-only.
On machines with 4 cores or greater, read contention on the sync.RWMutex
outweighs the cost of using a sync.Map.
Below is an old article on the subject, but it still holds true today:
https://medium.com/@deckarep/the-new-kid-in-town-gos-sync-map-de24a6bf7c2c
The sync.RWMutex and map of compression providers (`map[pb.CompressionType]compression.Provider`) in the partition consumer has been replaced with a sync.Map
This change is already covered by existing tests, such as:
- `pulsar/consumer_partitiion_test.go`
- Dependencies (does it add or upgrade a dependency): No
- The public API: No
- The schema: No
- The default values …

[Partition Consumer] Provide lock-free access to compression providers

---

pulsar/producer_partition.go

Fixes #687
As #687 said, use a separate gorutine to handle the logic of reconnect. Avoid blocking the reconnection logic due to the gorutine block of runEventsLoop

Use a separate gorutine to handle the logic of reconnect

---

pulsar/default_router_bench_test.go

The default router is called for every message published in the default configuration.  Therefore, it must maintain a high level of performance in the face of code changes.  Previously, we had a benchmark that measured serial routing performance, but we didn't have a way to measure performance of the router under parallel routing calls.
Added a `BenchmarkDefaultRouterParallel` bench test case to `default_router_bench_test.go` module.
I ran the default router bench test module by hand from the pulsar sub-directory:
```
$ go test  -bench="^BenchmarkDefaultRouterParallel$"  -count=10 -cpu=1,2,4,8,16 -run=^$
```
- Dependencies (does it add or upgrade a dependency): No
- The public API: No
- The schema: No
- The default values of configurations: No
- The wire protocol: No
- Does this pull …

[DefaultRouter] add a parallel bench test

---

pulsar/producer_partition.go

Reverts apache/pulsar-client-go#691

Revert "Use a separate gorutine to handle the logic of reconnect"

---

pulsar/producer_partition.go

Signed-off-by: xiaolongran <rxl@apache.org>
In https://github.com/apache/pulsar-client-go/pull/700, we use a separate go rutine to handle the logic of reconnect, so here you may encounter the same data race problem as https://github.com/apache/pulsar-client-go/pull/535
Now, the conn field is read and written atomically; avoiding race conditions.

Fix data race while accessing connection in partitionProducer

---

pulsar/internal/connection.go
pulsar/internal/connection_pool.go

Signed-off-by: xiaolongran <rxl@apache.org>
Fixes #697
As #697 said, In Go SDK, when the reconnection logic is triggered under certain conditions, the reconnection will not succeed due to request timeout.
Comparing the implementation of the Java SDK, we can see that each time the reconnection logic is triggered, the original connection will be closed and a new connection will be created.
So in this pr, we introduced a new `reconnectFlag` field in the `connection` struct to mark the reconnection state. When the broker actively informs the client to close the connection to trigger the reconnection logic, we will store it from the `connections` cache of the `connectionPool`. The old connection object is deleted, and a new connection is created to complete the reconnection
- Add …

Fix stuck when reconnect broker

---

pulsar/consumer_partition.go
pulsar/internal/buffer.go

Fixes #702
As #702 desc, In some scenarios, when the `Read(size uint32) []byte` interface in **Buffer** is called, the panic of a slice out of bounds may occur. So in this pr, the judgment of boundary conditions is added. When the slice is out of bounds, a `CommandAck_BatchDeSerializeError` error will be sent to the Broker to avoid the Go SDK process being down due to the panic.
After adding the current logic, the effect of execution is as follows:
- Add logic to check slice boundaries for `Read()` of Buffer

Fix slice bounds out of range for readSingleMessage

---

pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/producer_impl.go
pulsar/producer_partition.go
pulsar/reader_impl.go

address issue: https://github.com/apache/pulsar-client-go/issues/707

Encryption failure test case fix

---

pulsar/default_router.go
pulsar/default_router_test.go

Previously, we used atomic operations to read and update parts of the
default router state.  Unfortunately, the reads and updates could race
under concurrent calls which leads to unnecessary clock reads and an
associated slowdown in performance.
Now, we use atomic addition to increment the message count and batch size.
This removes the race condition by ensuring that each go-routine will have
a unique messageCount, and hence only one will perform the clock read.
Run the default router unit tests to verify correctness.
Run the default router bench parallel bench tests (https://github.com/apache/pulsar-client-go/pull/693) and verify the performance speedup; results before and after below:
```
name                      old time/op  new time/op  delta
DefaultRouterParallel     14.7ns ± 1% …
```

[DefaultRouter] fix unnecessary system clock reads due to races accessing router state

---

pulsar/consumer_partition.go
pulsar/producer_partition.go

Fixes #711
As #711 desc, when the user calls `Send()`, we introduced **waitgroup** to ensure that the messageID is returned synchronously, but in `internalSendAsync()`, the callback may be triggered multiple times, causing the issue of #711
- Replace `waitgroup` with `doneCh`, consistent with the implementation on the consumer side to facilitate subsequent code maintenance
- Introduce an atomic variable isDone to ensure that `close(channel)` will only be triggered once

Fix negative WaitGroup counter issue

---

.github/workflows/go.yml
.github/workflows/project.yml
README.md
docker-ci.sh
go.mod
go.sum
oauth2/auth.go
oauth2/go.mod
oauth2/go.sum

Fixes #675  https://github.com/apache/pulsar-client-go/issues/675
The original CVE 
CVE-2020-26160
high severity
Vulnerable versions: <= 3.2.0
Patched version: No fix
jwt-go allows attackers to bypass intended access restrictions in situations with []string{} for m["aud"] (which is allowed by the specification). Because the type assertion fails, "" is the value of aud. This is a security problem if the JWT token is presented to a service that lacks its own audience check. There is no patch available and users of jwt-go are advised to migrate to golang-jwt at version 3.2.1
`oauth2` go mod uses github.com/form3tech-oss/jwt-go, which is a fork from dgrijalva/jwt-go that is in read-only. The modification is switch to golang-jwt.
Set the minimum golang version to 1.15. It is because the …

[issue 675] oauth2 use golang-jwt address CVE-2020-26160

---

go.mod

1. `github.com/dgrijalva/jwt-go` contains a known CVE [vulnerability](https://github.com/advisories/GHSA-w73w-5m7g-f7qc)
2. This dependency was replaced with another jwt package.
3. But `oauth2` package version wasn't updated in master, so `github.com/apache/pulsar-client-go` still depends on it at the moment:
Update the version of `oauth2` to the latest commit to that package
```
$ go get github.com/apache/pulsar-client-go/oauth2@fe3b7c4e445b
$ cd $(go env GOPATH)/pkg/mod/github.com/apache/pulsar-client-go/oauth2@v0.0.0-20211108044248-fe3b7c4e445b/
$ go mod why github.com/dgrijalva/jwt-go
```
- Dependencies (does it add or upgrade a dependency): yes, upgrades …

Bump oauth2 package version to the latest in master

---

pulsar/producer_partition.go

Disable batchFlushTicker when Disable batching, reduce cpu cost
Stop the batchFlushTicker when Disable batching

[optimize] Stop batchFlushTicker when Disable batching

---

pulsar/producer_partition.go

Master Issue: [#729 ]
I received an alarm indicating that the server load was too high, used the pprof tool to locate the problem and determined that the cause was a ticker leak while a large number of producer creating failed.
Here are some screenshots to show it:
- pprof heap, there are a number of SDK-started ticker, accounted for 90%
- pprof cpu, cpu consumption is also here
stop ticker when create producer failed

[Issue 729]stop ticker when create producer failed

---

go.mod
go.sum

Signed-off-by: Shubham Sharma <shubhash@microsoft.com>
Fixes #725
This PR will enable pulsar-client-go to be a compliant library. One of its dependencies was not compliant with OSS licensing requirements earlier, and this PR upgrades to the latest version of it, which has a MIT license.
Ran the following commands
```bash
go get github.com/beefsack/go-rate@latest
go mod tidy
```
- **Dependencies** (does it add or upgrade a dependency): yes …

[Issue 725][Dependencies] Upgrade beefsack/go-rate

---

go.mod
go.sum

This commit updates klauspost/compress to v1.14.4 which provides some
performance improvements for pure go zstd compression and decompression.
For details, see:
https://github.com/klauspost/compress/releases
Results from `pulsar/internal/compression/compression_bench_test.go` show the speedup.
```
name                                        old time/op    new time/op     delta
Compression/zstd-pure-go-fastest               967µs ± 0%      907µs ± 1%   -6.21%  (p=0.000 n=8+7)
Compression/zstd-pure-go-fastest-8             968µs ± 1%      779µs ±13%  -19.57%  (p=0.000 n=8+8)
Compression/zstd-pure-go-default              1.52ms ± 1%     1.45ms ± 0%   -4.35%  (p=0.000 n=8+8)
Compression/zstd-pure-go-default-8            1.52ms ± 2%     1.45ms ± 1%   -4.66%  (p=0.000 n=8+8) …
```

Upgrade klauspost/compress to v1.14.4

---

Dockerfile

Fixes #748 
we should temporarily point to 2.8.2 for non-blocking pr until 2.10 is published to `pulsar:latest`

Temporarily point ci to pulsar 2.8.2

---

Dockerfile

Make dockerfile go version consistent with the `go.mod` file and `README doc` 
- update go version from 1.13 to 1.15

[build] make go version consistent

---

pulsar/consumer_partition.go
pulsar/impl_message.go
pulsar/internal/buffer.go
pulsar/internal/commands.go
pulsar/internal/commands_test.go
pulsar/internal/connection.go
pulsar/internal/pulsartracing/message_carrier_util_test.go
pulsar/message.go
pulsar/negative_acks_tracker_test.go

Adapt [PIP 90](https://github.com/apache/pulsar/wiki/PIP-90%3A-Expose-broker-entry-metadata-to-the-client) in go client
allow go client retrieve brokermetadata
- modify `CommandConnect` featureflags, turn `SupportsBrokerEntryMetadata` to true
- add `index()` `brokerPublishTime` methods on `message` interface
- add `Skip` method on bytebuffer

Exposing broker metadata

---

pulsar/reader.go
pulsar/reader_impl.go
pulsar/reader_test.go

Master Issue: #344
#368 adds support for schemas in consumer and producer, but didn't add the corresponding option to reader. This fixes that.
Add `schema` field to `ReaderOptions` and pass the value to the consumer so messages can be read with a schema.
`go test -run ^TestReaderWithSchema$ ./pulsar`
- The public API: yes
- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented? GoDoc

Add schema support to Reader

---

pulsar/reader.go
pulsar/reader_impl.go
pulsar/reader_test.go

allow config reader's subscription name, follow java's feature https://github.com/apache/pulsar/pull/8801
add param `SubscriptionName` in `ReaderOptions`
add the test for setting the subscritpion name

allow config reader subscription name

---

pulsar/client_impl_test.go
pulsar/producer_test.go

Currently a few of the test topics aren't cleaned up after use, so if the same test is ran twice topic creation would fail.
`defer` topic cleanup in unit tests.
This change is already covered by existing tests. For example, before the change,
`go test -timeout 5s -run ^TestHTTPTopicPartitions$ github.com/apache/pulsar-client-go/pulsar -count=2`
would fail, and now it would pass.

Cleanup topics after unit tests

---

pulsar/client.go
pulsar/client_impl.go
pulsar/table_view.go
pulsar/table_view_impl.go
pulsar/table_view_test.go

Fixes https://github.com/apache/pulsar/issues/13929
This adds TableView support to the Golang client so it can have feature parity with the Java client.
See https://github.com/apache/pulsar/issues/12356 and https://github.com/apache/pulsar/pull/12838 for context.
Add `TableView` and `Client.CreateTableView` and so users can track a keyed topic as a map.
- `go test -timeout 5s -run ^TestTableView$ github.com/apache/pulsar-client-go/pulsar`
- The public API: yes
- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented? GoDocs

Add TableView support

---

pulsar/producer_partition.go

Most of this situation is caused by the timeout of sending the message. When the sending of the message times out, we will try to remove the object from the local pendingQueue, but after a period of time, the broker may push the message back, resulting in the connection reconnect occurs.
Follow Java SDK process logic:
```
op = pendingMessages.peek();
if (op == null) {
if (log.isDebugEnabled()) {
log.debug("[{}] [{}] Got ack for timed out msg {} - {}", topic, producerName, sequenceId, highestSequenceId);
}
return;
}
```
When a timeout occurs, we just need to drop the request instead of closing the connection.
- Remove reconnection timeout when sendReceipt timeout.

Fix ack timeout cause reconnect

---

pulsar/internal/connection.go
pulsar/producer_partition.go

At present, it is assumed that there are multiple topics multiplexing the same TCP connection, then any topic may trigger the reconnection operation of this TCP connection. In the actual production environment, we see that a small number of producers will report the following errors:
```
time="2022-04-19T21:43:28+08:00" level=warning msg="Connection closed unable register listener id=41" local_addr="9.xcxx:43051" remote_addr="pulsar://1.xxxx:6650"
```
The specific code logic is as follows:
https://github.com/apache/pulsar-client-go/blob/master/pulsar/internal/connection.go#L851-L855
We can see that when we try to register the producer, we will first check the status of the current connection. If the connection is closed, then we will …

Fix producer unable register when cnx closed

---

pulsar/error.go
pulsar/producer_partition.go
pulsar/producer_test.go

Add tests for producer schema encode.
Fixes #763
When using Producer, if the ProducerMessage.Value fails to encode using the producer's Schema, the code never returns when using `producer.Send()` and never executes the callback when using `producer.SendAsync()`. Additionally, the publishSemaphore that was Acquired is never released.
When an error is returned by Schema Encode, release the Semaphore and execute the callback.
- *Added integration test with failure to encode schema*
- Does this pull request introduce a new …

[Issue 763][producer] Fix deadlock in Producer Send when message fails to encode.

---

pulsar/producer_partition.go

…rrentBatches if the associated batch builder contains multi batches(KeyBasedBatchBuilder).
Doing transparent forwarding could centralized the branching logic at only one place.
<--
- Each commit in the pull request has …

[Issue 749]Fix panic caused by flushing current batch with an incorrect internal function.

---

pulsar/consumer_partition.go

At present, for different Command requests, when we request the Broker, some commands check the state of the current consumer, and some do not check the state of the current consumer.
If the consumer's state is closing or closed, in fact, we don't need to continue to request the broker, but should directly return the current request.
The current change checks all requests to the broker's command and adds a check on the consumer state.
- add error info for `RequestOnCnxNoWait` func
- add consumer state check when request commands

Add consumer state check when request commands

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_partition.go
pulsar/consumer_regex.go
pulsar/impl_message.go
pulsar/internal/connection.go
pulsar/internal/connection_pool.go
pulsar/internal/pulsartracing/consumer_interceptor_test.go

There are mainly two problems fixed in this pr. 
1. The first one is to return some error information when the Go SDK handles Ack by itself to the user. Note: This is not the error information returned by the Broker side, but some errors that may occur in the Go SDK itself when processing the Ack command link. If we ignore these possible Errors here, then when the user calls Ack, because there is no return value, the user will think that the current Ack request has been successful, but in fact the Ack command may have failed when the Go SDK requested, resulting in this The Ack status of a message is lost and it becomes a hollow message. This will cause the backlog size on the broker side to continuously increase until the threshold of the backlog is triggered and the message sending …

Add error response for Ack func

---

pulsar/internal/connection.go
pulsar/internal/connection_pool.go

Fixes #766 
The change made in #703 is invalid. See #766 .
One of the motivation of #703 was to implement similar behavior as there is in Java SDK. The change didn't do that.
In the Java SDK, the concepts (classes) are fairly misleading, and something that might seem to be a connection close isn't one. The ClientHandler is really a reference to a connection in the Java SDK. The ClientCnx (which holds the TCP/IP connection) isn't closed in the Java SDK in ClientHandler.connectionClosed:
https://github.com/apache/pulsar/blob/04aa9e8e51869d1621a7e25402a656084eebfc09/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java#L122-L141
This reverts #703 / commit 1a8432cfd3aa231f8eb3c97171a47eab98a8f20a.

Revert "Fix stuck when reconnect broker (#703)"

---

pulsar/consumer_partition_test.go
pulsar/internal/metrics.go
pulsar/internal/topic_name.go
pulsar/internal/topic_name_test.go

Signed-off-by: hantmac <hantmac@outlook.com>
Fixes [#<718>](https://github.com/apache/pulsar-client-go/issues/718)
Fix nil pointer dereference in TopicNameWithoutPartitionPart
`topic_name_test.go`

[Issue 718] Fix nil pointer dereference in TopicNameWithoutPartitionPart

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/internal/connection.go

Follow https://github.com/apache/pulsar/pull/8161, support Ack Response Command for Go SDK
- Add `AckWithResponse` in `ConsumerOptions` struct

Support ack response for Go SDK

---

pulsar/consumer_partition.go

Fixes #779
Fix bug in #779
Set requestId int the ack request command when the AckWithResponse option is enabled.

[Issue 779]Fix ack request not set requestId when enable AckWithResponse option

---

.github/workflows/go.yml
.github/workflows/project.yml
.golangci.yml
pulsar/consumer_partition.go
pulsar/schema.go

Just a minor change to ensure compatibility with go 1.18

[github ci] add go 1.18 to the test matrix

---

pulsar/consumer_partition.go
pulsar/internal/connection.go

Related to https://github.com/apache/pulsar-client-go/pull/761
This PR fixed the issue using closed connection at consumer side.
If same issue as https://github.com/apache/pulsar-client-go/pull/761 happens at consumer side, consumer will report the following errors and can't consume any messages.
```
ERRO[0180] [Connection was closed when request flow cmd]  consumerID=1 name=wzrtq subscription=sub1 topic="persistent://public/default/topic-go-1"
ERRO[0180] [unable to send initial permits to broker]    consumerID=1 error="connection closed" name=wzrtq subscription=sub1 topic="persistent://public/default/topic-go-1"
```
* return an error when unable to add consumer handler.

Fix using closed connection in consumer

---

Dockerfile
integration-tests/.htpasswd
integration-tests/license_test.go
integration-tests/standalone.conf
pulsar/client.go
pulsar/client_impl_test.go
pulsar/internal/auth/basic.go
pulsar/internal/auth/basic_test.go
pulsar/internal/auth/provider.go

Miss the basic authentication.
- Add the basic authentication provider in `internal/auth`
- Add factory method of basic authentication provider in `client.go`
- Configure the basic authentication provider in integration tests
- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented? docs

feat: add basic authentication

---

go.mod
go.sum
perf/perf-producer.go

Fixes #752 
The go rate limiter library, beefsack/go-rate, is an MIT license. We need update the license. The PR removes this dependency.
In Go, it is rather simple to implement a rate limiter directly. A buffered channel is used to store a request timestamp as message. The channel receiver check each timestamp (in the message) to sleep on the remaining time duration. 
The per second rate is the size of channel buffer. If the buffer is full, the main producing go routine blocks on producing Pulsar message, until the sleep expires and move to on the next message in the channel thus free up a slot in the channel.
It resembles leaky bucket rate limiting implementation. Because of leveraging go channel, it uses less than 10 lines of code and remove the dependency entirely. Since the …

[issue #752] replace go-rate rate limiter with a buffered channel implementation

---

pulsar/consumer_partition.go
pulsar/internal/backoff.go
pulsar/internal/backoff_test.go
pulsar/internal/metrics.go
pulsar/producer_partition.go

Implement #814 
In a Pulsar cluster's kubernetes deployment or a deployment with Proxy/LB in the front, we need metrics counter to track the re-connection failure producers and consumers.
When brokers go offline but the proxy/LB is still functioning, TCP connection can still be established but the topic look up failed. pulsar_client_connections_establishment_errors counter is not incremented in this case.  Therefore new counters are required to track such failure cases.
Two new counter metrics `pulsar_client_producers_reconnect_failure` and `pulsar_client_consumers_reconnect_failure` will be incremented at the producer_partition and consumer_partition retry failure code block.
Two new counter metrics `pulsar_client_producers_reconnect_max_retry` and …

[issue 814] consumer and producer reconnect failure metrics counter

---

pulsar/internal/commands.go

Currently, the golangci-lint returns an error about coding style like below.
```
bash-4.2# /root/go/bin/golangci-lint run -v
INFO [config_reader] Config search paths: [./ /pulsar-client-go / /root]
INFO [config_reader] Used config file .golangci.yml
INFO [lintersdb] Active 16 linters: [bodyclose deadcode goimports gosimple govet ineffassign lll misspell prealloc revive stylecheck typecheck unconvert unparam unused varcheck]
INFO [loader] Go packages loading at mode 575 (compiled_files|types_sizes|deps|exports_file|files|imports|name) took 2.153604501s
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 242.078666ms
INFO [linters context/goanalysis] analyzers took 0s with no stages
INFO [runner/skip dirs] Skipped 2 issues from dir examples/producer by pattern (^|/)examples($|/) …
```

[cleanup] Fix to follow lint error (File is not `goimports`-ed (goimports))

---

go.mod
go.sum

A vulnerability scan on this repository found a vulnerable version of `gopkg.in/yaml.v3`.
https://github.com/advisories/GHSA-hp87-p4gw-j4gq
We need to upgrade the version of `github.com/stretchr/testify` because it directly depends on `gopkg.in/yaml.v3`.
https://github.com/stretchr/testify/pull/1192
Upgraded `github.com/stretchr/testify` to the latest version, v1.8.0.

[security] Bump github.com/stretchr/testify to update gopkg.in/yaml.v3

---

pulsar/client.go
pulsar/client_impl.go
pulsar/consumer_partition_test.go
pulsar/internal/commands.go
pulsar/internal/lookup_service_test.go
pulsar/internal/metrics.go

Add ClientOptions.MetricsRegisterer for customizing prometheus
metrics registerer.
Currently, client always use `prometheus.DefaultRegisterer` to register metrics, but the application might already have a registerer for metrics registering and exporting.
Add ClientOptions.MetricsRegisterer to allow user to customize the metrics registerer. They can use the existed registerer in their applications.
- Does this pull request introduce a new feature? …

[client] Add MetricsRegisterer to ClientOptions

---

pulsar/consumer.go
pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/retry_router.go

Fixes #807 
To customize producer options for DLQ topics.
Add DLQProducerOptions to consumer's DLQ policy.
The existing DLQ test is enhanced to cover customized producer options.
A new producer options field, `DLQProuducerOptions`, is introduced for DLQ policy to govern the producer options.
```
ConsumerOptions{
Topics:              topics,
DLQ: &DLQPolicy{
MaxDeliveries:   3,
DeadLetterTopic: dlqTopic,
DLQProducerOptions: ProducerOptions{
BatchingMaxPublishDelay: 100 * time.Millisecond,
},
},
```
- The public API: yes
- The default values of configurations: yes (the existing lz4 compression type is the default.)
- Does this pull request …

[issue #807] dlq topic producer options

---

pulsar/consumer_test.go
pulsar/message_test.go
pulsar/producer_partition.go

time.Time should use `IsZero()` to check for initialization and now, it use compare to 0, it on the wrong side.
*(or)*
*(or)*
*(example:)*
- The wire …

[bugfix] Fix wrong check eventime by default

---

pulsar/negative_acks_tracker.go
pulsar/negative_acks_tracker_test.go
pulsar/negative_backoff_policy.go
pulsar/negative_backoff_policy_test.go

NackBackoffPolicy.Next return int64 type before, but it used as time.Durtion.
NackBackoffPolicy.Next return time.Duration
NackBackoffPolicy.Next return int64 type before, but it used as time.Durtion.
return int64 before is ambiguous .   NackBackoffPolicy.Next return time.Duration may  be better.
NackBackoffPolicy.Next return time.Duration . 
- [ ✓  ] Make sure that the change passes the CI checks.
This change is already covered by existing tests . 

Fixs : NackBackoffPolicy.Next return time.Duration

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/dlq_router.go
pulsar/internal/backoff.go
pulsar/internal/backoff_test.go
pulsar/internal/http_client.go
pulsar/internal/rpc_client.go
pulsar/negative_backoff_policy.go
pulsar/producer.go
pulsar/producer_partition.go
pulsar/retry_router.go

Fixes #851
As  #851 said, the reconnection strategy in the default reconnection logic is not universal. In different usage scenarios, we better allow users to customize the reconnection strategy.
Exposed `BackoffPolicy` in Producer and Consumer

Parameterize the reconnection option

---

CHANGELOG.md
VERSION
stable.txt

- add 0.9.0 changelog
- bump VERSION and stable version
*(or)*
*(or)*
*(example:)* …

add 0.9.0 release changelog

---

pulsar/client.go
pulsar/client_impl.go
pulsar/client_impl_test.go
pulsar/internal/connection.go
pulsar/internal/http_client.go

Add a TLS transport config for the client.
In the old version, we can only use the TLS authentication to config the TLS transport, so we cannot use the other authentication, which is confusing, so we need to add a TLS transport config for the client, which would resolve the issue I mentioned.
When using this config with the TLS authentication, the TLS authentication config is preferred.

Add TLS transport config

---

pulsar/consumer_partition.go
pulsar/consumer_test.go

Fixes #833 
The availablePermits may leak when message is discarded. Please refer to #833 for details. 
- Wraps a struct availablePermits to atomic increase and reset. 
- Add the permits increasing in `discardCorruptedMessage`.
This change added tests and can be verified as follows: `pulsar/consumer_test.go:TestAvailablePermitsLeak()`

[Issue 833] Fix the availablePermits leak that could cause consumer stuck.

---

scripts/run-ci.sh

Master Issue: #870 
Currently, the CI of pulsar-go-client is more and more prone to fail due to timeout. It's hard to find out which test case failed based on CI log now.
Add go test flag '-v' will make the CI log more clearly to locate which test failed or timeout.
Add go test flag '-v' in `run-ci.sh`

[CI] Add go test flag '-v' for more clearly CI log

---

pulsar/internal/utils.go
pulsar/internal/utils_test.go

Signed-off-by: Ayman Khalil <ayman.khalil@datastax.com>
When producing messages via the go client, if the user doesn't assign an explicit `EventTime` to the message, the following `uint64` will end up on the wire:
`11651379494838`
This is because [TimestampMillis](https://github.com/aymkhalil/pulsar-client-go/blob/7fbfbaac9532efd3dbab7f768daca045a86d9966/pulsar/internal/utils.go#L30) calls UnixNano, but [UnixNano](https://pkg.go.dev/time#Time.UnixNano) on the zero Time is undefined.
[This](https://go.dev/play/p/mDPKyxFCKLL) code mimic what happens when TimestampMillis is called on the Zero value
Please note that go consumers (like this[ ](https://github.com/apache/pulsar-client-go/blob/a013ff0b7353fab87a7eb7599377bb06b46eb7b7/pulsar/consumer_test.go#L624)test) will NOT notice this issue, …

Fix marshalling time.Time{} to uint64

---

pulsar/consumer_partition.go

The `availablePermitsCh` may cause the dispatcher stuck.
https://github.com/apache/pulsar-client-go/blob/0b0720ab73d7f6378b8b6ac37acbafe547c268c8/pulsar/consumer_partition.go#L1096-L1109
For example, if `messageCh <- nextMessage` continueously selected 10 times, the `availablePermitsCh` will be filled. The next `messageCh <- nextMessage` will be stuck forever because `pr := <-pc.availablePermitsCh` can never be reached.
Remove the `pc.availablePermitsCh` from dispatcher.
*(or)*
*(or)*

[Fix] Fix the dispatcher() stuck caused by availablePermitsCh

---

pulsar/producer_partition.go

Master Issue: #877 
The producer `Send()` is a sync method. It depends on closing doneCh by `sendRequest.callback()` to finish waiting. But there are some return case does not call `sendRequest.callback()`, which may cause `Send()` stuck.
https://github.com/apache/pulsar-client-go/blob/5679f1f7b3840184b8947b5b8c8170fec181eecc/pulsar/producer_partition.go#L481-L484
https://github.com/apache/pulsar-client-go/blob/5679f1f7b3840184b8947b5b8c8170fec181eecc/pulsar/producer_partition.go#L492-L498
https://github.com/apache/pulsar-client-go/blob/5679f1f7b3840184b8947b5b8c8170fec181eecc/pulsar/producer_partition.go#L528-L531
There are three places need to add `sendRequest.callback()` before return. These code is all intrduced in https://github.com/apache/pulsar-client-go/pull/611. I guess the …

[Fix] Fix the Send() stuck caused by callback() not being called

---

pulsar/consumer_test.go
pulsar/producer_test.go
pulsar/reader.go
pulsar/reader_impl.go
pulsar/reader_test.go

Fixes #872
Add `BackoffPolicy` for `ReaderOptions` and add tests for `BackoffPolicy`.
Because `Reader` uses `partitionConsumer`, just adding a field in `ReaderOptions` is enough.
This change has added tests.
- **The public API: (yes)**

feat: add BackoffPolicy to `reader` and improve test case

---

pulsar/internal/connection.go
pulsar/internal/http_client.go

Fix load tls certificate.
This is an incorrect condition. The `CertFile` and `KeyFile` cannot be empty, see the following code that directly read this file:
```
func LoadX509KeyPair(certFile, keyFile string) (Certificate, error) {
certPEMBlock, err := os.ReadFile(certFile)
if err != nil {
return Certificate{}, err
}
keyPEMBlock, err := os.ReadFile(keyFile)
if err != nil {
return Certificate{}, err
}
return X509KeyPair(certPEMBlock, keyPEMBlock)
}
```

Fix load tls certificate

---

oauth2/client_credentials_provider.go

- Code cleanup.
- A minor change to use the constant instead of a repeated string.
- Does this pull request introduce a new feature? - **No.**

OAuth2 KeyFileProvider - Use the `DATA` constant as prefix

---

oauth2/client_credentials_provider.go
oauth2/client_credentials_provider_test.go
oauth2/data_url.go
oauth2/data_url_test.go

Add data url format to read the key file, same with the java client.
This closes #866.

Add data url format to read the key file

---

pulsar/consumer_partition.go

Master Issue: #879 
#879 shows ackReq.err has data race problem.
Read
https://github.com/apache/pulsar-client-go/blob/44b64aa712a0d85ce7562134c0f7cf3d21f17ac0/pulsar/consumer_partition.go#L471-L473
Write
https://github.com/apache/pulsar-client-go/blob/44b64aa712a0d85ce7562134c0f7cf3d21f17ac0/pulsar/consumer_partition.go#L702-L707
After ackReq.doneCh has introduced in #777 , I think the final return value of `AckId` can be nil. Because ` ackReq.err` may not necessarily be set before the `AckID` returns. If user need to know the result of ack, just using `AckIDWithResponse` will be fine.
Modify the return value of `AckID`.
*(or)*
This change is already covered by …

[Fix] Fix the data race of ackReq.err

---

pulsar/consumer_test.go
pulsar/message.go

Fixes #453 
Sometimes we need to deal with some messages manually.
```go
pb "github.com/apache/pulsar-client-go/pulsar/internal/pulsar_proto"
msgID := &pb.MessageIdData{
LedgerId:             proto.Uint64(699),
EntryId:              proto.Uint64(11),
Partition:            proto.Int32(0),
BatchIndex:           proto.Int32(0),
}
bytes, _ := proto.Marshal(msgID)
id, _ := pulsar.DeserializeMessageID(bytes)
err = consumer.AckID(id)
```
Here is the nonsensical serialization and deserialization code, also `pb` is an internal package and cannot be accessed externally.
Add the `NewMessageID()` method.

[Issue 453] Add NewMessageID() method.

---

pulsar/consumer_test.go
pulsar/producer_partition.go

Fixes #899 
`MessageMetadata.Compression` is missed to be set when batching is disabled in #805. This pr aims to fix it.
Set the `MessageMetadata.Compression` when batching is disabled and add test code.

[Issue 899] Fix the compression broken when batching is disabled

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/internal/connection.go

Fixes #901
Support consumer active events.
Add an option to consumers, add callback on `BaseCommand_ACTIVE_CONSUMER_CHANGE`.

[feat] support for consumer event listener

---

pulsar/consumer_impl.go
pulsar/consumer_test.go

In Apache pulsar documention default retry and dlq topic names are as follows
for Retry: `<topicname>-<subscriptionname>-RETRY`
https://pulsar.apache.org/docs/2.10.x/concepts-messaging#retry-letter-topic
for DLQ: `<topicname>-<subscriptionname>-DLQ`
https://pulsar.apache.org/docs/2.10.x/concepts-messaging#dead-letter-topic
added topicname also in the default Retry and DLQ topic name
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery …

Default retry and dlq topic name fixed as per the doc

---

pulsar/consumer.go

Fixes #923 
Remove the outdated interface description of `SeekByTime`. More details here #923.
Remove the outdated interface description of `SeekByTime`

[Issue 923] Remove the outdated interface description of `SeekByTime`

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_partition.go
pulsar/consumer_regex.go
pulsar/consumer_test.go
pulsar/impl_message.go
pulsar/impl_message_test.go
pulsar/internal/pulsartracing/consumer_interceptor_test.go

Master Issue: #183 
Cumulative acknowledgement is a useful feature. Users can use this feature to ack messages in the stream up to (and including) provided message. 
Issue #183 shows more details.
- Add two api `AckCumulative` and `AckIDCumulative` for `Consumer`.
``` golang
// AckCumulative the reception of all the messages in the stream up to (and including)
// the provided message.
AckCumulative(msg Message) error
// AckIDCumulative the reception of all the messages in the stream up to (and including)
// the provided message, identified by its MessageID
AckIDCumulative(msgID MessageID) error
```
- Add the `AckCumulative` and `AckIDCumulative` implementation for `consumer`, `multiTopicConsumer`, `regexConsumer` and `mockConsumer`.
- Add the unit test `TestConsumerNoBatchCumulativeAck` …

[Issue 183] [Feat] Support cumulative acknowledge

---

pulsar/table_view_impl.go
pulsar/table_view_test.go

Currently, when we publish a nil value message([tombstones](https://en.wikipedia.org/wiki/Tombstone_(data_store))) to a compacted topic used to `TableView`, the `TableView` will store a nil value in the map, but we should remove this key since this is a tombstone.
* Handle nil value message correctly in table-view
* Add unit test to verify.

Handle nil value message correctly in table-view

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_regex.go
pulsar/consumer_test.go
pulsar/internal/pulsartracing/consumer_interceptor_test.go

Fixes #915 
Master Issue: #915 
In Java SDK custom properties are allowed when ReconsumeLater is called so adding same in golang
Created a function which will take custom message properties and add them to retry message as per the doc.
To reduce the same code i callback this function from the reconsume later function. because other part of the code is same execpt the one which should change.
*(or)*
*(or)*
This …

Allow CustomProperties when sending message for retry

---

pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/reader_impl.go

Master Issue: #918 
The two chanel `clearMessageQueuesCh` and `clearQueueCb` just need to keep one.
For more details please check #918.
This PR does not ony aim to clean up, but also fix the potential bug in `clearMessageQueuesCh`.
For example, the `clearMessageQueuesCh` do the jod including clearing messageCh. But it may cause problem when `SeekByTime` invoked on partition topic.
https://github.com/apache/pulsar-client-go/blob/1d3499a18d526b4b1aef0bdbbc54ac812b8ae0c0/pulsar/consumer_impl.go#L614-L626
https://github.com/apache/pulsar-client-go/blob/1d3499a18d526b4b1aef0bdbbc54ac812b8ae0c0/pulsar/consumer_partition.go#L1168-L1175
When consume the partition topic, all the `partitionConsumer` share the same `messageCh`. After `SeekByTime` on partitioned topic, the messageCh may be cleared …

[Issue 918] [Refactor] Remove the `clearMessageQueuesCh` in `partitionConsumer.dispatcher()`

---

go.mod
go.sum
integration-tests/conf/standalone.conf
pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/impl_message.go
pulsar/impl_message_test.go
pulsar/message.go
pulsar/producer_partition.go
pulsar/reader_test.go

Fixes https://github.com/apache/pulsar-client-go/issues/894
Add an `EnableBatchIndexAcknowledgment` to specify whether batch index ACK is enabled. Since this feature requires the conversion between a bit set and its underlying long array, which is similar to Java's `BitSet`, this commit introduces github.com/bits-and-blooms/bitset dependency to replace the `big.Int` based implementation of the bit set.
Add a `BatchSize()` method to `MessageId` to indicate the size of the `ack_set` field. When the batch index ACK happens, convert the `[]uint64` to the `[]int64` as the `ack_set` field in `CommandAck`. When receiving messages, convert the `ack_set` field in `CommandMessage` to filter the acknowledged single messages.
Remove the duplicated code in `AckID` and `AckIDWithResponse`. …

[feature] Support batch index ACK

---

.github/workflows/project.yml
README.md
integration-tests/license_test.go
oauth2/authorization_tokenretriever_test.go
oauth2/client_credentials_provider.go
oauth2/client_credentials_provider_test.go
perf/pulsar-perf-go.go
pulsar/auth/athenz.go
pulsar/auth/athenz_test.go
pulsar/auth/basic_test.go
pulsar/auth/oauth2_test.go
pulsar/auth/token.go
pulsar/client_impl_test.go
pulsar/consumer_test.go
pulsar/crypto/default_crypto_Key_reader.go
pulsar/helper_for_test.go
pulsar/internal/compression/compression_bench_test.go
pulsar/internal/connection.go
pulsar/internal/http_client.go
pulsar/internal/lookup_service_test.go

The `io/ioutil` package has been deprecated in go1.16, see the [release notes](https://go.dev/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` calls with their new definitions in the `io` and `os` packages.
This change is already covered by existing tests.

Migrate from the deprecated io/ioutil package

---

pulsar/producer.go
pulsar/producer_partition.go
pulsar/producer_test.go

Master Issue: #931
#931
- Support the `Exclusive` Producer access mode config in the `ProducerOptions`.
**Note**: `WaitForExclusive` and `ExclusiveWithFencing` will be supported in other PR.
- Add `TestExclusiveProducer` to cover it.

[feat] Support Exclusive Producer access mode.

---

pulsar/internal/connection.go
pulsar/internal/rpc_client.go
pulsar/producer.go
pulsar/producer_partition.go
pulsar/producer_test.go

Master Issue: #931
#931
- Support the `WaitForExclusive` Producer access mode config in the `ProducerOptions`.
- Add `TestWaitForExclusiveProducer ` to cover it.

[feat] Support WaitForExclusive producer access mode.

---

pulsar/ack_grouping_tracker.go
pulsar/ack_grouping_tracker_test.go
pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_partition_test.go
pulsar/consumer_test.go
pulsar/message.go

Fixes #949 
Currently the Go client does not support grouping ACK requests, so each time `Ack` (or similar APIs) is called, a ACK request will be sent, which could downgrade the performance. We need to support configuring the time and size to cache `MessageID` before sending ACK requests.
- Add an `AckGroupingOptions` field to `ConsumerOptions`, when it's nil, use 100ms as the max time and 1000 as the max size.
- Add an `ackGroupingTracker` interface to support grouping ACK requests.
- When `AckWithResponse` is false, adding the `MessageID` instance to the tracker instead of sending the requests to `eventsCh`.
- Added `ack_grouping_tracker_test.go` to verify `ackGroupingTracker` in various cases
- The consumer side change can be …

Support grouping ACK requests by time and size

---

integration-tests/conf/standalone.conf

After https://github.com/apache/pulsar-client-go/pull/953, the Pulsar version was upgraded from 2.8.3 to 2.10.3. However, [PIP-119](https://github.com/apache/pulsar/pull/13352) changed the default value of `subscriptionKeySharedUseConsistentHashing` to true, which leads to the flakiness of Key_Shared subscription related tests.
Example: https://github.com/apache/pulsar-client-go/actions/runs/4291098473/jobs/7475868787
Configure `subscriptionKeySharedUseConsistentHashing` with `false`.

Fix flaky Key_Shared subscription related tests

---

perf/perf-consumer.go
perf/perf-producer.go

Currently, the perf tool does not support the maximum number of messages in batch for producer and batch index ACK for consumer.
- Add the `--batching-max-size` option to configure the maximum number of messages for producer
- To keep the code style consistent, change the `--batching-max-size` config from `int` to `uint`
- Add the `--enable-batch-index-ack` option to enable batch index ACK for consumer.

[perf] Support batch index ACK and max number of messages in batch

---

pulsar/client.go
pulsar/client_impl.go
pulsar/error.go
pulsar/internal/channel_cond.go
pulsar/internal/channel_cond_test.go
pulsar/internal/memory_limit_controller.go
pulsar/internal/memory_limit_controller_test.go
pulsar/producer_partition.go
pulsar/producer_test.go

Master Issue: #927 
#927 
- Added `channel_cond` class to enhance `sync.cond` to support wait that can accept context.
- Added the `memory_limit_controller` class.
- Producer adds memory limit relate logic.
- Added `channel_cond_test` to cover `channel_cond`
- Added `memory_limit_controller_test` to cover `mem_mory_limit_controller`
- Added `TestMemLimitRejectProducerMessages` and `TestMemLimitContextCancel ` to cover producer relate logic.

[feat] Support memory limit for producer.

---

distribution/LICENSE.bin.txt

This closes #952.
go-rate is licensed under GPLv3, which is not compatible with ALv2.
It has been already removed in https://github.com/apache/pulsar-client-go/pull/799 but we don't update all references.
Thank @artursouza for spotting this.

Fix license information for go-rate

---

pulsar/consumer_impl.go

Currently, the NackBackoffPolicy does not take effect, because in NackBackoffPolicy, we need to use Msg object for Nack, and MsgId cannot be used for Nack, otherwise the Msg redeliverCount field cannot be obtained for backoff retry.

Fix nack backoff policy logic

---

pulsar/client.go
pulsar/client_impl.go
pulsar/client_impl_test.go
pulsar/internal/connection.go
pulsar/internal/connection_pool.go
pulsar/internal/helper.go

The go implementation of PIP-165:https://github.com/apache/pulsar/issues/15516
* Add new configuration `ConnectionMaxIdleTime` to `ClientOptions`
* Add a goroutine to `ConnectionPool` to period check and release idle connections.
This change added tests
- If yes, how is the feature documented? ( GoDocs)
- If a feature is not documented yet in this PR, please create a followup issue for adding the …

[PIP-165] Auto release idle connections

---

pulsar/internal/connection_pool.go

Fixes #978
From the data race log of the issue:
```
2023-03-07T02:05:50.0096902Z WARNING: DATA RACE
2023-03-07T02:05:50.0097176Z Read at 0x00c0003bb298 by goroutine 111:
2023-03-07T02:05:50.0097767Z   github.com/apache/pulsar-client-go/pulsar/internal.(*connectionPool).checkAndCleanIdleConnections()
2023-03-07T02:05:50.0098468Z       /pulsar/pulsar-client-go/pulsar/internal/connection_pool.go:157 +0x24d
2023-03-07T02:05:50.0099058Z   github.com/apache/pulsar-client-go/pulsar/internal.StartCleanConnectionsTask.func1()
2023-03-07T02:05:50.0099727Z       /pulsar/pulsar-client-go/pulsar/internal/helper.go:25 +0x47
2023-03-07T02:05:50.0099934Z 
2023-03-07T02:05:50.0100066Z Previous write at 0x00c0003bb298 by goroutine 69:
2023-03-07T02:05:50.0100537Z …
```

[fix] Fix data race in checkAndCleanIdleConnections

---

pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_partition.go
pulsar/consumer_regex.go
pulsar/impl_message.go
pulsar/reader_impl.go

`toTrackingMessageID()` is a function that is widely used in `consumer` implementation. It can convert an interface type  `MessageID` into an struct type `trackingMessageID`. In addition, the second return value also plays a role in checking the `MessageID` type. In other words, it indicates that `MessageID` **cannot** be a user-defined type. From the perspective of code readability, `toTrackingMessageID()` should not do both.
**Note**: After #968 , `toTrackingMessageID()` returns only a pointer now. The role of original `ok` is replaced by nil pointer  now. However, the main content discussed in this PR has not changed.
For example.
https://github.com/apache/pulsar-client-go/blob/e2ea255052e8a527091791ef368851d885ee2d45/pulsar/consumer_regex.go#L176-L181
This example is the correct …

[refactor]: Refactor the toTrackingMessageID()

---

pulsar/message_chunking_test.go

Fixes #980 
The root cause of the flaky test is the producer publishes rate may be too large. This causes the producer doesn't even have enough messages in the publish queue. So there may not be the error `producer send queue is full: ProducerQueueIsFull` in some case.
* Setup publish rate limiter for the topic in TestChunksEnqueueFailed to reduce flaky. …

[fix] Setup rate limiter for TestChunksEnqueueFailed to reduce flaky

---

pulsar/internal/connection.go
pulsar/internal/rpc_client.go

prevent rpc client panic on rpc response if `ProducerReady` is nil
use `ProducerSuccess.GetProducerReady` instead of `ProducerSuccess.ProducerReady`
**panic log**
```log
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe997de]
goroutine 982 [running]:
github.com/apache/pulsar-client-go/pulsar/internal.(*connection).internalReceivedCommand(0xc0005d0840, 0xc0010a6000, {0x0?, 0x0})
/go/pkg/mod/github.com/apache/pulsar-client-go@v0.9.1-0.20230301160414-42ded0d59c46/pulsar/internal/connection.go:526 +0x1de
github.com/apache/pulsar-client-go/pulsar/internal.(*connection).run(0xc0005d0840)
/go/pkg/mod/github.com/apache/pulsar-client-go@v0.9.1-0.20230301160414-42ded0d59c46/pulsar/internal/connection.go:420 …
```

fix: prevent rpc client panic on rpc response if `ProducerReady` is nil

---

pulsar/ack_grouping_tracker.go
pulsar/ack_grouping_tracker_test.go

Master Issue: #979
The root cause is `internalReceivedCommand` will be blocked by `timedAckGroupingTracker.isDuplicate`. 
https://github.com/apache/pulsar-client-go/blob/75d2df3b7d1d1d04fb660a1b6c11ede1d2f161bf/pulsar/internal/connection.go#L421-L422
```
1 @ 0x104ff6204 0x104fc232c 0x104fc1ed8 0x1054894dc 0x105497934 0x10541fa60 0x10541e430 0x10541d3bc 0x10541c114 0x105027874
```
Then, the subsequent commands under this `connection` cannot be processed, resulting in a timeout.
**Failed logs**
```
time="2023-03-02T06:34:19Z" level=info msg="Closing consumer=2" consumerID=2 name=rtvmw subscription=sub-2 topic="persistent://public/default/my-topic-70957754"
time="2023-03-02T06:34:49Z" level=warning msg="Failed to close consumer" consumerID=2 error="request timed out" name=rtvmw …
```

Fix ack grouping tracker is duplicate method will be blocked.

---

pulsar/reader.go
pulsar/reader_impl.go
pulsar/reader_test.go

Fixes #935 
Support expose the chunk config of consumer to the reader
Add chunk config related filed in `ReaderOptions` struct.
- Added test for specified and default chunk options in reader.

[feat] Expose the chunk config of consumer to the reader

---

pulsar/ack_grouping_tracker.go
pulsar/ack_grouping_tracker_test.go
pulsar/consumer_partition.go
pulsar/consumer_partition_test.go
pulsar/message.go

Currently, when `EnableBatchIndexAck` is true, the ACK performance is very poor. There are two main reasons:
1. Acknowledgment by list is not supported. It means that even N MessageIDs are grouped, there are still N ACK requests to send.
2. The implementation of ACK grouping tracker is wrong. Give a batch that has N messages, when batch index ACK is enabled, each MessageID is cached. However, after all these N MessageIDs arrived, the current implementation does not clear them.
- Add a `func(id []*pb.MessageIdData)` to the ACK grouping tracker. When flushing individual ACKs, construct the slice and wrap the slice to `CommandAck` directly.
- Refactor the implementation of the ACK grouping tracker to have these two data structures:
- `pendingAcks`: Cache the non-batched MessageIDs
- …

Optimize batch index ACK performance

---

go.mod
go.sum
perf/perf-producer.go

Currently, when the rate of the producer is set relatively small, the actual production rate is not accurate.
For example.
```
$ ./pulsar-perf-old produce my-test-r1 -r 1
INFO[17:20:12.524] Stats - Publish rate:    2.9 msg/s -    0.0 Mbps - 
Latency ms: 50%   3.8 -95% 1004.0 - 99% 1004.3 - 99.9% 1004.3 - max 1005.2 
INFO[17:20:22.523] Stats - Publish rate:    3.0 msg/s -    0.0 Mbps - 
Latency ms: 50%   3.8 -95% 1004.0 - 99% 1004.2 - 99.9% 1004.2 - max 1004.9 
INFO[17:20:32.523] Stats - Publish rate:    3.0 msg/s -    0.0 Mbps - 
Latency ms: 50%   3.9 -95% 1004.0 - 99% 1004.0 - 99.9% 1004.0 - max 1004.1 
$ ./pulsar-perf-old produce my-test-r1 -r 5
INFO[17:27:33.597] Stats - Publish rate:    6.9 msg/s -    0.1 Mbps - 
Latency ms: 50%   4.0 -95% 1004.1 - 99% 1005.0 - 99.9% 1005.0 - max …
```

[perf]: More precise producer rate limiter

---

pulsar/dlq_router.go

Fixes #591
dlqrouter should process correctly 
when send error,dlqrouter nack the message
*(or)*
*(or)*
*(example:)*
- Does …

[issue 591] when send error,dlqrouter nack the message

---

perf/perf-consumer.go
pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_partition_test.go
pulsar/consumer_test.go
pulsar/internal/utils.go

Master Issue: #927 
**Note: This is part of the work for [PIP 74](https://github.com/apache/pulsar/wiki/PIP-74%3A-Pulsar-client-memory-limits) in go client.**
The memory limit in consumer side relys on flow control. So we need to firstly support auto scaled consumer receiver queue before we implement the consumer side memory limitation.
The main memory consumption on the consumer side comes from the messages that the consumer prefetches from the broker. Currently, the number of prefetched messages depends on the "current available permits" which represents the messages that have been delivered to the user. When the `availablePermits` reach a certain threshold, the client will send a `Flow` request to the broker to prefetch messages. The current threshold is half of the "receiverQueueSize" …

[feat]: Support auto scaled consumer receiver queue

---

pulsar/consumer_partition.go
pulsar/consumer_test.go

Fixes https://github.com/apache/pulsar-client-go/issues/993
When batch index ACK is disabled, if N messages in a batch are acknowledged, currently only the batched message ID of the last message will be acknowledged. This behavior is wrong because we need to acknowledge the whole batch.
- Create a new trackingMessageID that has no batch index and size fields for this case
- Add `TestConsumerBatchIndexAckDisabled` to cover this case

Fix batched messages not ACKed correctly when batch index ACK is disabled

---

pulsar/helper_for_test.go

retryAssert() will cause panic when assert failed.
For example.
```
func TestRetryAssert(t *testing.T) {
retryAssert(t, 5, 200, func() {}, func(t assert.TestingT) bool {
return assert.Equal(t, 1, 12)
})
}
```
Result.
```
=== RUN   TestRetryAssert
--- FAIL: TestRetryAssert (0.20s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1047ffe40]
```
This is because when assert failed, t.Errorf() will be invoked. However, retryAssert passed a nil value.
https://github.com/apache/pulsar-client-go/blob/04ad521e6d061768ff02ac9bf024932d45b2bd94/pulsar/helper_for_test.go#L180
- Fix retryAssert() to avoid panic()

[fix]: Fix panic caused by retryAssert()

---

pulsar/client_impl.go
pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/impl_message.go
pulsar/internal/memory_limit_controller.go
pulsar/internal/memory_limit_controller_test.go

Master Issue: #927 
This is part of the work for [PIP 74](https://github.com/apache/pulsar/wiki/PIP-74%3A-Pulsar-client-memory-limits) in go client.
More details in https://github.com/apache/pulsar-client-go/issues/927 .
- Consumer adds memory limit relate logic.
- Does this pull request introduce a new feature? (**yes** / no)
- If yes, how is the feature documented? (not applicable / docs / **GoDocs** / not documented)

[feat] Support consumer client memory limit

---

CHANGELOG.md
VERSION
stable.txt

Add 0.10.0 change log

---

.github/workflows/bot.yml

Fixes #909 
Change token to `GITHUB_TOKEN`.
After changing, the pulsar bot works fine. Example here:
https://github.com/labuladong/pulsar-client-go/actions/runs/3681253024/jobs/6227745474#step:4:27

[improve][ci] change token name to `GITHUB_TOKEN`

---

pulsar/client.go
pulsar/client_impl.go
pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_partition.go
pulsar/consumer_regex.go
pulsar/helper_for_test.go
pulsar/internal/batch_builder.go
pulsar/internal/commands.go
pulsar/internal/http_client.go
pulsar/internal/key_based_batch_builder.go
pulsar/internal/pulsartracing/consumer_interceptor_test.go
pulsar/message.go
pulsar/producer_partition.go
pulsar/transaction.go
pulsar/transaction_coordinator_client.go
pulsar/transaction_impl.go
pulsar/transaction_test.go

Master Issue:https://github.com/apache/pulsar-client-go/issues/932
Implement transaction coordinator client.
1. Implement transaction coordinator
2. implement transactionImpl
3. Implement transaction in producer and consumer API
*(or)*
*(or)*
*(example:)*
- The public API: …

[feat][txn]Implement transactional consumer/producer API

---

pulsar/message_chunking_test.go

Fixes #983 
Old TestMaxPendingChunkMessages() uses the concurrent message publish to make the consumer discard unavailable chunk. And it's flaky.
So the `sendSingeChunk()` is introduced to manual create scenarios where old chunks should be discarded.
- Fix `TestMaxPendingChunkMessages()`

[Flaky Test]: Fix flaky test TestMaxPendingChunkMessages()

---

pulsar/negative_acks_tracker_test.go

Fixes #1016
The test for negative ack trackers needs to wait sometime to close the message channel. We use this interval time to assert that the negativeAckTracker can trigger the redelivering with the correct time interval.  But we can't assert this interval very precisely due to the concurrent execution. Currently, we reserve only one millisecond for this concurrent execution:
https://github.com/apache/pulsar-client-go/blob/3367cc0cf877faadce0671c412ec827af7d27a16/pulsar/negative_acks_tracker_test.go#L45-L49
Here, 100 milliseconds is for the client tick delay. But we only wait for another 1 millisecond. This seems too short and introduces the flaky.
This PR waits for more 200 milliseconds. This will not affect the correctness of the test. Because the minimum interval NackDelay we used …

[fix] Fix flaky test in `negative_acks_tracker_test.go`

---

pulsar/producer_partition.go
pulsar/producer_test.go

Fixes #1013
The event time is not set when batching is disabled. The event time will be lost.
This is a regression bug in 0.10.0.
* Set the event time when sending single message

[fix] Fix event time not being set when batching is disabled

---

pulsar/producer_partition.go
pulsar/schema.go

use golang/hash/maphash instead of crypto/sha256 for hash function of hashmap in Schema.hash()
as the hash function is used for determining the hash key, it is safe to use a non-cryptographic function.
Fixes #1021
Improve performance of the SchemaCache by replacing the cryptographic hash function.
Replaced the crypto/sha256 with golang/hash/maphash function.

[Issue 1021][client] FIX: use maphash instead of crypto/sha256 for hash function of hashmap in Schema.hash()

---

pulsar/producer_partition.go

This closes https://github.com/apache/pulsar-client-go/issues/1020.

chore: improve logs on failTimeoutMessages

---

Dockerfile

The master branch is broken:
```
E: Package 'openjdk-11-jre-headless' has no installation candidate
The command '/bin/sh -c apt-get update && apt-get install -y openjdk-11-jre-headless ca-certificates' returned a non-zero code: 100
make: *** [Makefile:41: container] Error 100
```
See https://github.com/apache/pulsar-client-go/actions/runs/5274623023/jobs/9543594971?pr=1029
It's because the latest `golang` image does not have the `openjdk-11-jre-headless`
Install `openjdk-17-jre-headless` instead.

Fix broken master by upgrading JRE to 17

---

pulsar/producer_partition.go

Fixes #1027
fix send timeout error cause by reconnection failures
After #691 , client avoid blocking the reconnection logic, but it also make reconnection and internalSend/internalFlush have concurrency issues。
when the client connection is block, it run into `p.grabCnx()` to get new connection and resend pendingQueue messages. At the same time, the internalSend/internalFlush keep running by use pendingQueue and  send mssage by `p._getConn().WriteData`. Therefore, it received an ack larger than expected, and trigger the ConnectionClosed logic, then the client enter `p.reconnectToBroker()` and repeat the concurrency issues with internalSend/internalFlush, fall into a reconnect-resend-connectionClosed loop
- Dependencies (does it add or …

[Issue 1027][producer] fix: split sendRequest and make reconnectToBroker and other operate in the same coroutine

---

Dockerfile

The master branch is broken:
```
head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory
Exception in thread "main" java.lang.InternalError: Error loading java.security file
```
See https://github.com/apache/pulsar-client-go/actions/runs/5368805969/jobs/9740647704?pr=999
Use `openjdk-17-jre` to replace `openjdk-17-jre-headless`.
https://github.com/crossoverJie/pulsar-client-go/pull/4

Fix openjdk-17

---

pulsar/client.go
pulsar/client_impl.go
pulsar/internal/connection.go
pulsar/internal/http_client.go

My company requires specific cipher suites and control over TLS version used for security.
ClientOptions now has TLSCipherSuites, TLSMinVersion, and TLSMaxVersion. These are used when creating tls.Config objects.
This change is a trivial rework / code cleanup without any test coverage, simple pass-along variables to tls.Config objects.
- The schema: (don't know)
- If yes, how is the feature documented? (not documented)
- If a feature is not applicable for documentation, explain why? Simple pass-along features with comments.
- If a …

Allow user to specify TLS ciphers an min/max TLS version

---

pulsar/consumer_partition.go
pulsar/producer_partition.go
pulsar/producer_test.go

When batching is disabled, the ordering key couldn't be configured and parsed correctly. This is a regression bug.
For the reproducible code, please see the test `TestNoBatchSendMessagesWithMetadata` in this PR.
* Set the ordering key when publishing a single message
* Parsed the ordering key when consuming a single message
This change added tests: `TestBatchSendMessagesWithMetadata` and `TestNoBatchSendMessagesWithMetadata` …

[fix] Fix ordering key not being set and parsed when batching is disabled

---

pulsar/producer_partition.go

Fixes #<xyz>
In pulsar/producer_partition.go, there are many cases that calling the callback without checking if it is nil or not, it will be panic if the input callback is nil at runtime.
- Modified pulsar/producer_partition.go
*(or)*
*(or)*
*(example:)*
- …

[Fix] check if callback is nil before calling it

---

pulsar/producer_partition.go

Fixes #<xyz>
There are duplicated code lines and typo errors in producer_partition.go, fix them.
*(or)*
*(or)*
*(example:)*
*If `yes` was chosen, please …

[Refactor] refactor duplicated code lines and fix typo errors

---

pulsar/producer_partition.go

Fixes #1040
Master Issue: #1040
fix #1040, return when registerSendOrAckOp() return an error.
- modified: pulsar/producer_partition.go
*(or)*
*(or)*
*(example:)*
- …

[Fix] return when registerSendOrAckOp() failed

---

docs/release-process.md

The link to the `GPG keys to sign release artifacts` is dead.
The link of the tag is incorrectly pointed to the pulsar-client-node.

Fix the wrong link in the relesae process

---

pulsar/producer_partition.go
pulsar/producer_test.go

Fixes #<xyz>
Check if a message is nil before accessing it in `partitionProducer.internalSendAsync()`
- pulsar/producer_partition.go
- pulsar/producer_test.go
*(or)*
*(or)*
*(example:)*
*If …

[Fix][Producer] check if message is nil

---

CHANGELOG.md
VERSION
stable.txt

Add 0.11.0 change log

---

pulsar/producer_partition.go
pulsar/producer_test.go

Fixes #877 
The original PR is #878. Because the original author @billowqiu has not continued to reply to the review comments for a long time, resubmit the fix here.
- Add select for ctx and doneCh in partitionProducer.Send()
- If a feature is not documented yet in this PR, please create a followup issue for …

[fix] [issue 877] Fix ctx in partitionProducer.Send() is not performing as expected

---

pulsar/producer_partition.go
pulsar/producer_test.go

Currently, if `!p.options.DisableBlockIfQueueFull` and `msg.Value != nil && msg.Payload != nil`, request will be blocked forever 'cause `defer request.stopBlock()` is set up after the verify logic. 
```go
if msg.Value != nil && msg.Payload != nil {
p.log.Error("Can not set Value and Payload both")
runCallback(request.callback, nil, request.msg, errors.New("can not set Value and Payload both"))
return
}
// The block chan must be closed when returned with exception
defer request.stopBlock()
```
Here is the PR to stop block request even if Value and Payload are both set
- pulsar/producer_partition.go
*(or)*
This change is already covered by existing tests, such as …

[Fix][Producer] Stop block request even if Value and Payload are both set

---

pulsar/producer_partition.go

Fixes #1044
Master Issue: #1044
Simplify the producer flush logic
1. add a callback field to the pendingItem, default is nil;
2. in partitionProducer.internalFlush() get the last pendingItem from pendingQueue;
3. update the last pendingItem by setup a new callback;
4. in partitionProducer.ReceivedSendReceipt, no need to identify the sendRequest by checking if the msg is nil;
5. in pendingItem.Complete(), invoke its callback to notify the flush is done.
*(or)*
This change is already covered by …

[Improve][Producer] simplify the flush logic

---

pulsar/producer_partition.go
pulsar/producer_test.go

Fixes #1051 
The producer memory limit have some problem when `EnableChunking=true` or `Schema` is set.
- When `Schema` is set, the actual message payload is `msg.Value`. The `len(msg.Payload)` may be 0 and memory can not be reserved acurate.
https://github.com/apache/pulsar-client-go/blob/be3574019383ac0cdc65fec63e422fcfd6c82e4b/pulsar/producer_partition.go#L479-L494
- In chunking, if producer meets the memory limit, it should release the memory for **chunks which has send out**. But the calculate for this release is not accurate, it should be `uncompressedPayloadSize - int64(lhs)` instead of `uncompressedPayloadSize - int64(rhs)`
https://github.com/apache/pulsar-client-go/blob/be3574019383ac0cdc65fec63e422fcfd6c82e4b/pulsar/producer_partition.go#L662-L664
- In chunking, if …

[fix] [issue 1051]: Fix inaccurate producer mem limit in chunking and schema

---

pulsar/producer_partition.go

Fixes #1057 
`dataChan` is introduced by #1029  to fix the problem of reconnectToBroker. But it missed that if a flush operation excuted, there may still be some messages in `dataChan`. And these messages can't be flushed.
- Fix the producer flush opertion is not guarantee to flush all messages

[fix] [issue 1057]:  Fix the producer flush opertion is not guarantee to flush all messages

---

pulsar/producer_partition.go
pulsar/producer_test.go

Fixes #1064 
If we set producer `DisableBatching=true`, it will be panic when call `producer.Flush()`. More details in #1064 .
- Avoid panic in non-batching producer
- Add unit test to cover `Flush()` in non-batching producer.

[fix] [issue 1064] Fix the panic when try to flush in DisableBatching=true

---

pulsar/consumer_partition.go
pulsar/producer_partition.go
pulsar/transaction_test.go

Master https://github.com/apache/pulsar-client-go/issues/1060
1. For the chunk message, we only register the send operation once but end the send operation multiple times when receiving the send response. It will make the transaction can be committed before all the operations are completed.
2. When we use transaction ack for chunk messages, the provided transaction is ignored, resulting in the chunk message actually being acknowledged using the non-transactional ack method.
1. Only end the send operation when receive the last chunk message.
2. Add the check for the transaction when the massage is a chunk message.
*(or)*
This change is already covered by existing tests, …

[fix][txn] Fix the transaction acknowledgement and send logic for  chunk message

---

pulsar/consumer_partition.go
pulsar/producer_partition.go

When a consumer fails to get created, we should close any resources that it created to prevent leaks of internal resources and leaks of the consumer on the broker side. The broker leak could happen if the connection was left open. These fixes are similar to #1061.
* Close `ackGroupingTracker` and `chunkedMsgCtxMap` if `grabConn` fails. We cannot call `Close` on the consumer because the state is not `Ready`. If we re-design the consumer, it could be nice to be able to call `Close` in this scenario.
* Call `Close` on the consumer in cases where we move it to `Ready` but determine it is not able to be created.
* Fix typo in comment
This is a trivial change.

[fix] Close consumer resources if creation fails

---

pulsar/auth/tls.go
pulsar/internal/connection.go

When using pulsar tls authentication with a broker that sets the authenticationRefreshCheckSeconds the connection was dropped for each authentication refresh check. After analyzing logs and tcpdumps I concluded that this error appears because the tls authentication is returning null, witch does not pass a validation in the broker.
After analyzing the tls auth implementation in Java (that works), I concluded that the GetData method should return empty byte array instead of nil.
```
2023-07-20 15:32:32 2023-07-20T14:32:32,225+0000 [pulsar-io-29-5] INFO  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:42304] Refreshing authentication credentials for originalPrincipal null and authRole pulsar-admin
2023-07-20 15:32:32 2023-07-20T14:32:32,225+0000 [pulsar-io-29-9] INFO …
```

Fix: client reconnected every authenticationRefreshCheckSeconds when using tls authentication

---

pulsar/producer.go

After #1029 , `eventChan` is split into `dataChan` and `cmdChan`.  But the description of `SendAsync()` is not modified.
https://github.com/apache/pulsar-client-go/blob/9867c29ca329302e97ddd9c6a99f66853c7f447f/pulsar/producer.go#L226-L231
- Correct the description of SendAsync() description

[fix] Correct the SendAsync() description

---

pulsar/client_impl.go
pulsar/client_impl_test.go

Fixes #1026 
Multiple calls to `client.Close` causes panic.
Add `closeOnce sync.Once`

[Fix] Multiple calls to client.Close causes panic

---

pulsar/reader.go
pulsar/reader_impl.go
pulsar/reader_test.go

Implement the GetLastMSgID API for Reader.
*(or)*
*(or)*
*(example:)*
- Does this pull request introduce a new feature? (yes …

[improve][client] Implement GetLastMSgID for Reader

---

pulsar/client.go

The default value of `ConnectionMaxIdleTime` is said to be 60 seconds in the comment,
https://github.com/apache/pulsar-client-go/blob/2a15a251d25bd2a6276051d71873e9e106cc1e85/pulsar/client.go#L155-L157
but it actually seems to be 180 seconds. 60 seconds is the minimum value, not the default value.
https://github.com/apache/pulsar-client-go/blob/2a15a251d25bd2a6276051d71873e9e106cc1e85/pulsar/client_impl.go#L39-L40

[fix] Fix comment for ConnectionMaxIdleTime

---

pulsar/client_impl.go
pulsar/internal/connection.go

Fixes #1094 
connection.go's net.Dialer gets timeout with the default setting occasionally. The default has been increased by PR #563 but I think increasing the pulsar-client-go library default is not the answer, instead we should respect net.Dialer's default.
Although the ConnectionTimeout can be a user specified value at the NewClient() creation, the default is 10 seconds that is hard coded in client_impl.go (https://github.com/apache/pulsar-client-go/blob/master/pulsar/client_impl.go#L34)
In fact, the previous value was 5 seconds. It was increased to 10 seconds by this PR https://github.com/apache/pulsar-client-go/pull/563
I believe we should not tweak Go's default, instead to respect the OS default. Here is the Go's net.Dialer comments. It states the TCP timeouts are often around 3 …

[issue 1094] connectionTimeout respects net.Dialer default timeout

---

pulsaradmin/pkg/admin/auth/oauth2.go

Current `pulsaradmin` OAuth2 params don't support to input the scope field. Add a function to implement it. `ClientCredentialsFlowOptions` has a `AdditionalScopes` field to set scopes.

Support OAuth2 with scope field

---

pulsar/producer_partition.go
pulsar/producer_test.go

When producing a message, we can specify the `DisableReplication` option, and if set to true, the message is expected not to be replicated to remote clusters. However, this option currently does not work, and even if set to true, messages will be replicated to remote clusters.
The following part is the cause of this issue.
https://github.com/apache/pulsar-client-go/blob/ac9c1a6399336461d2d3ce1cdd31cac6debd5ed5/pulsar/producer_partition.go#L554-L559
If `DisableReplication` is true, `ReplicationClusters` is set to `__local__`. However, the metadata that is actually sent to the broker has already been constructed immediately before that. Therefore, there is no point in changing the value of `ReplicationClusters` here. The order of these two must be reversed.
Construct the metadata after …

[fix] Fix issue where DisableReplication flag does not work

---

pulsar/consumer_partition.go

I have a topic with 4 partitions and multiple subscriptions. One of the subscriptions (in keyshared mode) is stuck while consuming from one partition, while the other subscriptions and this particular subscription consuming from other partitions are working fine.
After communicating with the cloud service provider, they believe that it is caused by a consumer not acknowledging the messages it received. However, in my code, I have closed the consumer, so the server should not be waiting indefinitely.
After checking the logs and the code, I believe the situation was as follows:
1. The server notifies the consumer to reconnect and starts sleeping at this line: https://github.com/apache/pulsar-client-go/blob/master/pulsar/consumer_partition.go#L1645.
2. In my code logic, I closed the …

double check before consumer reconnect

---

pulsar/producer_partition.go

Fixes #1071
Master Issue: #1071
Spilt PR #1071 into multiple ones, this is the FIRST one.
#1071 is a BIG PR, it refactor the sending logic, here we just rename `pendingItem.Complete()` to `pendingItem.done()` , and we will add `sendRequest.done()` in #1110 to make them have the same name and meaning.
*(or)*
*(or)* …

[PR-1071-1] rename pendingItem.Complete() to  pendingItem.done()

---

pulsar/producer_partition.go

Fixes #1071
Master Issue: #1071
Spilt PR #1071 into multiple ones, this is the SECOND one.
https://github.com/apache/pulsar-client-go/pull/1071 is a BIG PR, it refactor the sending logic, here we just add fields to `sendRequest` add `sendRequest.done()`  to make `sendRequest` can keep track of the resouces it applied and can release them together.
*(or)*
*(or)*
This …

[ PR-1071-2] add sendRequest.done() to release resource together

---

pulsar/producer_partition.go

This refers to #1071.
The main object is to move schema validation and codec to internalSendAsnc from internalSend. This is a self-contained step for `validateMsg`.

refactor: factor out validateMsg

---

pulsar/producer_interceptor.go

The comment against the `BeforeSend` method in the `ProducerInterceptor` interface is incomplete. Whilst it's fairly easy to infer the missing words, the comment is clearer when complete.
https://github.com/apache/pulsar-client-go/blob/af56e6031d8021ddcff188f94c4d744eba3b3211/pulsar/producer_interceptor.go#L21-L22
Completed the comment so it reads
```
// BeforeSend This is called before send the message to the brokers. This method is allowed to modify the
// message.
```
This is the first time I've come across these interceptors so I've verified that the `BeforeSend` method can modify the message: https://go.dev/play/p/UQ4Q1MNPOpf
- The …

[fix] Complete comment on ProducerInterceptor interface BeforeSend method

---

pulsar/message_chunking_test.go
pulsar/producer_partition.go

This refers to https://github.com/apache/pulsar-client-go/pull/1071. This follows up to https://github.com/apache/pulsar-client-go/pull/1118.
1. Factor out updateSchema
2. Factor out updateUncompressedPayload 
3. Factor out updateMetaData
4. Factor out updateChunkInfo
5. Move all these methods (expect updateChunkInfo which we will handle resource later) to internalSendAsync so that we populate the sendrequest in application thread
6. Drop stopBlock
- If yes, how is …

refactor: prepare sendrequest and move to internalSendAsync

---

pulsar/producer_partition.go

Fixes #<xyz>
The debug log in `ReceivedSendReceipt()` telling us that the client is closing the connection when `pi.sequenceID > response.GetSequenceId()`, but actually it does not, that will make the user confused when debugging.
``` go
if pi.sequenceID < response.GetSequenceId() {
// Force connection closing so that messages can be re-transmitted in a new connection
p.log.Warnf("Received ack for %v on sequenceId %v - expected: %v, closing connection", response.GetMessageId(),
response.GetSequenceId(), pi.sequenceID)
p._getConn().Close()
return
} else if pi.sequenceID > response.GetSequenceId() {
// Ignoring the ack since it's referring to a message that has already timed out.
p.log.Warnf("Received ack for %v on sequenceId %v - expected: %v, closing connection", …
```

[improve] make debug log more clearer in ReceivedSendReceipt()

---

pulsar/producer_partition.go

Fixes #1098 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8a8eaa]
goroutine 1 [running]:
github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).internalFlushCurrentBatch(0xc00c6ccc60)
/go/pkg/mod/github.com/apache/pulsar-client-go@v0.11.0/pulsar/producer_partition.go:869 +0x2a
github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).runEventsLoop(0xc00c6ccc60)
/go/pkg/mod/github.com/apache/pulsar-client-go@v0.11.0/pulsar/producer_partition.go:457 +0x1d7
created by github.com/apache/pulsar-client-go/pulsar.newPartitionProducer in goroutine 5713
/go/pkg/mod/github.com/apache/pulsar-client-go@v0.11.0/pulsar/producer_partition.go:203 +0x9bb
when the producer option set to DisableBatching: …

[fix][issue 1098] check batchBuilder in case batch is disabled

---

pulsar/producer_partition.go

Fixes #1008 
Master Issue: #1008 
Fix the same issue of #1008 for producer.
Move the local vars below out of the loop:
``` go
var (
delayReconnectTime time.Duration
defaultBackoff     = internal.DefaultBackoff{}
)
```
*(or)*
*(or)*
*(example:)*
- The …

[Fix][Producer] Fix reconnection backoff logic for producer

---

docs/release-process.md

This PR is to fix a dead link issue discovered by Max Xu:
https://lists.apache.org/thread/5wgxr443w2j86xcydwky3b7xjb719rtk
The link to the KEYS file is a dead link.
- Replace the link with the correct one: https://downloads.apache.org/pulsar/KEYS
- If a feature is not documented yet in this PR, please create a …

[fix] Fix dead link to the KEYS file in the release process

---

pulsar/producer_partition.go

Fixes #<xyz>
`sendRequest ` in producer is a frequently allocated struct, pool it can decrease the memory allocation.
1. Init a sync.Pool;
2. Get sendRequest  from the pool when we need; 
3. Reset sendRequest and put it back into the pool when it is done.
Benchmark test:
``` go
package test_test
import (
"context"
"github.com/apache/pulsar-client-go/pulsar"
_ "net/http/pprof"
"os"
"runtime/pprof"
"sync/atomic"
"testing"
)
var (
client   pulsar.Client
producer pulsar.Producer
)
func init() {
var err error
client, err = pulsar.NewClient(pulsar.ClientOptions{
URL: "pulsar://127.0.0.1:6650",
})
if …
```

[Improve] pool sendRequest to improve producer perf

---

pulsar/table_view_impl.go

When TableView fails to read a message with the schema the error message is malformed, e.g.
```
ERRO[0000] msg.GetSchemaValue() failed with %!w(*pulsar.message=&{[..snipped..]}); msg is schema not found for topic: [..snipped..], schema version : [ [0 0 0 0 0 0 0 0] ]
```
The correct formatting will help users to debug their issues.
Switch error args to match the formatting directives and context of the message. …

[fix][TableView] Correct argument order to Errorf in TableView message handling

---

pulsar/producer_partition.go

Fixes #1084
Master Issue: #1084
Fix the same issue of https://github.com/apache/pulsar-client-go/pull/1084 for producer.
Add double check after sleeping:
``` go
// double check
if p.getProducerState() != producerReady {
// Producer is already closing
p.log.Info("producer state not ready, exit reconnect")
return
}
```
*(or)*
*(or)*
*(example:)*
- *Added …

[Fix][Producer] double check before producer reconnect

---

pulsar/producer_partition.go
pulsar/producer_test.go

GoLang Pulsar client library has no support for Topic termination.
When a topic is terminated following should happen at client library side.
1. Producers should stop reconnecting. As once topic is terminated, it is permanent. 
2. All the pending messages should be failed. 
If reconnect is failing with TopicTerminated error. 
Run through the pending messages queue and complete the callback.
After that exit the reconnect loop and set producer state as closing.
Marking producer state producerClosing will ensure that new messages are immediately failed.

When topic is terminated. Client must not retry connecting to broker.

---

pulsar/table_view.go
pulsar/table_view_impl.go
pulsar/table_view_test.go

Fixes #1132 
Fix issue #1132 - using JSONSchema with TableView
- Set a concrete type in the `payload` variable before JSON-unmarshalling into that variable. This allows the JSON package to identify and use the type rather than seeing it as `interface{}`.
- Use `reflect.Indirect(payload).Interface()` when storing the payload and passing it to listeners to remove the pointer from `reflect.New`.
- Add test coverage for `TableView.Get` covering all supported schema types.
- Add test coverage for `TableView.ForEachAndListen` for JSONSchema.
Additional minor changes. They didn't seem worth their own MRs but I'm happy to split them out if that's better.
- Correct typo in comments on `TableView.ForEach` and `TableView.ForEachAndListen` interface methods.
- Correct `TableView.ForEachAndListen` …

[Issue 1132] Fix JSONSchema unmarshalling in TableView

---

pulsar/consumer_impl.go
pulsar/consumer_regex_test.go
pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/internal/pulsar_proto/PulsarApi.pb.go
pulsar/reader_impl.go

Releted PR: https://github.com/apache/pulsar/pull/21589
Set DLQ producerName `%s-%s-DLQ`
- The default values of configurations: (yes)
- If yes, how is the feature documented? (not documented)

[Improve] Set dlq producerName

---

pulsar/transaction_impl.go

When aborting or committing a transaction, it can happen that an error returned from the client triggers a panic when attempting to cast it to a Pulsar error.
A proper check is performed when casting the error.
- If a feature is not documented yet in this PR, please create a followup issue for adding …

[transaction] Avoid a panic when using transaction

---

pulsar/internal/connection.go

Fixes #<xyz>
When I run client in K8s pods(keepAliveInterval=5s), connections are closed occasionally, I can't find the root cause, when I look into the code, I found `c.lastDataReceivedTime` is not updated in `doHandshake()`, if we have no data to send the first check of `c.lastDataReceivedTime` probably tell the connection is stale and close it, I think it is better to update `c.lastDataReceivedTime` when doHandshake() succeed.
```go
newConnection()// the first set here
doHandshake()// not set here
internalReceivedCommand()// the second set here
runPingCheck()// the first check here
```
```go …
```

[Improve] update connection.lastDataReceivedTime when connection is ready

---

pulsar/consumer.go

I recently notice that some users using `Unsubscribe()` interface to stop receiving messages from current subscribed topic. But this action can lead to losing messages if retention policy exceed.
We can add some comment in the `Unsubscribe` interface, and this comment can base on [native Java sdk client](https://github.com/apache/pulsar/blob/181b20bf59fdf51734c375b6563c8f1020a71881/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L53).
- If yes, how is the feature documented? N/A
- If a feature is not …

[Improve] update Unsubscribe() interface comment

---

pulsaradmin/pkg/utils/topic_auto_creation_config.go

Fixes #1105
To allow setting the AutoTopicCreation policy to non-partitioned it is required to not send the partitions parameter, by making Partitions a pointer instead of an int this is possible.
Change type of Partitions in TopicAutoCreationConfig from int to *int
I tested it by using it in our application as the admin code currently does not have much test code. I saw here https://github.com/apache/pulsar-client-go/pull/1085 that there are reorganization plans + setting up test scaffolding in the future.

[Issue 1105][pulsaradmin] fix AutoTopicCreation for type non-partitioned

---

pulsaradmin/pkg/admin/namespace.go
pulsaradmin/pkg/admin/namespace_test.go
pulsaradmin/pkg/utils/topic_auto_creation_config.go

Fixes #<xyz>
The `GetTopicAutoCreation` endpoint is missed, needs to add it
Implement the `GetTopicAutoCreation` method
- If a …

[Improve] Implement GetTopicAutoCreation

---

pulsar/consumer_impl.go
pulsar/consumer_regex_test.go
pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/reader_impl.go

Releted PR: https://github.com/apache/pulsar/pull/21890
Set DLQ producerName `fmt.Sprintf("%s-%s-%s-DLQ", r.topicName, r.subscriptionName, r.consumerName)`
- If a feature is not documented yet in this PR, please …

[fix] Fix DLQ producer name conflicts when multiples consumers send messages to DLQ

---

pulsar/internal/compression/zstd_cgo.go
pulsar/internal/utils.go
pulsar/producer_test.go

Fixes #1163
Thanks @0x4500 for reporting this issue and providing the analysis. 
https://github.com/apache/pulsar-client-go/pull/1121 introduces a regression bug. The compression logic has been moved from `internalSend` to `internalSendAsync` which leads to the compression being executed concurrently.
However, `zstd_cgo` doesn't support concurrent compression of data. To prevent this, we need to introduce a mutex.
- Add mutex for zstd_cgo
I have run the benchmark and shows that this change has a minimal impact on performance.
Before this PR(I have also provided other compression provider benchmark for reference.):
```
BenchmarkCompression
BenchmarkCompression/zlib
BenchmarkCompression/zlib-12         	     388	   2904783 ns/op	  34.63 MB/s
BenchmarkCompression/lz4 …
```

Fix SIGSEGV with zstd compression enabled

---

pulsar/consumer_test.go
pulsar/internal/pulsartracing/producer_interceptor_test.go
pulsar/producer.go
pulsar/producer_impl.go
pulsar/producer_partition.go
pulsar/producer_test.go
pulsar/reader_test.go

The producer's `Flush` method does not respect context cancellation. If the caller's context get's cancelled, it will have to wait for the producer to finish flushing.
This change adds a `FlushWithCtx` method which takes a context and selects on two channels.
This change is already covered by existing tests. See code changes for relevant tests.
- If a feature is not applicable for documentation, explain why? It's a very trivial change. It adds a common pattern in Go.
- If …

[Producer] respect context cancellation in Flush

---

pulsar/schema.go
pulsar/schema_test.go
pulsar/table_view_test.go

This fixes #1175 
This fixes the BytesSchema by adding it into the switch-case in the NewBytes constructor, and adds a test showing that it can be used in a producer and consumer. Before the fix, the test fails due to the unrecognised schema in the constructor and the producer and consumer fail to encode the message.
The motivation is that BytesSchema appears to be intended as the default schema (e.g. see [here](https://github.com/petermnhull/pulsar-client-go/blob/master/pulsar/consumer_impl.go#L92) for the Consumer) instead of defining no schema at all, but this code-path is never hit as no Schemas have the NONE type.
I first started looking at this when using a TableView with a topic without a defined or consistent Schema, and I have a work in progress branch for that which will rely on …

Fix BytesSchema

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/reader.go
pulsar/reader_impl.go
pulsar/reader_test.go

Master Issue: #1177
Currently, there is an issue with the reader implementation. If the reader is creating, it won't get the topic metadata from the topic. The reader can only read messages from a single topic. If the topic is a partitioned topic, the reader won't know that and will try to create a non-partition topic with the same name. And it will lead to this issue: https://github.com/apache/pulsar/issues/22032
- Support partitioned topic reader
This change added tests.
- Does this pull request introduce a new feature? (yes …

[feat] Support partitioned topic reader

---

pulsar/consumer_partition.go

Fixes #1180 
In the `MessageReceived`, the number of skipped messages should be increased to available permits to avoid skipped permits leading flow request not be sent.

[Bug Fix]Fix available permits in MessageReceived

---

pulsar/client_impl.go
pulsar/consumer_partition.go
pulsar/reader.go
pulsar/reader_impl.go
pulsar/reader_test.go

Fixes #1171
If `getLastMessageId` continually fails, the reader.HasNext can get stuck in an infinite loop. Without any backoff, the reader would keep trying forever.
- Implemented a backoff policy for `getLastMessageID`.
- If HasNext fails, it now returns false.
Currently, the `HasNext` method doesn't report errors. However, failure is still possible. For instance, if `getLastMessageID` repeatedly fails and hits the retry limit. An option is to keep trying forever, but this would stall all user code. This isn't user-friendly, so I rejected this solution.
The `HasNext` retry mechanism requires to use of `IsMaxBackoffReached` for the backoff. But it isn't exposed in the `BackOffPolicy` interface. Introducing a new method to the `BackOffPolicy` would introduce breaking changes for the user …

[fix] Fix Infinite Loop in Reader's `HasNext` Function

---

Makefile
pulsar/consumer_test.go
pulsaradmin/pkg/admin/topic.go
pulsaradmin/pkg/admin/topic_test.go
pulsaradmin/pkg/utils/data.go

Releted PR: https://github.com/apache/pulsar/pull/21611
Add `GetStatsOptions` params.

[Improve] Add optional parameters for getPartitionedStats

---

.github/workflows/ci.yml
Dockerfile
Makefile
scripts/run-ci.sh

There are related discussion records [here](https://github.com/apache/pulsar-client-go/pull/1037). It is recommended to switch the base image to `apachepulsar/pulsar`.
Change base image to `apachepulsar/pulsar`.

[Improve]Change base image to apachepulsar/pulsar

---

integration-tests/tokens/admin-token
pulsaradmin/pkg/admin/brokers.go
pulsaradmin/pkg/admin/brokers_test.go
pulsaradmin/pkg/utils/data.go

Releted PR: https://github.com/apache/pulsar/pull/11268
Add `HealthCheckWithTopicVersion` interface.
*(or)*
*(or)*
*(example:)*
- The wire protocol: …

[Improve] Add admin api HealthCheckWithTopicVersion

---

Dockerfile
Makefile

Test container image is built for `amd64` platforms only. This makes it difficult to test and run on others, notably Apple Silicon chips running `arm64`.
The source of the problem is using the hardcoded `amd64` Go binary distribution during the image build. On Apple Silicon, running `make test` yields the following error:
```
...
docker run -i pulsar-client-go-test:latest bash -c "cd /pulsar/pulsar-client-go && ./scripts/run-ci.sh"
+ export GOPATH=/pulsar/go
+ GOPATH=/pulsar/go
+ export GOCACHE=/tmp/go-cache
+ GOCACHE=/tmp/go-cache
+ go mod download
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
./scripts/run-ci.sh: line 26:     7 Trace/breakpoint trap   go mod download
make: *** [test] Error 133
```
Sourcing the local platform name from `uname -m` and using it to …

[fix][build] Build test container image using current hardware platform

---

Dockerfile
Makefile
integration-tests/clustered/docker-compose.yml
pulsar/client_impl_clustered_test.go
pulsar/client_impl_test.go
pulsar/internal/connection_pool.go
pulsar/reader_clustered_test.go
pulsar/reader_test.go
scripts/run-ci-clustered.sh
scripts/run-ci.sh

Migrate https://github.com/apache/pulsar/pull/22085/ and (parts of) https://github.com/apache/pulsar-client-cpp/pull/411/ over to the Go client. Context for this idea [here](https://github.com/apache/pulsar/pull/22085/files#r1497008116).
Golang client support for blue-green migration needs the connection pool to differentiate between connections with the same logical address, but different physical addresses. Otherwise, the wrong connection might be used by the client, in effect pointing to the old cluster, instead of the new one.
The connection pool maintains a map of connections, keyed by their logical address and a random connection id. This PR proposes including the physical address in the key also, therefore allowing the upper layer to differentiate between connections with identical …

[improve] Use physical address information in connection pool key

---

pulsaradmin/pkg/admin/brokers.go
pulsaradmin/pkg/admin/brokers_test.go
pulsaradmin/pkg/utils/data.go

To keep consistent with the [Java client](https://github.com/apache/pulsar/pull/9799).
Add `GetLeaderBroker` interface.
*(or)*
*(or)*
*(example:)*
- Does this pull …

[Improve] Add admin api GetLeaderBroker

---

pulsaradmin/pkg/admin/brokers.go
pulsaradmin/pkg/admin/brokers_test.go

To keep consistent with the [Java client](https://github.com/apache/pulsar/pull/14702).
Add admin api GetListActiveBrokers
*(example:)*
- If a feature is not documented yet in this PR, please create a …

[Improve] Add admin api GetListActiveBrokers

---

pulsaradmin/pkg/admin/schema.go
pulsaradmin/pkg/admin/schema_test.go

Add admin api ForceDeleteSchema
*(example:)*

[Improve] Add admin api ForceDeleteSchema

---

go.mod
go.sum
oauth2/auth.go

Upgrade go-jwt to v5 to keep up-to-date.
- Upgrade go-jwt to v5 from v3.

[improve] Upgrade golang-jwt to v5

---

pulsaradmin/pkg/admin/schema.go
pulsaradmin/pkg/admin/schema_test.go
pulsaradmin/pkg/utils/schema_util.go

- CreateSchemaBySchemaInfo
- GetVersionBySchemaInfo
- GetVersionByPayload
- TestCompatibilityWithSchemaInfo
- TestCompatibilityWithPostSchemaPayload
*(example:)* …

[Improve] Supplement schema admin api.

---

pulsar/consumer_partition.go
pulsar/consumer_test.go

The consumer should return error when AckCumulative on a Shared/KeyShared subscription
This change added tests

[fix] Return an error when AckCumulative on a Shared/KeyShared subscription

---

pulsar/schema.go

`AvroCodec` is not used.
Remove `AvroCodec` from `JSONSchema`.
*(or)*
*(or)*
*(example:)*
- If yes, how is the …

[cleanup] Remove AvroCodec from JSONSchema

---

pulsar/reader_impl.go
pulsar/reader_test.go
pulsar/table_view_impl.go

Fixes #1218 
Calling Next on a reader already closed will block forever unless the context is canceled. Similarly, the call will not return if a different go routine closes the reader.
Next now listens for the close channel of the consumer to return an error when it closes.
- *Added an integration test that closes the reader and calls Next*
None

[Issue 1218][Reader] Reader Next returns on closed consumer

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_multitopic_test.go
pulsar/consumer_regex.go
pulsar/consumer_regex_test.go
pulsar/consumer_test.go
pulsar/impl_message.go
pulsar/internal/pulsartracing/consumer_interceptor_test.go
pulsar/message.go

Releted PR: https://github.com/apache/pulsar/pull/20040
- Add `GetLastMessageIDs`api for consumer.
- The wire protocol: (yes)

[Improve] PIP-313 Add GetLastMessageIDs API

---

pulsaradmin/pkg/admin/admin.go
pulsaradmin/pkg/admin/brokers.go
pulsaradmin/pkg/admin/brokers_test.go

If users use a custom dynamic configuration, it's better not to do any escaping for the config value. Let the user fill it out manually.
The original implementation will escape the value twice, the first time is here:
https://github.com/apache/pulsar-client-go/blob/a1ce5e6d48fd00d07d45958a5c7482751f0cbb68/pulsaradmin/pkg/admin/brokers.go#L123-L123
the second time is here:
https://github.com/apache/pulsar-client-go/blob/a1ce5e6d48fd00d07d45958a5c7482751f0cbb68/pulsaradmin/pkg/admin/admin.go#L107-L109

fix dynamic config

---

pulsaradmin/pkg/admin/brokers_test.go
pulsaradmin/pkg/rest/client.go

Even https://github.com/apache/pulsar-client-go/pull/1228 fix the double escape error, there still some issue about custom dynamic config.
When the custom config value has `/`, the golang net/http package will unescape it by default. see https://github.com/golang/go/issues/7356
For example, if the config value is a json like `{"key": "https://example.com/"}`, the expected request should be:
```
/admin/v2/brokers/configuration/someConfig/%7B%22key%22%3A%20%22https%3A%2F%2Fexample.com%2F%22%7D
```
But the actual request will be this:
```
/admin/v2/brokers/configuration/someConfig/{"key": "https://example.com/"}
```
And it will causes 404 not found because `/` in the URL. 
If you escape the value twice, it will be:
```
/admin/v2/brokers/configuration/someConfig/%257B%2522key%2522%253A%2520%25 …
```

Fix custom value with `/`

---

pulsar/consumer_impl.go

Reuse function checkMsgIDPartition.
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? (no)
- …

Reuse function checkMsgIDPartition

---

pulsar/consumer_partition.go
pulsar/consumer_test.go

Fixes #1233
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? no
- If a feature is not applicable for …

[Issue 1233] Fix the issue where the AckIDCumulativ cannot return error.

---

pulsar/error.go
pulsar/transaction_coordinator_client.go
pulsar/transaction_disabled_test.go
scripts/run-ci-clustered.sh

If the broker doesn't enable the transaction coordinator, the TC client will still be created without returning any error. And when creating the transaction, it will crash here:
https://github.com/apache/pulsar-client-go/blob/a2d8a9fb0bda1d66cb304b5b4efe797088e8d1a2/pulsar/transaction_coordinator_client.go#L221
This is because the tc.cons will be emtpy.
- Add new error `ErrTransactionCoordinatorNotEnabled`
- Return error `ErrTransactionCoordinatorNotEnabled` if the broker doesn't  enable transaction
- Does this pull request …

[fix] fix the client crash when the transaction coordinator not found

---

Dockerfile

The Dockerfile looks unsupport the ARM arch, which always downloads the golang of the AMD arch.
- Use golang image to install the golang in the Dockerfile
- Switch golang from 1.18 to 1.20 in the Dockerfile, #1230 requires golang@1.20

improve: install golang by image in the Dockerfile

---

pulsar/internal/rpc_client.go
pulsar/producer_partition.go
pulsar/producer_test.go

https://github.com/apache/pulsar-client-go/pull/1210 breaks the producer feature.
When the `MaxConnectionsPerBroker` is greater than 1, the client will create multiple connections, the producer cannot use the correct connect to send the message to the broker:
```
make build
./bin/pulsar-perf produce test01 -r 100 --profile  --max-connections 30 --profile --service-url pulsar://localhost:6650 -q 100 --batching-time 10
INFO[16:40:23.991] Connecting to broker                          remote_addr="pulsar://localhost:6650"
INFO[16:40:23.994] TCP connection established                    local_addr="[::1]:59230" remote_addr="pulsar://localhost:6650"
INFO[16:40:23.996] Connection is ready                           local_addr="[::1]:59230" remote_addr="pulsar://localhost:6650"
INFO[16:40:24.002] …
```

fix: fix producer connection

---

.github/workflows/ci.yml

Improve CI.
- build and test uses the `go-version: [ '1.20', '1.21', '1.22' ]` matrix.
- lint uses the go 1.20(golangci-lint@1.51.2 doesn't work on go 1.21 or later version) version and `golangci/golangci-lint-action@v6`, the lint result will be reported on the pr.

ci: validate multiple version builds and use golangci-lint-action

---

pulsar/internal/batch_builder.go
pulsar/internal/key_based_batch_builder.go
pulsar/internal/key_based_batch_builder_test.go
pulsar/producer_partition.go

When using key-based producing, the key-based batcher cannot guarantee the sequence ID order when flushing messages. This leads to frequent disconnections between the client and the broker, resulting in poor performance.
Here is the related log:
```
time="2024-07-19T03:38:07Z" level=warning msg="Received send error from server: [PersistenceError] : [Cannot determine whether the message is a duplicate at this time]"
time="2024-07-19T03:38:07Z" level=warning msg="Connection was closed" cnx="xxx" producerID=1 producer_name=xxx topic="xxx"
time="2024-07-19T03:38:07Z" level=warning msg="Failed to write on connection" error="use of closed network connection" local_addr="xxx" remote_addr="xxx"
```
The broker receives unordered messages and returns a SendError to the client. This causes the …

[Fix] Fix the key-based batch can't guarantee the ordering when flushing

---

CHANGELOG.md

Add changelog for 0.13.0

---

pulsar/producer_partition.go

Fixes #1236 
When the producer reconnects to the broker, resending the pending messages, and changing the `sentAt`, this will break the `failTimeoutMessages` feature, which compares `sentAt` with the current time to determine if the message has the timeout.
1. Add `createdAt` to `pendingItem` struct.
2. Init the `sentAt` and `createdAt` when sending the message, and update `sentAt` when resending the message to the broker.
Use existing tests.

fix: failTimeoutMessages cannot delete outdated messages

---

oauth2/client_credentials_flow.go
oauth2/client_credentials_flow_test.go
oauth2/client_credentials_provider.go
oauth2/client_credentials_provider_test.go

Fixes https://github.com/streamnative/pulsarctl/issues/1266 which uses the code being touched here.
As the issue shows when using Pulsarctl which works with a context as configuration style, Oauth2 is used under the hood.
However the library does not expose any way to inject the context configuration `scope` value, and then relies on reading that from the `keyFile` for `client_credentials flow`.
However that is not being utilized in the current code as the scope value is not read from from the file.
To allow the usage of oauth2 with a keyfile in Pulsarctl 3+ which it doesn't right now
*Describe the modifications you've …

[Fix] PulsarCtl 1266  Oauth2 Client credentials flow use scopes from the keyfile as well

---

pulsaradmin/pkg/admin/namespace.go
pulsaradmin/pkg/admin/namespace_test.go

Fixes #1253 
Adds support for the get / set / delete `subscriptionExpirationTime` namespace settings.
Created new functions in `namespace.go` that implement support for `subscriptionExpirationTime` settings
- *Added integration tests for new client functions*
- The public API: (**yes** / no)
- Does this pull request introduce a new feature? (**yes** / no)
- If yes, how is the feature documented? (not applicable / docs / **GoDocs** / not documented)
- If a feature is not …

Add support for subscription expiration time namespace settings

---

pulsar/producer_partition.go
pulsar/producer_test.go

Fixes #1259 
When calling Flush or FlushWithCtx after closing the producer, it will panic.
Check the state of the producer before proceeding with a flush and return an error if it is closed already.
- *Added integration test to call FlushWithCtx after Close and see that it returns an error*
None

[Issue 1259][producer] Prevent panic when calling Flush on closed producer

---

pulsar/producer_partition.go

Fixes #1258 
While flushing, the data channel is switched if a new allocated one which can cause the loss of messages because the length can be zero which would stop the procedure and at the same time a new message can be sent to the channel.
Instead of allocating a new channel, it empties the existing one up to the length of the buffer of the channel before proceeding with the flush.
This change is already covered by existing tests, such as *TestFlushInProducer*.

[Issue 1258][producer] Avoid a data race when flushing with load

---

pulsar/consumer.go
pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/producer.go
pulsar/producer_partition.go

Fixes #1239
Add `InitialSubscriptionName` for DLQPolicy.
*(or)*
*(or)*
*(example:)*
- If yes, how is the …

[Improve] Add InitialSubscriptionName for DLQPolicy

---

pulsaradmin/pkg/admin/subscription.go
pulsaradmin/pkg/admin/subscription_test.go
pulsaradmin/pkg/utils/message_id.go
pulsaradmin/pkg/utils/topic_name.go

If peek a partitioned topic, will see a message id: `7316:0:-1:-1`, the parititonIndex should not be -1.
```
pulsarctl subscription peek --count 10 persistent://public/default/my-topic-partition-0 test-sub
Message ID : 7316:0:-1:-1
Properties :
{
"publish-time": "2024-08-08T17:50:39.476+08:00"
}
Message :
00000000  68 65 6c 6c 6f 2d 31                              |hello-1|
```
- Set partition index on peek message.
Add `TestPeekMessageForPartitionedTopic` to cover it.

[fix] peek message will return -1 for partitionIndex

---

pulsaradmin/pkg/admin/namespace.go
pulsaradmin/pkg/admin/namespace_test.go

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

feat: support the namespace offloadThresholdInSeconds API in pulsaradmin pkg

---

pulsar/ack_grouping_tracker.go
pulsar/ack_grouping_tracker_test.go

Fixes #1262
According to #1262 
> The ticker.Stop method is never called on the timedAckGroupingTracker member ticker, and so it is leaked.
Call `t.ticker.Stop()` function when close `timedAckGroupingTracker`.
- Added integration tests

[Issue 1262][consumer] stop timer when close timedAckGroupingTracker

---

pulsar/internal/connection.go

Fixes #1274 
A race can happen while a consumer or a producer is registering itself to the connection to later receive closing notification.
This pull request changes the concurrency model of the connection to properly lock the different actors between the closing procedure and the registration of handlers and listeners. After this, a caller will properly check the state of the connection and aborts if closed, and it will be certain that it will not be registered in concurrency with a closing.
This change is already covered by existing tests.
none
none

[Issue 1274][connection] Refactor connection concurrency model

---

pulsar/consumer_partition.go
pulsar/producer_partition.go

Fixes #1272 
Producers and consumers register themselves to the connection to be notified when it gets closed. Even though the callback push the events in a channel, it can get stuck and the connection pool is locked which prevents any other caller to get a connection.
This PR makes sure that the callback never blocks.
This change is already covered by existing tests.
none

[Issue 1272][connection] Attempt to avoid deadlock during reconnection

---

pulsar/ack_grouping_tracker_test.go
pulsar/default_router.go
pulsar/internal/memory_limit_controller.go
pulsar/producer_partition.go

Fixed panic caused by memory not aligned in arm32 arch.
Move variable that uses 64-bit atomic operations to the front of the structure so that it is 64-bit aligned.

[fix] [Issue 485]Fixed panic caused by memory not aligned in arm32 arch

---

pulsar/ack_grouping_tracker_test.go

Fixes #1291
The `MaxTime` setting for AckGroupingTracker is too short at only 10,000 nanoseconds.
This causes the test very flaky.
- Change the `MaxTime` to 10 seconds
- If a feature is not documented yet in this PR, please create a followup …

[fix] fix flaky test `TestCloseFlushWithTimer`

---

CHANGELOG.md

Add changelog for 0.14.0

---

pulsaradmin/pkg/admin/schema.go
pulsaradmin/pkg/admin/schema_test.go
pulsaradmin/pkg/utils/schema_util.go

Didn't create an issue but I can if that's necessary, otherwise I'll write the details in this PR.
We actively use `pulsarctl` which has a dependency on this library. We have a use case where we want to interogate the SchemaRegistry to retrieve a history of schema versions and observe schema evolution for topics with higher retention (e.g. infinite retention, >6mo retention etc.).
The PR only contains additions such as:
- Added `GetAllSchemas` method to the `Schema` interface
- Added the implementation for the `GetAllSchemas` method
- Added a model for the Pulsar Admin API response
- Added a utility method to convert from this model to a list …

[pulsaradmin] Add GetAllSchemas command

---

pulsar/consumer_partition.go

The message payload is optional and in some cases only message properties are sent. In this case, the message decompression would fail.
Only do the decompression if the payload is not empty.
- If a feature is not applicable for documentation, explain why? it's just a bugfix

[fix] Only decompress the payload if it's not empty

---

Makefile
integration-tests/blue-green/docker-compose.yml
pulsar/blue_green_migration_test.go
scripts/run-ci-blue-green-cluster.sh

Issue #1282
Use pulsar-client-go-test docker to test TestBlueGreenMigrationTestSuite case, so that we can get rid of local environment go pkg dependencies.
1. Use `integration-tests/extensible-load-manager/docker-compose.yml` docker network in `integration-tests/blue-green/docker-compose.yml` green cluster, to make sure two clusters are in the same network environment.
2. Use new unique service names in `integration-tests/blue-green/docker-compose.yml` green cluster to avoid service name duplication.
3. Use service name instead of service forwarding port in pulsar/blue_green_migration_test.go.
- Updated integration tests
- …

[Issue 1282][test] use pulsar-client-go-test docker to test TestBlueGreenMigrationTestSuite case

---

pulsar/consumer_partition.go
pulsar/consumer_partition_test.go

We currently use `chan []*message` as queueCh, and use the slice to stage the messages to send the message to the parent consumer, this will result in excessive use of memory.
This PR optimizes potentially reducing overall memory overhead.
- Use `chan *message` instead of `chan []*message`.
- Fix test.

improve: use chan *message instead of chan []*message as queueCh

---

pulsaradmin/pkg/admin/subscription.go
pulsaradmin/pkg/admin/subscription_test.go

After [pip-279](https://github.com/apache/pulsar/pull/20627), all properties keys and values use json string save to header: `X-Pulsar-Property`
This PR to compatible with this change when using subscription admin API.
Also, Using `pip-279` also avoids the issue where the Go HTTP client automatically formats HTTP headers: https://github.com/golang/go/issues/37834, This will impact the peek command, the previous method might retrieve `properties` with inconsistent casing compared to the user-defined.
- Compatible the HTTP header properties with PIP-279
- Add TestPeekMessageWithProperties to cover this.
- The …

Compatible the HTTP header properties with PIP-279

---

Dockerfile
Makefile
integration-tests/blue-green/docker-compose.yml
integration-tests/clustered/docker-compose.yml
integration-tests/extensible-load-manager/docker-compose.yml
scripts/run-ci.sh

Upgrade image to 4.0.0 and fixed an issue with command line parameter passing in docker compose, related [issue](https://github.com/remkop/picocli/issues/2348).
*(or)*
*(or)*
*(example:)*
- The …

[improve] Upgrade pulsar image to 4.0.0 in tests

---

pulsar/consumer_impl.go
pulsar/consumer_partition.go

Broker's seek logic: 
1. Close the consumer, not connection.
2. Move the read position of the cursor.
3. Return response to the client.
Seek issue:
1. Seek and reconnect requests in the different goroutines, which should be executed serially.
2. Message loss after seek operation based on time: the partitioned topic has multiple consumer partitions, when all seek request is done, the parent consumer will clean up the receive queue, and at the same time, the consumer partition re-reads the message asynchronous. when a message is received, the consumer partition will push the message to the parent consumer, there is a concurrency issue with message cleaning and message push.
- Use the same goroutine to perform the seek and reconnect.
- The parent consumer pauses receiving messages from all …

fix: seek race

---

pulsar/ack_grouping_tracker.go
pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_multitopic_test.go
pulsar/consumer_partition.go
pulsar/consumer_regex.go
pulsar/consumer_test.go
pulsar/consumer_zero_queue.go
pulsar/impl_message.go
pulsar/internal/pulsartracing/consumer_interceptor_test.go

For `Shared` and `Key_Shared` subscriptions, if some messages failed to acknowledge, these messages would never be dispatched to the consumer until restarted. If the number of unacknowledged messages reached the threshold, the broker would never dispatch messages anymore. However, the consumer does not have a chance to check which messages failed to acknowledged.
Even if this case was not hit, if the consumer restarted after consuming many messages, the old unacknowledged messages would be delivered again, which is very confusing and might affect the business logic.
Therefore, we can only enable `AckWithResponse` to know which messages failed to acknowledge. Unfortunately, currently the Go SDK only supports acknowledging single messages. It harms the performance significantly.
To solve …

Support acknowledging a list of message IDs

---

pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/internal/http_client.go
pulsar/internal/retry.go
pulsar/internal/retry_test.go
pulsar/internal/rpc_client.go
pulsar/producer_partition.go
pulsar/producer_test.go
pulsar/reader_test.go
pulsar/retry_router.go
pulsar/transaction_coordinator_client.go

We are using `time.Sleep` and `for` to execute the retry, which cannot be interrupted, this PR will use context and timer to improve this behavior.
The next improvement idea supports passing the context to interrupt the retry, when closing the producer or consumer, we need to do that.
- Add the `Retry` method to execute the try, and use `Retry` instead of `time.Sleep` and `for`.

improve: use ctx and timer instead sleep

---

pulsar/consumer_multitopic.go
pulsar/consumer_multitopic_test.go
pulsar/consumer_partition.go

Currently when a consumer subscribes multiple topic-partitions and `AckWithResponse` is true, the `AckIDList` method will iterate over all internal consumers **sequentially**. It harms the performance especially there are many internal consumers. For example, if the connection of an internal consumer was stuck by some reason, message IDs from other consumer would be blocked for the operation timeout.
In `ackIDListFromMultiTopics`, call `consumer.AckIDList` in goroutines and use a channel to receive all errors from these calls.
Add `TestMultiTopicAckIDListTimeout`, which sets a dummy connection instance whose `SendRequest` never completes the callback, to verify the `AckIDList` call will not take much more time than the operation timeout to complete. Without this improvement, it will take …

Improve the AckIDList performance when there are many topics subscribed

---

pulsar/consumer_impl.go

No longer need to copy variables after version 1.22.
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature …

Remove unnecessary code

---

pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/producer_partition.go

When a consumer or producer reconnects to the broker, the event loop handling the reconnection becomes occupied, preventing the execution of the `close` command. This can result in the inability to properly close the consumer or producer, leading to potential resource management issues.
- Introduce passing a `context` to the retry function. This ensures that when the `context` is completed or canceled, the retry logic is interrupted and stops further attempts.
- Modify the `producer.Close` and `consumer.Close` methods to call the associated `context.CancelFunc` to cancel the reconnection attempts.

Fix close blocked

---

pulsar/consumer_test.go
pulsar/dlq_router.go

Fixes #1297
Master Issue: https://github.com/apache/pulsar/pull/21589
When multiple consumers with same name are using dlq policies at the same time, prompt will throw below exceptions:
`
ERRO[0069] Failed to create DLQ producer  dlq-topic="persistent://<tenant>/<namespace>/<topic>-<subscription>-DLQ" error="server error: ProducerBusy: org.apache.pulsar.broker.service.BrokerServiceException$NamingException: Producer with name '-<subscription>-<consumerName>-DLQ' is already connected to topic"
`
Add a random suffix in dlq producer name like: `opt.Name = fmt.Sprintf("%s-%s-%s-%s-DLQ", r.topicName, r.subscriptionName, r.consumerName, generateRandomName())`
This change is already covered by existing tests, such as `pulsar/consumer_test.go#TestDLQ(t *testing.T)`
*If `yes` was chosen, please …

[Issue 1297][consumer] Fix DLQ producer name conflicts when there are same name consumers

---

.github/workflows/ci.yml
pulsar/consumer_partition.go
pulsar/consumer_zero_queue_test.go

Fixes #1276
In the current situation, when using `zeroQueueConsumer`, the permits will be incremented an additional time.
When using `zeroQueueConsumer`, the permits are managed by itself.
*(or)*
*(or)*
*(example:)*
- …

[Issue 1276] Fix multiple consumers using zeroQueueConsumer

---

pulsar/client.go
pulsar/client_impl.go
pulsar/client_impl_test.go
pulsar/consumer_test.go
pulsar/internal/connection.go
pulsar/internal/connection_pool.go

Reference [Java client](https://github.com/apache/pulsar/pull/20009).
*(or)*
*(or)*
*(example:)*
- If yes, how …

PIP-254: Support configuring client version

---

oauth2/auth.go
oauth2/cache/cache.go
oauth2/store/keyring.go
oauth2/store/store.go
pulsar/consumer_partition.go
pulsar/crypto/default_message_crypto.go
pulsar/internal/commands.go
pulsar/internal/connection.go
pulsar/internal/crypto/producer_encryptor.go
pulsar/primitiveSerDe.go
pulsar/producer_impl.go
pulsar/table_view_impl.go

This pull request wraps errors using `%w` to preserve the original error and provide more meaningful error messages.
* Wrap errors using `%w` to preserve context
* Handle errors using `errors.Is()`
* Remove unreachable code
* Fix typos

fix: wrap errors using %w to preserve context

---

go.mod
go.sum
pulsar/error.go
pulsar/error_test.go
pulsar/producer_partition.go

Use the standard `errors.Join` function to wrap errors.
* Use `errors.Join` to wrap multiple errors
* Remove the `github.com/hashicorp/go-multierror` dependency
This change is already covered by existing tests.

refactor: use errors.Join to wrap multiple errors

---

pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/internal/connection_pool.go
pulsar/internal/lookup_service_test.go
pulsar/internal/rpc_client.go
pulsar/producer_partition.go
pulsar/producer_test.go
pulsar/transaction_coordinator_client.go

This is a catch up for https://github.com/apache/pulsar/pull/21144
When a producer or consumer reconnects, a random number will be generated as the key suffix in `ConnectionPool` to create or get the `Connection` object from the pool.
https://github.com/apache/pulsar-client-go/blob/ffba2a8fd2781f536bc03ec1408f82f6e4ea4d3a/pulsar/internal/connection_pool.go#L159-L160
- Change GetConnection() of connection_pool and add params: keySuffix
- Generate once keySuffix for consumer/producer when create it.
- When reconnecting, use this keySuffix to ensure obtaining the same connection
- Add TestSelectConnectionForSameConsumer and TestSelectConnectionForSameProducer to cover this.

[fix] [client] fix same producer/consumer use more than one connection per broker

---

pulsar/internal/connection.go

Fixes #<xyz>
Master Issue: #1335 #1336 
Reading is run in a seperate goroutine, `connection.incomingCmdCh` is redundant, just call `connection.internalReceivedCommand() directly`.
```go
func (c *connection) run() {
pingSendTicker := time.NewTicker(c.keepAliveInterval)
pingCheckTicker := time.NewTicker(c.keepAliveInterval)
defer func() {
// stop tickers
pingSendTicker.Stop()
pingCheckTicker.Stop()
// all the accesses to the pendingReqs should be happened in this run loop thread,
// including the final cleanup, to avoid the issue
// https://github.com/apache/pulsar-client-go/issues/239
c.failPendingRequests(errConnectionClosed)
c.Close()
}()
// All reads come from the reader goroutine
go c.reader.readFromConnection()  // reading is run in a SEPERATE goroutine here
go …
```

opt: delete redundant channel connection.incomingCmdCh

---

pulsar/consumer_partition.go

Improve the error for the message decompress to include more useful information.
The error log would be :
```
level=error msg="handle message Id: ledgerId:5  entryId:0  partition:-1" consumerID=1 error="failed to decompress message: some error, compression type: 1, payload size: 4, uncompressed size: 4" local_addr="127.0.0.1:49301" remote_addr="pulsar://localhost:6650"
```
- If …

Improve message decompress error

---

pulsar/consumer_test.go
pulsar/internal/connection.go

Fixes #1335
Master Issue: #1335
Sync all the write calls of a connection into one goroutine to avoid potential data/write conflicts
Sync all the write calls of a connection into one goroutine.
No
@shibd @nodece @RobertIndie @BewareMyPower @crossoverJie 
- If a feature is not documented yet in this PR, please create a …

Fix: Potential data/write conflicts

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/consumer_zero_queue_test.go
pulsar/impl_message.go
pulsar/reader.go
pulsar/reader_impl.go
pulsar/reader_test.go

There are **three attributes** to handle seek/filter/subscribe for Reader.
1. `startMessageID`: The start message ID, which can be specified by the user when creating the reader. It can be set to a specific position, or to the `earliest` or `latest`. When creating a consumer, this is [set in the request](https://github.com/apache/pulsar-client-go/blob/9aeeb4e7bbfcaa4039d66ab2857888be2d6fcaf3/pulsar/consumer_partition.go#L1979), and the broker uses it to set mark delete position.
2. `lastDequeuedMsg`: The most recent message dispatched from the consumer's internal queue to the user. **If it's nil, it means no messages have been delivered to the user. If there is a value, it indicates the user has consumed up to this point.**
3. `lastMessageInBroker`: The ID of the last message in the topic …

Fix wrong result of reader.hasNext/Next after seeking by id or time

---

pulsar/consumer_multitopic_test.go
pulsar/internal/connection.go
pulsar/producer_partition.go

Fixes #1337
Master Issue: #1337
Fix potential data race
1. Add a context and a cancel func to pendingItem;
2. In pendingItem.done(), cancel the context;
3. If context is done, stop writing.
No

Fix: Potential data race

---

pulsar/message.go

Master Issue: https://github.com/apache/pulsar/issues/23968
Related Issue: https://github.com/apache/pulsar-site/pull/507
We now support consuming delayed messages with shared and Key-shared type subscriptions, which has been corrected since [pulsar 3.x doc](https://pulsar.apache.org/docs/3.0.x/concepts-messaging/#delayed-message-delivery) in above pr.
But Golang code `deliverAt` and `deliverAfter` comment says we can only support Shared type subscription, so that maybe we need to fix them.
Replace `SubscriptionType=Shared` comment with `SubscriptionType=Shared or SubscriptionType=KeyShared` in deliverAt and deliverAfter api.
- The …

[improve] Update deliverAfter and deliverAt api comment

---

.github/workflows/ci.yml

Because of the ASF policy, the CI cannot use `golangci/golangci-lint-action@v6`, it has been fixed by https://github.com/apache/infrastructure-actions/pull/142.
```
golangci/golangci-lint-action@v6 is not allowed to be used in apache/pulsar-client-go. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace, or matching the following: 1Password/load-secrets-action@*, AdoptOpenJDK/install-jdk@*, BobAnkh/auto-generate-changelog@*, DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8, DavidAnson/markdownlint-cli2-action@v16, EnricoMi/publish-unit-test-result-action@*, JamesIves/github-pages-deploy-action@881db5376404c5c8d621010bcbec0310b58d5e29, …
```

fix: use sha instead of tag for golangci/golangci-lint-action

---

pulsar/auth/athenz.go
pulsar/auth/athenz_test.go

The Athenz auth plugin obtains a role token from the ZTS server to be used for authentication. Depending on the user's environment, it may be necessary to access ZTS through a proxy, but currently the proxy URL is not configurable via the auth plugin.
Modified the Athenz auth plugin to enable users to configure the proxy URL for ZTS. Proxy configuration is supported in v1.12.8 and later of the Athenz library.
https://github.com/AthenZ/athenz/pull/2841
- If yes, how is the feature documented? (not documented)
- If …

[improve] Make ZTS proxy configurable in athenz auth plugin

---

pulsar/consumer_partition.go
pulsar/reader_test.go

The Go client version 0.15.0 introduced a regression bug. If the reader's `startMessageId` is set to the latest, it will hang while reading. This issue can be reproduced using the new test case: `TestReaderReadFromLatest`.
The root cause is a change in behavior from before version 0.15.0. Previously, the consumer would avoid discarding messages if `startMessageId` was set to Latest. This logic was altered in this pull request: https://github.com/apache/pulsar-client-go/pull/1340/files#diff-782cf41d23c24657ede53da5d028f05819b302305ed676c61322b4cfba4265e9L1454-L1457
The following logic was removed:
```go
// if we start at latest message, we should never discard
if pc.options.startMessageID != nil && pc.options.startMessageID.equal(latestMessageID) {
return false
}
```
In version 0.15.0, if …

Fix reader hanging when startMessageId is latest

---

.github/workflows/ci.yml
Makefile
pulsar/reader_test.go
scripts/run-ci-blue-green-cluster.sh
scripts/run-ci-clustered.sh
scripts/run-ci-extensible-load-manager.sh
scripts/run-ci.sh

This PR https://github.com/apache/pulsar-client-go/pull/1351 introduced some changes but breaked the CI. Currently, even if there are some failed tests, the CI won't be failed: https://github.com/apache/pulsar-client-go/actions/runs/14973771263/job/42060743359?pr=1364#step:6:9285
The root cause is because it captures the exit status of the tee command instead of the go test command. This causes the script to report "Tests passed" even when tests actually fail, leading to false positive CI results.
```
$TEST_CMD 2>&1 | tee $TEST_LOG
```
- Use `set -o pipefail` to correctly capture the exit status of the `go test` command in the pipeline
*(or)*
This change is already …

Fix CI can't be failed even the tests are failed

---

docs/release-process.md
scripts/stage-release.sh

The "Build and inspect an artifact." step in the [release process](https://github.com/apache/pulsar-client-go/blob/master/docs/release-process.md) would also include the `.git` folder.
https://lists.apache.org/thread/pndqy7lfb8nrsgjh0wfq1bsrs1g7ds3y
- Added a new script for staging the release artifact: `stag-release.sh`
- Updated the release process to exclude the `.git` folder from the release artifact
- If yes, how is the feature documented? (not applicable / docs …

Fix the staging release process

---

docs/release-process.md

In the release process, we don't update go client release note no the pulsar-site: https://pulsar.apache.org/release-notes/client-go/. This makes the pulsar-site go client release note page outdated.
- Update the release process to update the release note on pulsar-site
- Fix ToC
- If a feature is not documented …

Update the release process to update the release note on pulsar-site

---

pulsaradmin/pkg/admin/topic.go
pulsaradmin/pkg/admin/topic_test.go

Add two methods `UpdateProperties` and `RemoveProperty` to `Topics`. They are the corresponding methods of `updateProperties` and `removeProperties` methods in Java.
P.S. Java's `removeProperties` is confusing. It can only remove one key, so I adopted the `RemoveProperty` name.

Support update or remove topic properties

---

Makefile
pulsar/consumer_test.go

Master Issue: https://github.com/apache/pulsar/issues/23968 
Related pr: https://github.com/apache/pulsar-client-go/pull/1339
Refered to pr [comment](https://github.com/apache/pulsar-client-go/pull/1339#issuecomment-2712819343), there is no test cases about using keyShared subscription mode to consume delayed messages, so that maybe we need to add one.
Add `pulsar/consumer_test/TestConsumerKeySharedWithDelayedMessages` test case.
This change added tests and can be verified. …

[improve] Add testcase to test using keyShared subscription and delayed messages at the same time

---

pulsaradmin/pkg/admin/auth/token.go

Support JSON token file format authentication for Pulsar Admin.
E.g: 
```
{"file": "./mnt/token"}
```
- Add token file format for json.

fix: support json token file format authentication

---

pulsar/backoff/backoff.go
pulsar/internal/service_name_resolver.go

The Go 1.20 release deprecated the `rand.Seed` function, noting that programs should use the `rand.New(rand.NewSource(seed))` method instead. This change was made because using `rand.Seed` affects the global random number generator, which can lead to unexpected behavior in concurrent programs. By updating to the recommended API, we improve the code's forward compatibility and follow Go's best practices for random number generation.
Replaced all occurrences of `rand.Seed(time.Now().UnixNano())` with `rand.New(rand.NewSource(time.Now().UnixNano()))`
Updated variable assignments to use the new random generator instance where applicable
Maintained the same seed behavior (using current nanosecond time) but now with proper instance isolation
Verifying this change
Make sure that the change …

chore: replace deprecated api rand.Seed

---

pulsar/backoff/backoff.go
pulsar/backoff/backoff_test.go
pulsar/transaction_coordinator_client.go

Fixes https://github.com/apache/pulsar-client-go/pull/1363
Above pr removed backoff init() strategy, which initialized a rand seed when package loaded, so that other functions can import  `DefaultBackoff{}` directly.
After pr changes, there is no rand initilization by default, and we need to manually call `NewDefaultBackoff()` instead of `DefaultBackoff{}` to avoid nil issue, example output below:
```
=== RUN   TestTLSConnectionCAError
time="2025-07-02T12:08:20+08:00" level=info msg="Connecting to broker" remote_addr="pulsar+ssl://localhost:6651"
time="2025-07-02T12:08:20+08:00" level=warning msg="Failed to connect to broker." error="tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match localhost" remote_addr="pulsar+ssl://localhost:6651"
--- …
```

[Fix] Fix backoff unit tests

---

pulsar/negative_backoff_policy.go
pulsar/negative_backoff_policy_test.go

Fixes #1384 
Once the redelivery count is high enough, the backoff time overflows to zero causing immediate redelivery.
Check for the overflow to assign the max backoff time in that case.
This change is already covered by existing tests, such as:
- Extend `TestDefaultNackBackoffPolicy_Next` with failing cases added.

[Issue 1384][consumer] Fix the default nack backoff policy

---

pulsar/consumer_multitopic_test.go
pulsar/internal/batch_builder.go
pulsar/internal/buffer.go
pulsar/internal/connection.go
pulsar/internal/key_based_batch_builder_test.go
pulsar/internal/metrics.go
pulsar/producer_partition.go
pulsar/producer_test.go

Fixes https://github.com/apache/pulsar-client-go/issues/1371
The issue is that the buffer is sent to the connection when the data is flushed at this line: https://github.com/apache/pulsar-client-go/blob/0ab28c229e4dab2adb505a135325b6ede6e0e4f4/pulsar/producer_partition.go#L910
Because of this, both the data request in the connection and the pending item hold onto this buffer.
However, if the pending item fails due to a timeout or the producer closing, the buffer is returned to the buffer pool at this line: https://github.com/apache/pulsar-client-go/blob/0ab28c229e4dab2adb505a135325b6ede6e0e4f4/pulsar/producer_partition.go#L1747
Yet, the connection still has this buffer. When the connection tries to handle the data request, it will try to use a buffer that has already been returned. This …

Fix sending buffer race by using proper reference counting

---

integration-tests/blue-green/docker-compose.yml
integration-tests/clustered/docker-compose.yml
integration-tests/extensible-load-manager/docker-compose.yml
pulsaradmin/pkg/admin/topic.go
pulsaradmin/pkg/admin/topic_test.go
pulsaradmin/pkg/utils/auto_subscription_creation.go
pulsaradmin/pkg/utils/auto_subscription_creation_test.go
pulsaradmin/pkg/utils/data.go
pulsaradmin/pkg/utils/offload_policies.go
pulsaradmin/pkg/utils/offload_policies_test.go

…te, max consumers, message size, subscriptions, schema validation, deduplication, replicator dispatch rate, offload policies, auto subscription creation, and schema compatibility strategy
Fixes #<xyz>
The Pulsar Go client's admin APIs for topic-level policies were incomplete and not aligned with the Java client's RESTful APIs. This inconsistency made it difficult for users who work with both Java and Go clients to have a unified experience when managing topic-level policies programmatically.
Currently, many essential topic-level policy management features available in the Java admin client are …

feat: align topics level policies admin apis to java restful apis

---

pulsar/consumer_impl.go
pulsar/consumer_test.go

Fixes #1399 
Master Issue: #1399
`ReconsumeLater` doesnot adds the eventTime in new rebuilded consumer Message before pushing to Retry or Dlq topic 
```go
// line 639 (consumer_impl.go)
consumerMsg := ConsumerMessage{
Consumer: c,
Message: &message{
payLoad:    msg.Payload(),
properties: props,
msgID:      msgID,
eventTime:  msg.EventTime(), //<-- eventTime is added
},
}
if uint32(reconsumeTimes) > c.dlq.policy.MaxDeliveries {
c.dlq.Chan() <- consumerMsg
} else {
c.rlq.Chan() <- RetryMessage{
consumerMsg: consumerMsg,
producerMsg: ProducerMessage{
Payload:      msg.Payload(),
Key:          msg.Key(),
OrderingKey:  msg.OrderingKey(),
Properties:   props,
DeliverAfter: delay,
EventTime:    msg.EventTime(), //<--eventTime is added
},
}
}
```
This change added tests and can be verified as …

[Issue 1399] add eventTime in reconsumeLaterWithCustomProperties func

---

pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/message.go

Fixes https://github.com/apache/pulsar-client-go/issues/1388
Master Issue: https://github.com/apache/pulsar-client-go/pull/907, https://github.com/apache/pulsar/pull/23182
Since pulsar sdk does not support `AckTimeout()` method, we can only use `Nack()` or `ReconsumeLater()` to trigger dlq policy and send messages to dlq. We can find system properties(e.g. `REAL_TOPIC` and `ORIGIN_MESSAGE_ID`) in these dlq messages.
Refer to issue https://github.com/apache/pulsar-client-go/issues/1388, before pr https://github.com/apache/pulsar-client-go/pull/907 `dlq_router#run()` will directly copy properties to create a new dlq message when receiving a message from `dlq.Chan()`. But we only define message properties in ReconsumeLater's `ReconsumeLaterWithCustomProperties()` and not in Nack's …

[Fix] DLQ Messages will lose system properties when sent from reconsumeLater()

---

pulsar/internal/batch_builder.go
pulsar/internal/buffer.go
pulsar/internal/key_based_batch_builder.go
pulsar/internal/key_based_batch_builder_test.go
pulsar/internal/metrics.go
pulsar/producer_partition.go
pulsar/producer_test.go

#1394 introduces the `pulsar_client_sending_buffers_count` metric to track how many buffers are allocated for send purpose and not put back to the pool. However, unlike other metrics, this metric is not client level, so it cannot be attached with `CustomMetricsLabels` in client options.
When a send buffer was not put back to the pool, it means the `Release` method is not called due to some reason. Changing this metric to client level could help locate which client has triggered this bug in an application that has many client instances from different businesses.
Here is an example metric when I configured `CustomMetricsLabels: map[string]string{"key": "value"}` after this change
```
pulsar_client_sending_buffers_count{client="go",key="value"} 1
```

Change the pulsar_client_sending_buffers_count metric to client level

---

.github/workflows/ci.yml
.gitignore
pulsar/consumer_test.go
pulsar/producer_partition.go
pulsar/producer_test.go
pulsaradmin/pkg/admin/subscription_test.go

Fixes #1357
When flushing concurrently with the same producer, the producer potentially creates a deadlock when the callback is only called once but the client waits for the flush request to be done in all `FlushWithCtx()`.
Change the callback function for to a list of callbacks.
Testcase `TestConcurrentFlushInProducer` added in the producer test suite.

[issue #1357][producer] fix: allow multiples callbacks with concurrent producer flushes (async publish)

---

pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_zero_queue_test.go

Fixes #1330 #398
`ZeroQueueConsumer` cannot consume messages when the broker restarts or unload topic.
- Increase `availablePermits` on reconnect for `ZeroQueueConsumer` 
- Add test case for zero queue consumer reconnection
- Suppress/Do not print the "unable to send initial permits to broker" error log when using `ZeroQueueConsumer`.
*(or)*
*(or)*
*(example:)*
*If `yes` was chosen, …

fix: handle reconnection logic for zero queue consumer

---

pulsar/consumer.go
pulsar/consumer_test.go
pulsar/dlq_router.go

When the retry mechanism is enabled, the RLQ producer first sends messages to the RLQ topic using the producer name if passed in the producer options inside the `DLQPolicy`. 
However, **with `DLQPolicy.ProducerOptions.Name` set**, when the delivery count is reached and the consumer `Nack()` the messages, **the DLQ producer sending messages to the DLQ uses RLQ producer name.**
This is an issue, especially for message deduplication process where each producers must have a globally unique name for a given topic.
This PR adds the `DeadLetterTopicProducerName` field to the `DLQPolicy` in order to either allow using a custom producer name or let the client create the producer name with the existing naming pattern.
- Added integration test `TestWithoutDeadLetterTopicDeadLetterTopicProducerName` …

fix: add DLQPolicy.DeadLetterTopicProducerName

---

pulsaradmin/pkg/admin/subscription.go
pulsaradmin/pkg/admin/subscription_test.go

The properties on messages returned by PeekMessages is not returned consistently as described in #1418 
This change makes sure we set all properties from headers before continuing on, so the returned message should consistently contain all properties.
Currently the properties returned is inconsistent on repeated calls, even if the message returned is the same each time.
I've made it so all headers are processed / al properties are set on every message, rather than exiting the loop early which can cause inconsistent results.
- Does this pull request …

[Issue #1418] Fix: Properties not getting consistently set on pulsaradmin subscription message responses
