apache/pulsar-client-go

pulsar/internal/compression/lz4.go

`cloudflare/golz4` is still based on CGo, so we should use a pure-go lz4 library.

Use pure Go LZ4 compression

---

docker-ci.sh
perf/perf-producer.go
run-ci.sh

Added scripts to compile and run the unit tests from a Docker container. 
This will be invoked from Jenkins to validate the PRs.

Added scripts to run unit tests

---

pulsar/impl_producer.go

Fixes #13 
[issues 13] Fix go func(){} usage question

[issues 13] Fix go func(){} usage question

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Copy [apache/pulsar](https://github.com/apache/pulsar/tree/master/.github) issues template.

Add github issues template

---

README.md

Add go report to checking code format
We need to add a check on the code format in ci.

add go report to checking code format

---

pulsar/internal/connection.go

Fixes #47
Fix the map of pendingReqs concurrent issue.

Fix the map of pendingReqs concurrent issue

---

.header
CONTRIBUTING.md
README.md

Improve `README.md` and add `CONTRIBUTING.md` file.

Improve README.md and add CONTRIBUTING.md file

---

CONTRIBUTING.md
pulsar/consumer_test.go
pulsar/impl_partition_consumer.go
pulsar/internal/connection.go

Fixes #53 
Fix concurrent map write and add test case  for this.

[Issue:53] Fix concurrent map write

---

examples/consumer/consumer.go
examples/producer/producer.go
pkg/compression/compression_test.go
pkg/compression/lz4.go
pulsar/consumer_test.go
pulsar/impl_client_test.go
pulsar/impl_consumer.go
pulsar/impl_producer.go
pulsar/internal/checksum.go
pulsar/internal/checksum_test.go
pulsar/internal/commands.go
pulsar/internal/connection.go
pulsar/internal/hash_test.go
pulsar/internal/lookup_service_test.go
pulsar/internal/rpc_client.go
pulsar/producer_test.go
pulsar/test_helper.go
pulsar/unackMsgTracker_test.go
util/error.go
util/util_test.go

Run `golangci-lint run` for formatting code.

Check `golint`, `gofmt` and `go import` for project

---

.gitignore
perf/pulsar-perf-go.go
pulsar/consumer_test.go
pulsar/error.go
pulsar/impl_partition_consumer.go
pulsar/internal/connection.go
pulsar/producer_test.go

- Add some test cases as follows:
- TestConsumer_EventTime
- TestNonPersistentTopic
- TestConsumer_Flow
- Fix consumer connection closed
- Add `pprof` for debug project
- Fix `flow` command logic

Add some test cases for project

---

pulsar/consumer_test.go
pulsar/impl_client.go
pulsar/internal/connection.go

Change-Id: I480f5b8bb580887543cde66824b2f5704f8fa6e8
more clean code
- use `goimports` import lib 
- use switch-case instrad of if-else for newClient in pulsar/impl_client.go
*(or)*
*(or)*
*(example:)*
- …

[refactor] clean code

---

license_test.go
pulsar/impl_consumer.go
run-ci.sh

Add license check for project.

Add license check for project

---

pulsar/impl_partition_producer.go

when poll return nil, type assert will panic.
- add assert check
Fixes #64

[ISSUE #64]fix: avoid assert panic

---

examples/consumer-listener/consumer-listener.go
examples/consumer/consumer.go

Motivation:
code is not fmt, should be with gofmt
Modifications:
- gofmt once
Fixes #74

[ISSUE #74]refactor: gofmt code

---

run-ci.sh

Add race detection to ci tests.
https://golang.org/doc/articles/race_detector.html#Introduction

Add race detection to ci testing.'

---

pulsar/impl_consumer.go
pulsar/impl_partition_consumer.go

Remove global variable usage in consumer code.

Remove usage of global consumer vars.

---

pulsar/impl_producer.go

[ISSUE #87] Ensure all producer partitions are closed.

---

perf/perf-consumer.go
perf/perf-producer.go
perf/pulsar-perf-go.go

Make starting the pprof server option when running produce and consume commands.

Make starting the pprof server optional.

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_test.go

Added integration test for acks and nacks

Added integration test for acks and nacks

---

pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_multitopic_test.go
pulsar/consumer_partition.go
pulsar/helper.go
pulsar/impl_message.go
pulsar/test_helper.go

Implement the multi topic consumer.

Add multi topic consumer.

---

pkg/pb/PulsarApi.pb.go

Update the protobuf file to access some of the new features and commands.

Update protobuf file.

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic_test.go
pulsar/consumer_regex.go
pulsar/consumer_regex_test.go
pulsar/internal/topic_name.go
pulsar/internal/topic_name_test.go
pulsar/test_helper.go

Add a regex consumer like the other clients.

Add regex consumer.

---

CONTRIBUTING.md

[CONTRIBUTING.md] Fix repository link

---

pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_regex.go

Fixes a bug in the subscriber function and converts the multi topic consumer to use the subscriber function.

Fix subscriber bug and use Consumer interface for multi topic consumer.

---

pulsar/consumer_impl.go

Fix #111: set consumer options

---

go.mod
go.sum
integration-tests/license_test.go

Master Issue: #112 
Dummy main file is not a good solution
1. Move license_test file from project root
2. Change file package
3. go mod tidy

[Issue #112] Move license_test from project root; change package name

---

distribution/LICENSE.bin.txt
distribution/license/LICENSE-cobra.txt
distribution/license/LICENSE-compress.txt
distribution/license/LICENSE-errors.txt
distribution/license/LICENSE-go-cmp.txt
distribution/license/LICENSE-go-rate.txt
distribution/license/LICENSE-logrus.txt
distribution/license/LICENSE-lz4.txt
distribution/license/LICENSE-mousetrap.txt
distribution/license/LICENSE-murmur3.txt
distribution/license/LICENSE-perks.txt
distribution/license/LICENSE-pflag.txt
distribution/license/LICENSE-protobuf.txt
distribution/license/LICENSE-testify.txt

- add lib license files for pulsar-client-go

Add lib license files for pulsar-client-go

---

pulsar/consumer_partition.go
pulsar/consumer_regex.go
pulsar/internal/topic_name.go
pulsar/internal/topic_name_test.go

* fix requestID using consumerID
* fix loopclosure issue
* add old style topic support

fix requestID using consumerID && loopclosure issue && add old style topic support

---

pulsar/internal/connection.go
pulsar/internal/connection_reader.go
pulsar/producer_partition.go

This is fixing an issue in which the Ping task is getting stalled when the connection is not writable (eg: network partition with the broker). The checking of connection staleness needs to be done in its own goroutine to ensure it's running even when the write/read routines are blocked.
This makes sure clients can successfully recover from partitions and failures with the brokers, also during the initial handshake. 
Verified that this fixes #107

Fixed detection and handling of stale connections

---

pulsar/client_impl.go
pulsar/internal/rpc_client.go

Implemented operation timeout for RPC requests to broker.

Implemented the operation timeout check

---

pulsar/internal/batch_builder.go
pulsar/message.go
pulsar/producer_partition.go
pulsar/producer_test.go

Fixes #150 . Added support for delay delivery

Set delay delivery when publishing a message

---

examples/reader/reader.go
pulsar/client_impl.go
pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/impl_message.go
pulsar/internal/commands.go
pulsar/reader.go
pulsar/reader_impl.go
pulsar/reader_test.go

Topic reader implementation

---

.gitignore
pulsar/internal/connection_pool.go
pulsar/internal/connection_reader.go
pulsar/internal/rpc_client.go

Fixes #144 
- Add retry logic when getting a connection error

Add retry logic when get connection error

---

README.md

Fixing a typo in a readme.md following changes done in https://github.com/apache/pulsar-client-go/pull/141

Fix: producer code example

---

pulsar/internal/connection.go

Fixes #178
- Fix concurrent map read and map write

[Issue:178]Fix concurrent map read and map write

---

pulsar/consumer.go
pulsar/consumer_impl.go
pulsar/consumer_multitopic.go
pulsar/consumer_partition.go
pulsar/consumer_regex.go
pulsar/consumer_test.go
pulsar/internal/utils.go
pulsar/internal/utils_test.go

Master Issue: #149 
- Add seek by time on consumer
- Add seek by time on consumer
- Add test case

Add seek by time on consumer

---

VERSION
docs/release-process.md
stable.txt

- Add release process file for pulsar-client-go

Add release process file for pulsar-client-go

---

.github/workflows/go.yml
pulsar/consumer_partition.go

Fixes #192
If Consumer Close() is called after Unsubscribe(), it will report error that 
```
"server error: MetadataError: Consumer not found" name=consumer12 subscription=sharedsub0 topic="persistent://tenant/ns/topic"
```
-  Fix consumer not found

Fix consumer not found

---

pulsar/consumer_partition.go

Fixes #194 
- Fix seek by time

[Bug fix] Fix seek by time error

---

CHANGELOG.md

- Add changelog file to project

Add changelog file to project

---

pulsar/consumer_impl.go
pulsar/consumer_partition.go
pulsar/consumer_regex.go

This flag is needed for the regex consumer.

Add flag to disable forced topic creation.

---

README.md

Update reader example to README.md

Update reader example to README.md

---

pulsar/internal/auth/provider.go

---
*Motivation*
Add oauth2 authentication can be constructed by name.

Add oauth2 to the provider

---

VERSION
stable.txt

- Update the version to 0.2.0 for `VERSION` file
- Update the version to 0.2.0 for `stable.txt` file

Update stable version to 0.2.0

---

CHANGELOG.md

Update change log file for 0.2.0 release.
Add `Feature` and `Improve` items.
Update `Contributors` lists.

Update change log file for 0.2.0

---

CHANGELOG.md
VERSION
stable.txt

Update changelog for 0.3.0 release
- Update changelog
- Update `VERSION` file
- Update `statble.txt` file

Update changelogs for 0.3.0

---

docs/release-process.md

At the time of release 0.3.0, some problems were found in the current release process

update release process

---

pulsar/internal/connection.go

In #410 I inadvertently added this statement

Removed unused `import "C"` statement

---

CHANGELOG.md

Signed-off-by: xiaolongran <rxl@apache.org>
Update 0.4.0 changelog file

Update 0.4.0 changelog file

---

pulsar/producer_partition.go

Signed-off-by: jonyhy96 <hy352144278@gmail.com>
Fixes #508

[issue 508] fix: add sentAt when put item into pendingQueue

---

pulsar/internal/connection.go

Signed-off-by: godchen0212 <qingxiang.chen@zilliz.com>
Fixes #498

[issue #498]fix range channel deadlock error

---

pulsar/internal/connection.go

Fixes #520
The panic is triggered because the `Connection.incomingRequestsCh` is already closed in the moment we're trying to do something with that connection.
In order to avoid the race condition, we need to always check if `closeCh` is already closed.

Always check connection close channell, before attempting to put requests

---

CHANGELOG.md
VERSION
stable.txt

Update changelog to 0.5.0
- update changelog
- update version file to 0.5.0
- update stable.txt file to 0.5.0

Update changelog to 0.5.0

---

go.sum
oauth2/auth.go
oauth2/go.mod
oauth2/go.sum

update jwt-go dependency to resolve vulnerabilities

---

pulsar/consumer_partition.go

[issue 516]Add lock for compressionProviders to fix data race problem

---

pulsar/producer_partition.go

Fix: #490 
Add error log when schema encode failed.

[issue 490] Add error log when schema encode failed.

---

VERSION
stable.txt

update version to 0.6.0

---

CHANGELOG.md

Update change log for 0.6.0 release

Update change log for 0.6.0 release

---

pulsar/internal/connection.go

[issue 574] Fix handle send error panic

---

pulsar/internal/service_name_resolver.go

When running test command, the data race warning occurred in my CI environment.
```
==================
WARNING: DATA RACE
Read at 0x00c0007936c0 by goroutine 472:
github.com/apache/pulsar-client-go/pulsar/internal.(*pulsarServiceNameResolver).ResolveHost()
/sd/workspace/src/github.com/apache/pulsar-client-go/pulsar/internal/service_name_resolver.go:66 +0x167
github.com/apache/pulsar-client-go/pulsar/internal.(*rpcClient).RequestToAnyBroker()
/sd/workspace/src/github.com/apache/pulsar-client-go/pulsar/internal/rpc_client.go:82 +0x70
github.com/apache/pulsar-client-go/pulsar/internal.(*lookupService).GetPartitionedTopicMetadata()
/sd/workspace/src/github.com/apache/pulsar-client-go/pulsar/internal/lookup_service.go:183 +0x2ab
github.com/apache/pulsar-client-go/pulsar.(*client).TopicPartition …
```

Fix data race issue in ServiceNameResolver

---

docs/release-process.md

Add some missing information to the release process docs.

Update release docs with missing information

---

CHANGELOG.md

Update change log for 0.7.0 release

Update change log for 0.7.0 release

---

VERSION
stable.txt

Update version to 0.7.0

---

oauth2/go.mod
oauth2/go.sum

Remove unused dependency in `oauth2` module.

Remove unused dependency in `oauth2` module

---

pulsar/consumer.go
pulsar/message.go
pulsar/producer.go
pulsar/reader.go

Fixes #652
Documentation fixes.

[Issue 652] Quick fixes to the documentation for the main building blocks of the library

---

pulsar/consumer_partition.go

fix:add order key to message

---

README.md

Improve docs
Just a minor readme update to help people getting started on the project.
- [ X ] Make sure that the change passes the CI checks.
No
- If yes, how is the feature documented? (not applicable)

readme: add note about how to build and test

---

pulsar/internal/connection_pool.go

Fix closed connection leak

---

README.md
pulsar/internal/pulsartracing/readme.md

Simple change, markdown error fix

Markdown error fix

---

CHANGELOG.md

add 0.8.0 changelog for repo

---

VERSION
stable.txt

Update version file to 0.8.0

---

CHANGELOG.md

add 0.8.1 changelog

---

pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/producer_partition.go

- create dlq producer with schema from consumer 
- address issue #726 
- follow java client to create dlq producer [here](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1984)

Dlq producer on topic with schema

---

pulsar/consumer.go

fix annotation typo in consumer.go

fix annotation typo in consumer.go

---

pulsar/client.go
pulsar/client_impl.go
pulsar/internal/connection.go
pulsar/internal/connection_pool.go

Fix #837 
- Add the `KeepAliveInterval` in the `ClientOptions`

Make keepalive interval configurable

---

pulsar/internal/connection.go

Embed Go SDK version to 0.9.0

---

pulsar/consumer.go

Modifications
fix typo in consumer.go

fix typo in consumer.go

---

.github/workflows/bot.yml

Fixes #867
The bot cannot get PR link.
* Set the `BOT_TARGET_REPOSITORY ` correctly.

[Issue 867][CI] Fix bot cannot get the pr link

---

pulsar/client_impl.go
pulsar/internal/connection.go

[Issue 489] TLS fix for certificate that does not include IP SANS, save hostname before switching to physical addr

---

pulsar/consumer_partition.go
pulsar/producer_test.go

prevent consumer panic on de-serializing message if schema not found

---

pulsar/consumer_test.go
pulsar/dlq_router.go
pulsar/message.go
pulsar/reader_test.go
pulsar/retry_router.go

add messageId and topic as props of DLQ message

---

README.md

See https://go.dev/blog/godoc.org-redirect.
This change is a documentation update without any test coverage.

Use pkg.go.dev badge in the readme

---

.github/workflows/project.yml
Dockerfile
Makefile

Fix CI
- https://github.com/apache/pulsar-client-go/actions/runs/4113122004/jobs/7099523489
- https://github.com/apache/pulsar-client-go/actions/runs/4101318705/jobs/7072982772
- Fixed golangci-lint version
- Using `COPY` instead docker mount

Improve test script

---

pulsar/auth/athenz.go
pulsar/auth/athenz_test.go

As with the Java client (cf. https://github.com/apache/pulsar/pull/19445), make the Athenz auth provider for the Go client support [Copper Argos](https://github.com/AthenZ/athenz/blob/master/docs/copper_argos.md).
Added new parameters `x509CertChain` and `caCert` to the Athenz auth provider. If the parameter `x509CertChain` is passed, the auth provider assumes that Copper Argos is used and presents the X.509 certificate to obtain a role token from ZTS. Existing users will not be affected by this change.

[improve] Athenz auth provider supports Copper Argos

---

pulsar/error.go
pulsar/transaction.go
pulsar/transaction_coordinator_client.go
pulsar/transaction_impl.go
pulsar/transaction_test.go

Master Issue:https://github.com/apache/pulsar-client-go/issues/932
Implement transaction coordinator client.
1. Implement transaction coordinator
2. implement transactionImpl
3. Implement transaction in producer and consumer API
*(or)*
*(or)*
*(example:)*
- The public API: …

[feat][txn]Implement transactionImpl

---

docs/release-process.md

Fix missing link in the release process

[Doc] Fix missing link in the release process

---

CHANGELOG.md

https://github.com/apache/pulsar-client-go/pull/1048#issuecomment-1623565815
- Add @gunli to the new contributor list in 0.11.0 change log

[fix] Fix 0.11.0 change log

---

.asf.yaml

For https://github.com/apache/pulsar-client-go/pull/1079.
We can toggle the config once that PR gets merged.

chore: allow rebase and merge

---

.asf.yaml

Reverts apache/pulsar-client-go#1080
The repo merge has been done. Regular PRs should go with squash and merge.

revrert: allow rebase and merge

---

pulsaradmin/pkg/admin/auth/oauth2.go
pulsaradmin/pkg/utils/utils.go

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

Support load config from env

---

CHANGELOG.md
VERSION
stable.txt

Add 0.11.1 change log

---

pulsaradmin/pkg/admin/topic_test.go

Lacking tests for creating topic using pulsarAdmin
- Add test for admin topic creation
This change added tests.

Add test for admin topic creation

---

CHANGELOG.md
VERSION
stable.txt

Add 0.12.0 change log

---

.github/workflows/codeql.yml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

Added CodeQL static code scanner

---

pulsaradmin/pkg/utils/function_state.go

Fixes https://github.com/apache/pulsar-client-go/issues/1184 & https://github.com/apache/pulsar/issues/22126
- see https://github.com/apache/pulsar-client-go/issues/1184 for details
- make function state values `omitempty`
*(or)*
*(or)*
*(example:)*
- …

fix: make function state values `omitempty`

---

VERSION
docs/release-process.md
stable.txt

We currently have two hardcoded version files in place: `VERSION` which represents the current version and `stable.txt` which represents the current stable version. However, I'm curious about the intended function of these files. Are they merely for developers to conveniently reference the current and stable versions? And what is our approach to managing these files? For instance, how do we determine what constitutes a stable version? If there's no compelling reason to keep these files, I'd propose to remove them.
Please see more discussion here: https://lists.apache.org/thread/mrntb1y7ws173ohtdvz1v8q86pg50cn2
- Remove `VERSION` and `stable.txt` files.
- …

Remove `VERSION` and `stable.txt` files

---

pulsaradmin/pkg/utils/sink_status.go

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

[fix] Change the wrong `SourceInstanceStatusData` in `SinkInstanceStatus`

---

pulsaradmin/pkg/utils/data.go

Fixes #<xyz>
The `runtimeFlags` is been used to allow user to customize the java options for both Kubernetes Runtime & Process runtime, the config can be passed by YAML or JSON via pulsarctl, but not been exposed as any option in CLI.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for …

[improve] expose RuntimeFlags for Pulsar Functions and Connectors

---

.asf.yaml

Improve PR merge.
Add `required_pull_request_reviews` and `required_conversation_resolution` to the `.asf.yaml`.

ci: add merge limitation

---

CHANGELOG.md

Add changelog for 0.13.1

---

pulsar/consumer_partition.go
pulsar/consumer_partition_test.go
pulsar/consumer_test.go

For the issue please refer to the PR description: #1310
Here have an analysis: https://github.com/apache/pulsar-client-go/pull/1310#issuecomment-2499888281
- Rever #1283 
- Add test from #1310 to cover `queueCh` never not full.
- If a feature is not documented yet in this PR, please create a followup issue for …

Revert #1283 and to fix possible deadlock when queueCh is full

---

.gitignore
go.mod
go.sum
pulsar/consumer_partition.go
pulsar/message_chunking_test.go
pulsar/producer_partition.go
pulsar/producer_test.go
pulsar/transaction_coordinator_client.go

Get rid of deprecation messages
Apply deprecation advice
- Dependencies (does it add or upgrade a dependency): yes

Chore: deprecated usages

---

go.mod
go.sum
pulsar/consumer_test.go
pulsar/internal/compression/lz4.go

Currently the version of lz4 used for the go client is v2.0.5 which is to old. This PR upgrades the lz4 to v4.
- Upgrade lz4 to v4
*(or)*
*(or)*
*(example:)*
- The default values of configurations: (yes / …

Upgrade lz4 to v4

---

pulsar/producer_partition.go

Fixes 
Master Issue: #1332 
Return the buffer to the pool after all callbacks have been called
Return the buffer to the pool after all callbacks have been called

Fix potential data race in pendingItem.done()

---

CHANGELOG.md

Add changelog for 0.15.0

---

CHANGELOG.md

Add changelog for 0.15.1
